/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations.async;

import static com.gbg.gocore.operations.Operations.AsyncRequestOperation;

import com.gbg.gocore.SDKConfiguration;
import com.gbg.gocore.models.operations.CreateSandboxScenarioRequest;
import com.gbg.gocore.operations.CreateSandboxScenario;
import com.gbg.gocore.utils.Headers;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.concurrent.CompletableFuture;

public class CreateSandboxScenarioRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final CreateSandboxScenarioRequest.Builder pojoBuilder;
    private CreateSandboxScenarioRequest request;
    private boolean _setterCalled;

    public CreateSandboxScenarioRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = CreateSandboxScenarioRequest.builder();
    }

    public CreateSandboxScenarioRequestBuilder journeyId(@Nonnull String journeyId) {
        this.pojoBuilder.journeyId(journeyId);
        this._setterCalled = true;
        return this;
    }

    public CreateSandboxScenarioRequestBuilder body(@Nullable com.gbg.gocore.models.CreateSandboxScenarioRequest body) {
        this.pojoBuilder.body(body);
        this._setterCalled = true;
        return this;
    }

    private CreateSandboxScenarioRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public CreateSandboxScenarioRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<CreateSandboxScenarioResponse> call() {
        AsyncRequestOperation<CreateSandboxScenarioRequest, CreateSandboxScenarioResponse> operation
              = new CreateSandboxScenario.Async(sdkConfiguration, _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
