/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations.async;

import static com.gbg.gocore.operations.Operations.AsyncRequestOperation;

import com.gbg.gocore.SDKConfiguration;
import com.gbg.gocore.models.operations.GetSandboxScenarioIncludePlatform;
import com.gbg.gocore.models.operations.GetSandboxScenarioRequest;
import com.gbg.gocore.operations.GetSandboxScenario;
import com.gbg.gocore.utils.Headers;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.concurrent.CompletableFuture;

public class GetSandboxScenarioRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final GetSandboxScenarioRequest.Builder pojoBuilder;
    private GetSandboxScenarioRequest request;
    private boolean _setterCalled;

    public GetSandboxScenarioRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = GetSandboxScenarioRequest.builder();
    }

    public GetSandboxScenarioRequestBuilder journeyId(@Nonnull String journeyId) {
        this.pojoBuilder.journeyId(journeyId);
        this._setterCalled = true;
        return this;
    }

    public GetSandboxScenarioRequestBuilder name(@Nonnull String name) {
        this.pojoBuilder.name(name);
        this._setterCalled = true;
        return this;
    }

    public GetSandboxScenarioRequestBuilder includePlatform(@Nullable GetSandboxScenarioIncludePlatform includePlatform) {
        this.pojoBuilder.includePlatform(includePlatform);
        this._setterCalled = true;
        return this;
    }

    private GetSandboxScenarioRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public GetSandboxScenarioRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<GetSandboxScenarioResponse> call() {
        AsyncRequestOperation<GetSandboxScenarioRequest, GetSandboxScenarioResponse> operation
              = new GetSandboxScenario.Async(sdkConfiguration, _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
