/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations.async;

import static com.gbg.gocore.operations.Operations.AsyncRequestlessOperation;

import com.gbg.gocore.SDKConfiguration;
import com.gbg.gocore.operations.Health;
import com.gbg.gocore.utils.Headers;
import com.gbg.gocore.utils.Utils;
import java.util.concurrent.CompletableFuture;

public class HealthRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();

    public HealthRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    
    public HealthRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<HealthResponse> call() {
        AsyncRequestlessOperation<HealthResponse> operation
            = new Health.Async(sdkConfiguration, _headers);
        return operation.doRequest()
            .thenCompose(operation::handleResponse);
    }
}
