/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations.async;

import static com.gbg.gocore.operations.Operations.AsyncRequestOperation;

import com.gbg.gocore.SDKConfiguration;
import com.gbg.gocore.models.operations.SearchAddressesRequest;
import com.gbg.gocore.models.operations.SearchAddressesSecurity;
import com.gbg.gocore.operations.SearchAddresses;
import com.gbg.gocore.utils.Headers;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.util.concurrent.CompletableFuture;

public class SearchAddressesRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private SearchAddressesRequest request;
    private SearchAddressesSecurity security;

    public SearchAddressesRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public SearchAddressesRequestBuilder request(@Nullable SearchAddressesRequest request) {
        this.request = request;
        return this;
    }

    public SearchAddressesRequestBuilder security(@Nonnull SearchAddressesSecurity security) {
        this.security = Utils.checkNotNull(security, "security");
        return this;
    }

    private SearchAddressesRequest _buildRequest() {
        return this.request;
    }
    
    public SearchAddressesRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<SearchAddressesResponse> call() {
        AsyncRequestOperation<SearchAddressesRequest, SearchAddressesResponse> operation
              = new SearchAddresses.Async(sdkConfiguration, security, _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
