/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations.async;

import static com.gbg.gocore.operations.Operations.AsyncRequestOperation;

import com.gbg.gocore.SDKConfiguration;
import com.gbg.gocore.models.operations.SubmitInteractionRequest;
import com.gbg.gocore.models.operations.SubmitInteractionSecurity;
import com.gbg.gocore.operations.SubmitInteraction;
import com.gbg.gocore.utils.Headers;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.util.concurrent.CompletableFuture;

public class SubmitInteractionRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private SubmitInteractionRequest request;
    private SubmitInteractionSecurity security;

    public SubmitInteractionRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public SubmitInteractionRequestBuilder request(@Nullable SubmitInteractionRequest request) {
        this.request = request;
        return this;
    }

    public SubmitInteractionRequestBuilder security(@Nonnull SubmitInteractionSecurity security) {
        this.security = Utils.checkNotNull(security, "security");
        return this;
    }

    private SubmitInteractionRequest _buildRequest() {
        return this.request;
    }
    
    public SubmitInteractionRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<SubmitInteractionResponse> call() {
        AsyncRequestOperation<SubmitInteractionRequest, SubmitInteractionResponse> operation
              = new SubmitInteraction.Async(sdkConfiguration, security, _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
