/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
public class CollectSpec2 {

    public static final CollectSpec2 REQUIRED = new CollectSpec2("required");
    public static final CollectSpec2 OPTIONAL = new CollectSpec2("optional");
    public static final CollectSpec2 CONDITIONAL = new CollectSpec2("conditional");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, CollectSpec2> values = createValuesMap();
    private static final Map<String, CollectSpec2Enum> enums = createEnumsMap();

    private final String value;

    private CollectSpec2(String value) {
        this.value = value;
    }

    /**
     * Returns a CollectSpec2 with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as CollectSpec2
     */ 
    @JsonCreator
    public static CollectSpec2 of(String value) {
        synchronized (CollectSpec2.class) {
            return values.computeIfAbsent(value, v -> new CollectSpec2(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<CollectSpec2Enum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        CollectSpec2 other = (CollectSpec2) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "CollectSpec2 [value=" + value + "]";
    }

    // return an array just like an enum
    public static CollectSpec2[] values() {
        synchronized (CollectSpec2.class) {
            return values.values().toArray(new CollectSpec2[] {});
        }
    }

    private static final Map<String, CollectSpec2> createValuesMap() {
        Map<String, CollectSpec2> map = new LinkedHashMap<>();
        map.put("required", REQUIRED);
        map.put("optional", OPTIONAL);
        map.put("conditional", CONDITIONAL);
        return map;
    }

    private static final Map<String, CollectSpec2Enum> createEnumsMap() {
        Map<String, CollectSpec2Enum> map = new HashMap<>();
        map.put("required", CollectSpec2Enum.REQUIRED);
        map.put("optional", CollectSpec2Enum.OPTIONAL);
        map.put("conditional", CollectSpec2Enum.CONDITIONAL);
        return map;
    }
    
    
    public enum CollectSpec2Enum {

        REQUIRED("required"),
        OPTIONAL("optional"),
        CONDITIONAL("conditional"),;

        private final String value;

        private CollectSpec2Enum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

