/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class Collect1 {

    @JsonProperty("ref")
    private String ref;


    @JsonProperty("spec")
    private CollectSpec1 spec;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("recommended")
    private Boolean recommended;

    @JsonCreator
    public Collect1(
            @JsonProperty("ref") @Nonnull String ref,
            @JsonProperty("spec") @Nonnull CollectSpec1 spec,
            @JsonProperty("recommended") @Nullable Boolean recommended) {
        this.ref = Optional.ofNullable(ref)
            .orElseThrow(() -> new IllegalArgumentException("ref cannot be null"));
        this.spec = Optional.ofNullable(spec)
            .orElseThrow(() -> new IllegalArgumentException("spec cannot be null"));
        this.recommended = recommended;
    }
    
    public Collect1(
            @Nonnull String ref,
            @Nonnull CollectSpec1 spec) {
        this(ref, spec, null);
    }

    public String ref() {
        return this.ref;
    }

    public CollectSpec1 spec() {
        return this.spec;
    }

    public Optional<Boolean> recommended() {
        return Optional.ofNullable(this.recommended);
    }

    public static Builder builder() {
        return new Builder();
    }


    public Collect1 withRef(@Nonnull String ref) {
        this.ref = Utils.checkNotNull(ref, "ref");
        return this;
    }


    public Collect1 withSpec(@Nonnull CollectSpec1 spec) {
        this.spec = Utils.checkNotNull(spec, "spec");
        return this;
    }


    public Collect1 withRecommended(@Nullable Boolean recommended) {
        this.recommended = recommended;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Collect1 other = (Collect1) o;
        return 
            Utils.enhancedDeepEquals(this.ref, other.ref) &&
            Utils.enhancedDeepEquals(this.spec, other.spec) &&
            Utils.enhancedDeepEquals(this.recommended, other.recommended);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            ref, spec, recommended);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Collect1.class,
                "ref", ref,
                "spec", spec,
                "recommended", recommended);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String ref;

        private CollectSpec1 spec;

        private Boolean recommended;

        private Builder() {
          // force use of static builder() method
        }

        public Builder ref(@Nonnull String ref) {
            this.ref = Utils.checkNotNull(ref, "ref");
            return this;
        }

        public Builder spec(@Nonnull CollectSpec1 spec) {
            this.spec = Utils.checkNotNull(spec, "spec");
            return this;
        }

        public Builder recommended(@Nullable Boolean recommended) {
            this.recommended = recommended;
            return this;
        }

        public Collect1 build() {
            return new Collect1(
                ref, spec, recommended);
        }

    }
}
