/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class Config {
    /**
     * The method by which the End User will consume the journey.
     */
    @JsonProperty("delivery")
    private Delivery delivery;

    @JsonCreator
    public Config(
            @JsonProperty("delivery") @Nonnull Delivery delivery) {
        this.delivery = Optional.ofNullable(delivery)
            .orElseThrow(() -> new IllegalArgumentException("delivery cannot be null"));
    }

    /**
     * The method by which the End User will consume the journey.
     */
    public Delivery delivery() {
        return this.delivery;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The method by which the End User will consume the journey.
     */
    public Config withDelivery(@Nonnull Delivery delivery) {
        this.delivery = Utils.checkNotNull(delivery, "delivery");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Config other = (Config) o;
        return 
            Utils.enhancedDeepEquals(this.delivery, other.delivery);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            delivery);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Config.class,
                "delivery", delivery);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Delivery delivery;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The method by which the End User will consume the journey.
         */
        public Builder delivery(@Nonnull Delivery delivery) {
            this.delivery = Utils.checkNotNull(delivery, "delivery");
            return this;
        }

        public Config build() {
            return new Config(
                delivery);
        }

    }
}
