/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import static com.gbg.gocore.operations.Operations.RequestOperation;

import com.gbg.gocore.SDKConfiguration;
import com.gbg.gocore.operations.DeleteInstance;
import com.gbg.gocore.utils.Headers;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nullable;

public class DeleteInstanceRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private DeleteInstanceRequest request;

    public DeleteInstanceRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public DeleteInstanceRequestBuilder request(@Nullable DeleteInstanceRequest request) {
        this.request = request;
        return this;
    }

    private DeleteInstanceRequest _buildRequest() {
        return this.request;
    }
    
    public DeleteInstanceRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public DeleteInstanceResponse call() {
        RequestOperation<DeleteInstanceRequest, DeleteInstanceResponse> operation
              = new DeleteInstance.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
