/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
public class DeviceConnectTokenType1 {

    public static final DeviceConnectTokenType1 BEARER = new DeviceConnectTokenType1("Bearer");
    public static final DeviceConnectTokenType1 D_PO_P = new DeviceConnectTokenType1("DPoP");
    public static final DeviceConnectTokenType1 NA = new DeviceConnectTokenType1("N_A");
    public static final DeviceConnectTokenType1 END_USER = new DeviceConnectTokenType1("end-user");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, DeviceConnectTokenType1> values = createValuesMap();
    private static final Map<String, DeviceConnectTokenType1Enum> enums = createEnumsMap();

    private final String value;

    private DeviceConnectTokenType1(String value) {
        this.value = value;
    }

    /**
     * Returns a DeviceConnectTokenType1 with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as DeviceConnectTokenType1
     */ 
    @JsonCreator
    public static DeviceConnectTokenType1 of(String value) {
        synchronized (DeviceConnectTokenType1.class) {
            return values.computeIfAbsent(value, v -> new DeviceConnectTokenType1(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<DeviceConnectTokenType1Enum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        DeviceConnectTokenType1 other = (DeviceConnectTokenType1) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "DeviceConnectTokenType1 [value=" + value + "]";
    }

    // return an array just like an enum
    public static DeviceConnectTokenType1[] values() {
        synchronized (DeviceConnectTokenType1.class) {
            return values.values().toArray(new DeviceConnectTokenType1[] {});
        }
    }

    private static final Map<String, DeviceConnectTokenType1> createValuesMap() {
        Map<String, DeviceConnectTokenType1> map = new LinkedHashMap<>();
        map.put("Bearer", BEARER);
        map.put("DPoP", D_PO_P);
        map.put("N_A", NA);
        map.put("end-user", END_USER);
        return map;
    }

    private static final Map<String, DeviceConnectTokenType1Enum> createEnumsMap() {
        Map<String, DeviceConnectTokenType1Enum> map = new HashMap<>();
        map.put("Bearer", DeviceConnectTokenType1Enum.BEARER);
        map.put("DPoP", DeviceConnectTokenType1Enum.D_PO_P);
        map.put("N_A", DeviceConnectTokenType1Enum.NA);
        map.put("end-user", DeviceConnectTokenType1Enum.END_USER);
        return map;
    }
    
    
    public enum DeviceConnectTokenType1Enum {

        BEARER("Bearer"),
        D_PO_P("DPoP"),
        NA("N_A"),
        END_USER("end-user"),;

        private final String value;

        private DeviceConnectTokenType1Enum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

