/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.gbg.gocore.utils.LazySingletonValue;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * DeviceConnectResponseBody1
 * 
 * <p>Success
 */
public class DeviceConnectResponseBody1 {
    /**
     * Token used for subsequent operations by the client
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("endUserToken")
    private String endUserToken;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tokenType")
    private DeviceConnectTokenType1 tokenType;

    /**
     * Seconds until the token expires
     */
    @JsonProperty("expiresIn")
    private double expiresIn;

    @JsonCreator
    public DeviceConnectResponseBody1(
            @JsonProperty("endUserToken") @Nullable String endUserToken,
            @JsonProperty("tokenType") @Nullable DeviceConnectTokenType1 tokenType,
            @JsonProperty("expiresIn") double expiresIn) {
        this.endUserToken = endUserToken;
        this.tokenType = Optional.ofNullable(tokenType)
            .orElse(Builder._SINGLETON_VALUE_TokenType.value());
        this.expiresIn = expiresIn;
    }
    
    public DeviceConnectResponseBody1(
            double expiresIn) {
        this(null, null, expiresIn);
    }

    /**
     * Token used for subsequent operations by the client
     */
    public Optional<String> endUserToken() {
        return Optional.ofNullable(this.endUserToken);
    }

    public Optional<DeviceConnectTokenType1> tokenType() {
        return Optional.ofNullable(this.tokenType);
    }

    /**
     * Seconds until the token expires
     */
    public double expiresIn() {
        return this.expiresIn;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Token used for subsequent operations by the client
     */
    public DeviceConnectResponseBody1 withEndUserToken(@Nullable String endUserToken) {
        this.endUserToken = endUserToken;
        return this;
    }


    public DeviceConnectResponseBody1 withTokenType(@Nullable DeviceConnectTokenType1 tokenType) {
        this.tokenType = tokenType;
        return this;
    }


    /**
     * Seconds until the token expires
     */
    public DeviceConnectResponseBody1 withExpiresIn(double expiresIn) {
        this.expiresIn = expiresIn;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DeviceConnectResponseBody1 other = (DeviceConnectResponseBody1) o;
        return 
            Utils.enhancedDeepEquals(this.endUserToken, other.endUserToken) &&
            Utils.enhancedDeepEquals(this.tokenType, other.tokenType) &&
            Utils.enhancedDeepEquals(this.expiresIn, other.expiresIn);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            endUserToken, tokenType, expiresIn);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DeviceConnectResponseBody1.class,
                "endUserToken", endUserToken,
                "tokenType", tokenType,
                "expiresIn", expiresIn);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String endUserToken;

        private DeviceConnectTokenType1 tokenType;

        private double expiresIn;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Token used for subsequent operations by the client
         */
        public Builder endUserToken(@Nullable String endUserToken) {
            this.endUserToken = endUserToken;
            return this;
        }

        public Builder tokenType(@Nullable DeviceConnectTokenType1 tokenType) {
            this.tokenType = tokenType;
            return this;
        }

        /**
         * Seconds until the token expires
         */
        public Builder expiresIn(double expiresIn) {
            this.expiresIn = expiresIn;
            return this;
        }

        public DeviceConnectResponseBody1 build() {
            return new DeviceConnectResponseBody1(
                endUserToken, tokenType, expiresIn);
        }


        private static final LazySingletonValue<DeviceConnectTokenType1> _SINGLETON_VALUE_TokenType =
                new LazySingletonValue<>(
                        "tokenType",
                        "\"Bearer\"",
                        new TypeReference<DeviceConnectTokenType1>() {});
    }
}
