/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
public class DeviceConnectTokenType2 {

    public static final DeviceConnectTokenType2 BEARER = new DeviceConnectTokenType2("Bearer");
    public static final DeviceConnectTokenType2 D_PO_P = new DeviceConnectTokenType2("DPoP");
    public static final DeviceConnectTokenType2 NA = new DeviceConnectTokenType2("N_A");
    public static final DeviceConnectTokenType2 END_USER = new DeviceConnectTokenType2("end-user");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, DeviceConnectTokenType2> values = createValuesMap();
    private static final Map<String, DeviceConnectTokenType2Enum> enums = createEnumsMap();

    private final String value;

    private DeviceConnectTokenType2(String value) {
        this.value = value;
    }

    /**
     * Returns a DeviceConnectTokenType2 with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as DeviceConnectTokenType2
     */ 
    @JsonCreator
    public static DeviceConnectTokenType2 of(String value) {
        synchronized (DeviceConnectTokenType2.class) {
            return values.computeIfAbsent(value, v -> new DeviceConnectTokenType2(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<DeviceConnectTokenType2Enum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        DeviceConnectTokenType2 other = (DeviceConnectTokenType2) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "DeviceConnectTokenType2 [value=" + value + "]";
    }

    // return an array just like an enum
    public static DeviceConnectTokenType2[] values() {
        synchronized (DeviceConnectTokenType2.class) {
            return values.values().toArray(new DeviceConnectTokenType2[] {});
        }
    }

    private static final Map<String, DeviceConnectTokenType2> createValuesMap() {
        Map<String, DeviceConnectTokenType2> map = new LinkedHashMap<>();
        map.put("Bearer", BEARER);
        map.put("DPoP", D_PO_P);
        map.put("N_A", NA);
        map.put("end-user", END_USER);
        return map;
    }

    private static final Map<String, DeviceConnectTokenType2Enum> createEnumsMap() {
        Map<String, DeviceConnectTokenType2Enum> map = new HashMap<>();
        map.put("Bearer", DeviceConnectTokenType2Enum.BEARER);
        map.put("DPoP", DeviceConnectTokenType2Enum.D_PO_P);
        map.put("N_A", DeviceConnectTokenType2Enum.NA);
        map.put("end-user", DeviceConnectTokenType2Enum.END_USER);
        return map;
    }
    
    
    public enum DeviceConnectTokenType2Enum {

        BEARER("Bearer"),
        D_PO_P("DPoP"),
        NA("N_A"),
        END_USER("end-user"),;

        private final String value;

        private DeviceConnectTokenType2Enum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

