/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.gbg.gocore.utils.HasSecurity;
import com.gbg.gocore.utils.SpeakeasyMetadata;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class DeviceConnectSecurity implements HasSecurity {

    @SpeakeasyMetadata("security:scheme=true,type=http,subtype=bearer,name=Authorization")
    private String deviceConnect;

    @JsonCreator
    public DeviceConnectSecurity(
            @Nonnull String deviceConnect) {
        this.deviceConnect = Optional.ofNullable(deviceConnect)
            .orElseThrow(() -> new IllegalArgumentException("deviceConnect cannot be null"));
    }

    public String deviceConnect() {
        return this.deviceConnect;
    }

    public static Builder builder() {
        return new Builder();
    }


    public DeviceConnectSecurity withDeviceConnect(@Nonnull String deviceConnect) {
        this.deviceConnect = Utils.checkNotNull(deviceConnect, "deviceConnect");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DeviceConnectSecurity other = (DeviceConnectSecurity) o;
        return 
            Utils.enhancedDeepEquals(this.deviceConnect, other.deviceConnect);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            deviceConnect);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DeviceConnectSecurity.class,
                "deviceConnect", deviceConnect);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String deviceConnect;

        private Builder() {
          // force use of static builder() method
        }

        public Builder deviceConnect(@Nonnull String deviceConnect) {
            this.deviceConnect = Utils.checkNotNull(deviceConnect, "deviceConnect");
            return this;
        }

        public DeviceConnectSecurity build() {
            return new DeviceConnectSecurity(
                deviceConnect);
        }

    }
}
