/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
public class FetchInteractionConsentType {

    public static final FetchInteractionConsentType ROLLUP = new FetchInteractionConsentType("rollup");
    public static final FetchInteractionConsentType EXPLICIT = new FetchInteractionConsentType("explicit");
    public static final FetchInteractionConsentType IMPLICIT = new FetchInteractionConsentType("implicit");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, FetchInteractionConsentType> values = createValuesMap();
    private static final Map<String, FetchInteractionConsentTypeEnum> enums = createEnumsMap();

    private final String value;

    private FetchInteractionConsentType(String value) {
        this.value = value;
    }

    /**
     * Returns a FetchInteractionConsentType with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as FetchInteractionConsentType
     */ 
    @JsonCreator
    public static FetchInteractionConsentType of(String value) {
        synchronized (FetchInteractionConsentType.class) {
            return values.computeIfAbsent(value, v -> new FetchInteractionConsentType(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<FetchInteractionConsentTypeEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        FetchInteractionConsentType other = (FetchInteractionConsentType) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "FetchInteractionConsentType [value=" + value + "]";
    }

    // return an array just like an enum
    public static FetchInteractionConsentType[] values() {
        synchronized (FetchInteractionConsentType.class) {
            return values.values().toArray(new FetchInteractionConsentType[] {});
        }
    }

    private static final Map<String, FetchInteractionConsentType> createValuesMap() {
        Map<String, FetchInteractionConsentType> map = new LinkedHashMap<>();
        map.put("rollup", ROLLUP);
        map.put("explicit", EXPLICIT);
        map.put("implicit", IMPLICIT);
        return map;
    }

    private static final Map<String, FetchInteractionConsentTypeEnum> createEnumsMap() {
        Map<String, FetchInteractionConsentTypeEnum> map = new HashMap<>();
        map.put("rollup", FetchInteractionConsentTypeEnum.ROLLUP);
        map.put("explicit", FetchInteractionConsentTypeEnum.EXPLICIT);
        map.put("implicit", FetchInteractionConsentTypeEnum.IMPLICIT);
        return map;
    }
    
    
    public enum FetchInteractionConsentTypeEnum {

        ROLLUP("rollup"),
        EXPLICIT("explicit"),
        IMPLICIT("implicit"),;

        private final String value;

        private FetchInteractionConsentTypeEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

