/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import static com.gbg.gocore.operations.Operations.RequestOperation;

import com.gbg.gocore.SDKConfiguration;
import com.gbg.gocore.operations.FetchInteraction;
import com.gbg.gocore.utils.Headers;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;

public class FetchInteractionRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private FetchInteractionRequest request;
    private FetchInteractionSecurity security;

    public FetchInteractionRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public FetchInteractionRequestBuilder request(@Nullable FetchInteractionRequest request) {
        this.request = request;
        return this;
    }

    public FetchInteractionRequestBuilder security(@Nonnull FetchInteractionSecurity security) {
        this.security = Utils.checkNotNull(security, "security");
        return this;
    }

    private FetchInteractionRequest _buildRequest() {
        return this.request;
    }
    
    public FetchInteractionRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public FetchInteractionResponse call() {
        RequestOperation<FetchInteractionRequest, FetchInteractionResponse> operation
              = new FetchInteraction.Sync(sdkConfiguration, security, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
