/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
public class FetchInteractionName {

    public static final FetchInteractionName COM = new FetchInteractionName("COM");
    public static final FetchInteractionName SOD = new FetchInteractionName("SOD");
    public static final FetchInteractionName DG1 = new FetchInteractionName("DG1");
    public static final FetchInteractionName DG2 = new FetchInteractionName("DG2");
    public static final FetchInteractionName DG3 = new FetchInteractionName("DG3");
    public static final FetchInteractionName DG4 = new FetchInteractionName("DG4");
    public static final FetchInteractionName DG5 = new FetchInteractionName("DG5");
    public static final FetchInteractionName DG6 = new FetchInteractionName("DG6");
    public static final FetchInteractionName DG7 = new FetchInteractionName("DG7");
    public static final FetchInteractionName DG8 = new FetchInteractionName("DG8");
    public static final FetchInteractionName DG9 = new FetchInteractionName("DG9");
    public static final FetchInteractionName DG10 = new FetchInteractionName("DG10");
    public static final FetchInteractionName DG11 = new FetchInteractionName("DG11");
    public static final FetchInteractionName DG12 = new FetchInteractionName("DG12");
    public static final FetchInteractionName DG13 = new FetchInteractionName("DG13");
    public static final FetchInteractionName DG14 = new FetchInteractionName("DG14");
    public static final FetchInteractionName DG15 = new FetchInteractionName("DG15");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, FetchInteractionName> values = createValuesMap();
    private static final Map<String, FetchInteractionNameEnum> enums = createEnumsMap();

    private final String value;

    private FetchInteractionName(String value) {
        this.value = value;
    }

    /**
     * Returns a FetchInteractionName with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as FetchInteractionName
     */ 
    @JsonCreator
    public static FetchInteractionName of(String value) {
        synchronized (FetchInteractionName.class) {
            return values.computeIfAbsent(value, v -> new FetchInteractionName(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<FetchInteractionNameEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        FetchInteractionName other = (FetchInteractionName) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "FetchInteractionName [value=" + value + "]";
    }

    // return an array just like an enum
    public static FetchInteractionName[] values() {
        synchronized (FetchInteractionName.class) {
            return values.values().toArray(new FetchInteractionName[] {});
        }
    }

    private static final Map<String, FetchInteractionName> createValuesMap() {
        Map<String, FetchInteractionName> map = new LinkedHashMap<>();
        map.put("COM", COM);
        map.put("SOD", SOD);
        map.put("DG1", DG1);
        map.put("DG2", DG2);
        map.put("DG3", DG3);
        map.put("DG4", DG4);
        map.put("DG5", DG5);
        map.put("DG6", DG6);
        map.put("DG7", DG7);
        map.put("DG8", DG8);
        map.put("DG9", DG9);
        map.put("DG10", DG10);
        map.put("DG11", DG11);
        map.put("DG12", DG12);
        map.put("DG13", DG13);
        map.put("DG14", DG14);
        map.put("DG15", DG15);
        return map;
    }

    private static final Map<String, FetchInteractionNameEnum> createEnumsMap() {
        Map<String, FetchInteractionNameEnum> map = new HashMap<>();
        map.put("COM", FetchInteractionNameEnum.COM);
        map.put("SOD", FetchInteractionNameEnum.SOD);
        map.put("DG1", FetchInteractionNameEnum.DG1);
        map.put("DG2", FetchInteractionNameEnum.DG2);
        map.put("DG3", FetchInteractionNameEnum.DG3);
        map.put("DG4", FetchInteractionNameEnum.DG4);
        map.put("DG5", FetchInteractionNameEnum.DG5);
        map.put("DG6", FetchInteractionNameEnum.DG6);
        map.put("DG7", FetchInteractionNameEnum.DG7);
        map.put("DG8", FetchInteractionNameEnum.DG8);
        map.put("DG9", FetchInteractionNameEnum.DG9);
        map.put("DG10", FetchInteractionNameEnum.DG10);
        map.put("DG11", FetchInteractionNameEnum.DG11);
        map.put("DG12", FetchInteractionNameEnum.DG12);
        map.put("DG13", FetchInteractionNameEnum.DG13);
        map.put("DG14", FetchInteractionNameEnum.DG14);
        map.put("DG15", FetchInteractionNameEnum.DG15);
        return map;
    }
    
    
    public enum FetchInteractionNameEnum {

        COM("COM"),
        SOD("SOD"),
        DG1("DG1"),
        DG2("DG2"),
        DG3("DG3"),
        DG4("DG4"),
        DG5("DG5"),
        DG6("DG6"),
        DG7("DG7"),
        DG8("DG8"),
        DG9("DG9"),
        DG10("DG10"),
        DG11("DG11"),
        DG12("DG12"),
        DG13("DG13"),
        DG14("DG14"),
        DG15("DG15"),;

        private final String value;

        private FetchInteractionNameEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

