/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum FetchInteractionScope {
    SUBJECT("subject"),
    REVIEWER("reviewer");

    @JsonValue
    private final String value;

    FetchInteractionScope(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<FetchInteractionScope> fromValue(String value) {
        for (FetchInteractionScope o: FetchInteractionScope.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

