/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class FetchInteractionRequest {
    /**
     * Journey instance identifier
     */
    @JsonProperty("instanceId")
    private String instanceId;

    @JsonCreator
    public FetchInteractionRequest(
            @JsonProperty("instanceId") @Nonnull String instanceId) {
        this.instanceId = Optional.ofNullable(instanceId)
            .orElseThrow(() -> new IllegalArgumentException("instanceId cannot be null"));
    }

    /**
     * Journey instance identifier
     */
    public String instanceId() {
        return this.instanceId;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Journey instance identifier
     */
    public FetchInteractionRequest withInstanceId(@Nonnull String instanceId) {
        this.instanceId = Utils.checkNotNull(instanceId, "instanceId");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        FetchInteractionRequest other = (FetchInteractionRequest) o;
        return 
            Utils.enhancedDeepEquals(this.instanceId, other.instanceId);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            instanceId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(FetchInteractionRequest.class,
                "instanceId", instanceId);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String instanceId;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Journey instance identifier
         */
        public Builder instanceId(@Nonnull String instanceId) {
            this.instanceId = Utils.checkNotNull(instanceId, "instanceId");
            return this;
        }

        public FetchInteractionRequest build() {
            return new FetchInteractionRequest(
                instanceId);
        }

    }
}
