/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;


public class FetchInteractionExtraction {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("aggregatedFields")
    private List<FetchInteractionAggregatedField> aggregatedFields;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("extractedFields")
    private List<FetchInteractionExtractedField> extractedFields;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("extractedImages")
    private List<FetchInteractionExtractedImage> extractedImages;

    @JsonCreator
    public FetchInteractionExtraction(
            @JsonProperty("aggregatedFields") @Nullable List<FetchInteractionAggregatedField> aggregatedFields,
            @JsonProperty("extractedFields") @Nullable List<FetchInteractionExtractedField> extractedFields,
            @JsonProperty("extractedImages") @Nullable List<FetchInteractionExtractedImage> extractedImages) {
        this.aggregatedFields = aggregatedFields;
        this.extractedFields = extractedFields;
        this.extractedImages = extractedImages;
    }
    
    public FetchInteractionExtraction() {
        this(null, null, null);
    }

    public Optional<List<FetchInteractionAggregatedField>> aggregatedFields() {
        return Optional.ofNullable(this.aggregatedFields);
    }

    public Optional<List<FetchInteractionExtractedField>> extractedFields() {
        return Optional.ofNullable(this.extractedFields);
    }

    public Optional<List<FetchInteractionExtractedImage>> extractedImages() {
        return Optional.ofNullable(this.extractedImages);
    }

    public static Builder builder() {
        return new Builder();
    }


    public FetchInteractionExtraction withAggregatedFields(@Nullable List<FetchInteractionAggregatedField> aggregatedFields) {
        this.aggregatedFields = aggregatedFields;
        return this;
    }


    public FetchInteractionExtraction withExtractedFields(@Nullable List<FetchInteractionExtractedField> extractedFields) {
        this.extractedFields = extractedFields;
        return this;
    }


    public FetchInteractionExtraction withExtractedImages(@Nullable List<FetchInteractionExtractedImage> extractedImages) {
        this.extractedImages = extractedImages;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        FetchInteractionExtraction other = (FetchInteractionExtraction) o;
        return 
            Utils.enhancedDeepEquals(this.aggregatedFields, other.aggregatedFields) &&
            Utils.enhancedDeepEquals(this.extractedFields, other.extractedFields) &&
            Utils.enhancedDeepEquals(this.extractedImages, other.extractedImages);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            aggregatedFields, extractedFields, extractedImages);
    }
    
    @Override
    public String toString() {
        return Utils.toString(FetchInteractionExtraction.class,
                "aggregatedFields", aggregatedFields,
                "extractedFields", extractedFields,
                "extractedImages", extractedImages);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private List<FetchInteractionAggregatedField> aggregatedFields;

        private List<FetchInteractionExtractedField> extractedFields;

        private List<FetchInteractionExtractedImage> extractedImages;

        private Builder() {
          // force use of static builder() method
        }

        public Builder aggregatedFields(@Nullable List<FetchInteractionAggregatedField> aggregatedFields) {
            this.aggregatedFields = aggregatedFields;
            return this;
        }

        public Builder extractedFields(@Nullable List<FetchInteractionExtractedField> extractedFields) {
            this.extractedFields = extractedFields;
            return this;
        }

        public Builder extractedImages(@Nullable List<FetchInteractionExtractedImage> extractedImages) {
            this.extractedImages = extractedImages;
            return this;
        }

        public FetchInteractionExtraction build() {
            return new FetchInteractionExtraction(
                aggregatedFields, extractedFields, extractedImages);
        }

    }
}
