/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
public class FetchInteractionStatusError {

    public static final FetchInteractionStatusError ERROR = new FetchInteractionStatusError("error");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, FetchInteractionStatusError> values = createValuesMap();
    private static final Map<String, FetchInteractionStatusErrorEnum> enums = createEnumsMap();

    private final String value;

    private FetchInteractionStatusError(String value) {
        this.value = value;
    }

    /**
     * Returns a FetchInteractionStatusError with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as FetchInteractionStatusError
     */ 
    @JsonCreator
    public static FetchInteractionStatusError of(String value) {
        synchronized (FetchInteractionStatusError.class) {
            return values.computeIfAbsent(value, v -> new FetchInteractionStatusError(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<FetchInteractionStatusErrorEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        FetchInteractionStatusError other = (FetchInteractionStatusError) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "FetchInteractionStatusError [value=" + value + "]";
    }

    // return an array just like an enum
    public static FetchInteractionStatusError[] values() {
        synchronized (FetchInteractionStatusError.class) {
            return values.values().toArray(new FetchInteractionStatusError[] {});
        }
    }

    private static final Map<String, FetchInteractionStatusError> createValuesMap() {
        Map<String, FetchInteractionStatusError> map = new LinkedHashMap<>();
        map.put("error", ERROR);
        return map;
    }

    private static final Map<String, FetchInteractionStatusErrorEnum> createEnumsMap() {
        Map<String, FetchInteractionStatusErrorEnum> map = new HashMap<>();
        map.put("error", FetchInteractionStatusErrorEnum.ERROR);
        return map;
    }
    
    
    public enum FetchInteractionStatusErrorEnum {

        ERROR("error"),;

        private final String value;

        private FetchInteractionStatusErrorEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

