/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class FetchInteractionContext {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("subject")
    private FetchInteractionSubject subject;

    @JsonCreator
    public FetchInteractionContext(
            @JsonProperty("subject") @Nullable FetchInteractionSubject subject) {
        this.subject = subject;
    }
    
    public FetchInteractionContext() {
        this(null);
    }

    public Optional<FetchInteractionSubject> subject() {
        return Optional.ofNullable(this.subject);
    }

    public static Builder builder() {
        return new Builder();
    }


    public FetchInteractionContext withSubject(@Nullable FetchInteractionSubject subject) {
        this.subject = subject;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        FetchInteractionContext other = (FetchInteractionContext) o;
        return 
            Utils.enhancedDeepEquals(this.subject, other.subject);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            subject);
    }
    
    @Override
    public String toString() {
        return Utils.toString(FetchInteractionContext.class,
                "subject", subject);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private FetchInteractionSubject subject;

        private Builder() {
          // force use of static builder() method
        }

        public Builder subject(@Nullable FetchInteractionSubject subject) {
            this.subject = subject;
            return this;
        }

        public FetchInteractionContext build() {
            return new FetchInteractionContext(
                subject);
        }

    }
}
