/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
public class GetJourneyStateName {

    public static final GetJourneyStateName COM = new GetJourneyStateName("COM");
    public static final GetJourneyStateName SOD = new GetJourneyStateName("SOD");
    public static final GetJourneyStateName DG1 = new GetJourneyStateName("DG1");
    public static final GetJourneyStateName DG2 = new GetJourneyStateName("DG2");
    public static final GetJourneyStateName DG3 = new GetJourneyStateName("DG3");
    public static final GetJourneyStateName DG4 = new GetJourneyStateName("DG4");
    public static final GetJourneyStateName DG5 = new GetJourneyStateName("DG5");
    public static final GetJourneyStateName DG6 = new GetJourneyStateName("DG6");
    public static final GetJourneyStateName DG7 = new GetJourneyStateName("DG7");
    public static final GetJourneyStateName DG8 = new GetJourneyStateName("DG8");
    public static final GetJourneyStateName DG9 = new GetJourneyStateName("DG9");
    public static final GetJourneyStateName DG10 = new GetJourneyStateName("DG10");
    public static final GetJourneyStateName DG11 = new GetJourneyStateName("DG11");
    public static final GetJourneyStateName DG12 = new GetJourneyStateName("DG12");
    public static final GetJourneyStateName DG13 = new GetJourneyStateName("DG13");
    public static final GetJourneyStateName DG14 = new GetJourneyStateName("DG14");
    public static final GetJourneyStateName DG15 = new GetJourneyStateName("DG15");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, GetJourneyStateName> values = createValuesMap();
    private static final Map<String, GetJourneyStateNameEnum> enums = createEnumsMap();

    private final String value;

    private GetJourneyStateName(String value) {
        this.value = value;
    }

    /**
     * Returns a GetJourneyStateName with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as GetJourneyStateName
     */ 
    @JsonCreator
    public static GetJourneyStateName of(String value) {
        synchronized (GetJourneyStateName.class) {
            return values.computeIfAbsent(value, v -> new GetJourneyStateName(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<GetJourneyStateNameEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        GetJourneyStateName other = (GetJourneyStateName) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "GetJourneyStateName [value=" + value + "]";
    }

    // return an array just like an enum
    public static GetJourneyStateName[] values() {
        synchronized (GetJourneyStateName.class) {
            return values.values().toArray(new GetJourneyStateName[] {});
        }
    }

    private static final Map<String, GetJourneyStateName> createValuesMap() {
        Map<String, GetJourneyStateName> map = new LinkedHashMap<>();
        map.put("COM", COM);
        map.put("SOD", SOD);
        map.put("DG1", DG1);
        map.put("DG2", DG2);
        map.put("DG3", DG3);
        map.put("DG4", DG4);
        map.put("DG5", DG5);
        map.put("DG6", DG6);
        map.put("DG7", DG7);
        map.put("DG8", DG8);
        map.put("DG9", DG9);
        map.put("DG10", DG10);
        map.put("DG11", DG11);
        map.put("DG12", DG12);
        map.put("DG13", DG13);
        map.put("DG14", DG14);
        map.put("DG15", DG15);
        return map;
    }

    private static final Map<String, GetJourneyStateNameEnum> createEnumsMap() {
        Map<String, GetJourneyStateNameEnum> map = new HashMap<>();
        map.put("COM", GetJourneyStateNameEnum.COM);
        map.put("SOD", GetJourneyStateNameEnum.SOD);
        map.put("DG1", GetJourneyStateNameEnum.DG1);
        map.put("DG2", GetJourneyStateNameEnum.DG2);
        map.put("DG3", GetJourneyStateNameEnum.DG3);
        map.put("DG4", GetJourneyStateNameEnum.DG4);
        map.put("DG5", GetJourneyStateNameEnum.DG5);
        map.put("DG6", GetJourneyStateNameEnum.DG6);
        map.put("DG7", GetJourneyStateNameEnum.DG7);
        map.put("DG8", GetJourneyStateNameEnum.DG8);
        map.put("DG9", GetJourneyStateNameEnum.DG9);
        map.put("DG10", GetJourneyStateNameEnum.DG10);
        map.put("DG11", GetJourneyStateNameEnum.DG11);
        map.put("DG12", GetJourneyStateNameEnum.DG12);
        map.put("DG13", GetJourneyStateNameEnum.DG13);
        map.put("DG14", GetJourneyStateNameEnum.DG14);
        map.put("DG15", GetJourneyStateNameEnum.DG15);
        return map;
    }
    
    
    public enum GetJourneyStateNameEnum {

        COM("COM"),
        SOD("SOD"),
        DG1("DG1"),
        DG2("DG2"),
        DG3("DG3"),
        DG4("DG4"),
        DG5("DG5"),
        DG6("DG6"),
        DG7("DG7"),
        DG8("DG8"),
        DG9("DG9"),
        DG10("DG10"),
        DG11("DG11"),
        DG12("DG12"),
        DG13("DG13"),
        DG14("DG14"),
        DG15("DG15"),;

        private final String value;

        private GetJourneyStateNameEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

