/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class GetJourneyStateDocumentPhone {
    /**
     * The type of phone number, such as landline, mobile, fax, unknown etc
     */
    @JsonProperty("type")
    private String type;

    /**
     * Phone number, ideally in international format with +(Country Code)
     */
    @JsonProperty("number")
    private String number;

    @JsonCreator
    public GetJourneyStateDocumentPhone(
            @JsonProperty("type") @Nonnull String type,
            @JsonProperty("number") @Nonnull String number) {
        this.type = Optional.ofNullable(type)
            .orElseThrow(() -> new IllegalArgumentException("type cannot be null"));
        this.number = Optional.ofNullable(number)
            .orElseThrow(() -> new IllegalArgumentException("number cannot be null"));
    }

    /**
     * The type of phone number, such as landline, mobile, fax, unknown etc
     */
    public String type() {
        return this.type;
    }

    /**
     * Phone number, ideally in international format with +(Country Code)
     */
    public String number() {
        return this.number;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The type of phone number, such as landline, mobile, fax, unknown etc
     */
    public GetJourneyStateDocumentPhone withType(@Nonnull String type) {
        this.type = Utils.checkNotNull(type, "type");
        return this;
    }


    /**
     * Phone number, ideally in international format with +(Country Code)
     */
    public GetJourneyStateDocumentPhone withNumber(@Nonnull String number) {
        this.number = Utils.checkNotNull(number, "number");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetJourneyStateDocumentPhone other = (GetJourneyStateDocumentPhone) o;
        return 
            Utils.enhancedDeepEquals(this.type, other.type) &&
            Utils.enhancedDeepEquals(this.number, other.number);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            type, number);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetJourneyStateDocumentPhone.class,
                "type", type,
                "number", number);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String type;

        private String number;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The type of phone number, such as landline, mobile, fax, unknown etc
         */
        public Builder type(@Nonnull String type) {
            this.type = Utils.checkNotNull(type, "type");
            return this;
        }

        /**
         * Phone number, ideally in international format with +(Country Code)
         */
        public Builder number(@Nonnull String number) {
            this.number = Utils.checkNotNull(number, "number");
            return this;
        }

        public GetJourneyStateDocumentPhone build() {
            return new GetJourneyStateDocumentPhone(
                type, number);
        }

    }
}
