/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class GetJourneyStateBiometric3 {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    private String id;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("type")
    private String type;


    @JsonProperty("faceImage")
    private String faceImage;

    @JsonCreator
    public GetJourneyStateBiometric3(
            @JsonProperty("id") @Nullable String id,
            @JsonProperty("type") @Nullable String type,
            @JsonProperty("faceImage") @Nonnull String faceImage) {
        this.id = id;
        this.type = type;
        this.faceImage = Optional.ofNullable(faceImage)
            .orElseThrow(() -> new IllegalArgumentException("faceImage cannot be null"));
    }
    
    public GetJourneyStateBiometric3(
            @Nonnull String faceImage) {
        this(null, null, faceImage);
    }

    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }

    public Optional<String> type() {
        return Optional.ofNullable(this.type);
    }

    public String faceImage() {
        return this.faceImage;
    }

    public static Builder builder() {
        return new Builder();
    }


    public GetJourneyStateBiometric3 withId(@Nullable String id) {
        this.id = id;
        return this;
    }


    public GetJourneyStateBiometric3 withType(@Nullable String type) {
        this.type = type;
        return this;
    }


    public GetJourneyStateBiometric3 withFaceImage(@Nonnull String faceImage) {
        this.faceImage = Utils.checkNotNull(faceImage, "faceImage");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetJourneyStateBiometric3 other = (GetJourneyStateBiometric3) o;
        return 
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.type, other.type) &&
            Utils.enhancedDeepEquals(this.faceImage, other.faceImage);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            id, type, faceImage);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetJourneyStateBiometric3.class,
                "id", id,
                "type", type,
                "faceImage", faceImage);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String id;

        private String type;

        private String faceImage;

        private Builder() {
          // force use of static builder() method
        }

        public Builder id(@Nullable String id) {
            this.id = id;
            return this;
        }

        public Builder type(@Nullable String type) {
            this.type = type;
            return this;
        }

        public Builder faceImage(@Nonnull String faceImage) {
            this.faceImage = Utils.checkNotNull(faceImage, "faceImage");
            return this;
        }

        public GetJourneyStateBiometric3 build() {
            return new GetJourneyStateBiometric3(
                id, type, faceImage);
        }

    }
}
