/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;


public class GetJourneyStateDocumentCurrentAddress {
    /**
     * Unformatted line based address
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("lines")
    private List<String> lines;

    /**
     * The address as a single line
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("addressString")
    private String addressString;

    /**
     * The primary delivery point for a premise or building. This could be a house number, a building name,
     * etc.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("premise")
    private String premise;

    /**
     * The name of a building or a building complex. In the US, this is the street number.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("building")
    private String building;

    /**
     * The name of a sub-building, such as a flat or apartment number.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("subBuilding")
    private String subBuilding;

    /**
     * This field holds the most common street or block data element within a country. For instance, USA
     * Street
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("thoroughfare")
    private String thoroughfare;

    /**
     * The name of a dependent street or block, such as a street within a complex.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("dependentThoroughfare")
    private String dependentThoroughfare;

    /**
     * This field holds the most common population center data element within a country. For instance, USA
     * City, Canadian Municipality
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("locality")
    private String locality;

    /**
     * This is a smaller area within a locality, such as a neighborhood or district. Like Manhattan in New
     * York City, or Soho in London.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("dependentLocality")
    private String dependentLocality;

    /**
     * This is an even smaller area within a dependent locality, often used in very detailed addresses.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("doubleDependentLocality")
    private String doubleDependentLocality;

    /**
     * This field contains the complete postal code for a particular delivery point, should such detail be
     * able to be determined. For example ZIP code in the US
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("postalCode")
    private String postalCode;

    /**
     * This field contains the post box number associated with a particular delivery point, should one
     * exist.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("postBox")
    private String postBox;

    /**
     * Country the address is in. It must be a valid ISO2 or ISO3 country code
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("country")
    private String country;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("superAdministrativeArea")
    private String superAdministrativeArea;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("administrativeArea")
    private String administrativeArea;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("subAdministrativeArea")
    private String subAdministrativeArea;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("organization")
    private String organization;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("location")
    private GetJourneyStateDocumentCurrentAddressLocation location;

    @JsonCreator
    public GetJourneyStateDocumentCurrentAddress(
            @JsonProperty("lines") @Nullable List<String> lines,
            @JsonProperty("addressString") @Nullable String addressString,
            @JsonProperty("premise") @Nullable String premise,
            @JsonProperty("building") @Nullable String building,
            @JsonProperty("subBuilding") @Nullable String subBuilding,
            @JsonProperty("thoroughfare") @Nullable String thoroughfare,
            @JsonProperty("dependentThoroughfare") @Nullable String dependentThoroughfare,
            @JsonProperty("locality") @Nullable String locality,
            @JsonProperty("dependentLocality") @Nullable String dependentLocality,
            @JsonProperty("doubleDependentLocality") @Nullable String doubleDependentLocality,
            @JsonProperty("postalCode") @Nullable String postalCode,
            @JsonProperty("postBox") @Nullable String postBox,
            @JsonProperty("country") @Nullable String country,
            @JsonProperty("superAdministrativeArea") @Nullable String superAdministrativeArea,
            @JsonProperty("administrativeArea") @Nullable String administrativeArea,
            @JsonProperty("subAdministrativeArea") @Nullable String subAdministrativeArea,
            @JsonProperty("organization") @Nullable String organization,
            @JsonProperty("location") @Nullable GetJourneyStateDocumentCurrentAddressLocation location) {
        this.lines = lines;
        this.addressString = addressString;
        this.premise = premise;
        this.building = building;
        this.subBuilding = subBuilding;
        this.thoroughfare = thoroughfare;
        this.dependentThoroughfare = dependentThoroughfare;
        this.locality = locality;
        this.dependentLocality = dependentLocality;
        this.doubleDependentLocality = doubleDependentLocality;
        this.postalCode = postalCode;
        this.postBox = postBox;
        this.country = country;
        this.superAdministrativeArea = superAdministrativeArea;
        this.administrativeArea = administrativeArea;
        this.subAdministrativeArea = subAdministrativeArea;
        this.organization = organization;
        this.location = location;
    }
    
    public GetJourneyStateDocumentCurrentAddress() {
        this(null, null, null,
            null, null, null,
            null, null, null,
            null, null, null,
            null, null, null,
            null, null, null);
    }

    /**
     * Unformatted line based address
     */
    public Optional<List<String>> lines() {
        return Optional.ofNullable(this.lines);
    }

    /**
     * The address as a single line
     */
    public Optional<String> addressString() {
        return Optional.ofNullable(this.addressString);
    }

    /**
     * The primary delivery point for a premise or building. This could be a house number, a building name,
     * etc.
     */
    public Optional<String> premise() {
        return Optional.ofNullable(this.premise);
    }

    /**
     * The name of a building or a building complex. In the US, this is the street number.
     */
    public Optional<String> building() {
        return Optional.ofNullable(this.building);
    }

    /**
     * The name of a sub-building, such as a flat or apartment number.
     */
    public Optional<String> subBuilding() {
        return Optional.ofNullable(this.subBuilding);
    }

    /**
     * This field holds the most common street or block data element within a country. For instance, USA
     * Street
     */
    public Optional<String> thoroughfare() {
        return Optional.ofNullable(this.thoroughfare);
    }

    /**
     * The name of a dependent street or block, such as a street within a complex.
     */
    public Optional<String> dependentThoroughfare() {
        return Optional.ofNullable(this.dependentThoroughfare);
    }

    /**
     * This field holds the most common population center data element within a country. For instance, USA
     * City, Canadian Municipality
     */
    public Optional<String> locality() {
        return Optional.ofNullable(this.locality);
    }

    /**
     * This is a smaller area within a locality, such as a neighborhood or district. Like Manhattan in New
     * York City, or Soho in London.
     */
    public Optional<String> dependentLocality() {
        return Optional.ofNullable(this.dependentLocality);
    }

    /**
     * This is an even smaller area within a dependent locality, often used in very detailed addresses.
     */
    public Optional<String> doubleDependentLocality() {
        return Optional.ofNullable(this.doubleDependentLocality);
    }

    /**
     * This field contains the complete postal code for a particular delivery point, should such detail be
     * able to be determined. For example ZIP code in the US
     */
    public Optional<String> postalCode() {
        return Optional.ofNullable(this.postalCode);
    }

    /**
     * This field contains the post box number associated with a particular delivery point, should one
     * exist.
     */
    public Optional<String> postBox() {
        return Optional.ofNullable(this.postBox);
    }

    /**
     * Country the address is in. It must be a valid ISO2 or ISO3 country code
     */
    public Optional<String> country() {
        return Optional.ofNullable(this.country);
    }

    public Optional<String> superAdministrativeArea() {
        return Optional.ofNullable(this.superAdministrativeArea);
    }

    public Optional<String> administrativeArea() {
        return Optional.ofNullable(this.administrativeArea);
    }

    public Optional<String> subAdministrativeArea() {
        return Optional.ofNullable(this.subAdministrativeArea);
    }

    public Optional<String> organization() {
        return Optional.ofNullable(this.organization);
    }

    public Optional<GetJourneyStateDocumentCurrentAddressLocation> location() {
        return Optional.ofNullable(this.location);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Unformatted line based address
     */
    public GetJourneyStateDocumentCurrentAddress withLines(@Nullable List<String> lines) {
        this.lines = lines;
        return this;
    }


    /**
     * The address as a single line
     */
    public GetJourneyStateDocumentCurrentAddress withAddressString(@Nullable String addressString) {
        this.addressString = addressString;
        return this;
    }


    /**
     * The primary delivery point for a premise or building. This could be a house number, a building name,
     * etc.
     */
    public GetJourneyStateDocumentCurrentAddress withPremise(@Nullable String premise) {
        this.premise = premise;
        return this;
    }


    /**
     * The name of a building or a building complex. In the US, this is the street number.
     */
    public GetJourneyStateDocumentCurrentAddress withBuilding(@Nullable String building) {
        this.building = building;
        return this;
    }


    /**
     * The name of a sub-building, such as a flat or apartment number.
     */
    public GetJourneyStateDocumentCurrentAddress withSubBuilding(@Nullable String subBuilding) {
        this.subBuilding = subBuilding;
        return this;
    }


    /**
     * This field holds the most common street or block data element within a country. For instance, USA
     * Street
     */
    public GetJourneyStateDocumentCurrentAddress withThoroughfare(@Nullable String thoroughfare) {
        this.thoroughfare = thoroughfare;
        return this;
    }


    /**
     * The name of a dependent street or block, such as a street within a complex.
     */
    public GetJourneyStateDocumentCurrentAddress withDependentThoroughfare(@Nullable String dependentThoroughfare) {
        this.dependentThoroughfare = dependentThoroughfare;
        return this;
    }


    /**
     * This field holds the most common population center data element within a country. For instance, USA
     * City, Canadian Municipality
     */
    public GetJourneyStateDocumentCurrentAddress withLocality(@Nullable String locality) {
        this.locality = locality;
        return this;
    }


    /**
     * This is a smaller area within a locality, such as a neighborhood or district. Like Manhattan in New
     * York City, or Soho in London.
     */
    public GetJourneyStateDocumentCurrentAddress withDependentLocality(@Nullable String dependentLocality) {
        this.dependentLocality = dependentLocality;
        return this;
    }


    /**
     * This is an even smaller area within a dependent locality, often used in very detailed addresses.
     */
    public GetJourneyStateDocumentCurrentAddress withDoubleDependentLocality(@Nullable String doubleDependentLocality) {
        this.doubleDependentLocality = doubleDependentLocality;
        return this;
    }


    /**
     * This field contains the complete postal code for a particular delivery point, should such detail be
     * able to be determined. For example ZIP code in the US
     */
    public GetJourneyStateDocumentCurrentAddress withPostalCode(@Nullable String postalCode) {
        this.postalCode = postalCode;
        return this;
    }


    /**
     * This field contains the post box number associated with a particular delivery point, should one
     * exist.
     */
    public GetJourneyStateDocumentCurrentAddress withPostBox(@Nullable String postBox) {
        this.postBox = postBox;
        return this;
    }


    /**
     * Country the address is in. It must be a valid ISO2 or ISO3 country code
     */
    public GetJourneyStateDocumentCurrentAddress withCountry(@Nullable String country) {
        this.country = country;
        return this;
    }


    public GetJourneyStateDocumentCurrentAddress withSuperAdministrativeArea(@Nullable String superAdministrativeArea) {
        this.superAdministrativeArea = superAdministrativeArea;
        return this;
    }


    public GetJourneyStateDocumentCurrentAddress withAdministrativeArea(@Nullable String administrativeArea) {
        this.administrativeArea = administrativeArea;
        return this;
    }


    public GetJourneyStateDocumentCurrentAddress withSubAdministrativeArea(@Nullable String subAdministrativeArea) {
        this.subAdministrativeArea = subAdministrativeArea;
        return this;
    }


    public GetJourneyStateDocumentCurrentAddress withOrganization(@Nullable String organization) {
        this.organization = organization;
        return this;
    }


    public GetJourneyStateDocumentCurrentAddress withLocation(@Nullable GetJourneyStateDocumentCurrentAddressLocation location) {
        this.location = location;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetJourneyStateDocumentCurrentAddress other = (GetJourneyStateDocumentCurrentAddress) o;
        return 
            Utils.enhancedDeepEquals(this.lines, other.lines) &&
            Utils.enhancedDeepEquals(this.addressString, other.addressString) &&
            Utils.enhancedDeepEquals(this.premise, other.premise) &&
            Utils.enhancedDeepEquals(this.building, other.building) &&
            Utils.enhancedDeepEquals(this.subBuilding, other.subBuilding) &&
            Utils.enhancedDeepEquals(this.thoroughfare, other.thoroughfare) &&
            Utils.enhancedDeepEquals(this.dependentThoroughfare, other.dependentThoroughfare) &&
            Utils.enhancedDeepEquals(this.locality, other.locality) &&
            Utils.enhancedDeepEquals(this.dependentLocality, other.dependentLocality) &&
            Utils.enhancedDeepEquals(this.doubleDependentLocality, other.doubleDependentLocality) &&
            Utils.enhancedDeepEquals(this.postalCode, other.postalCode) &&
            Utils.enhancedDeepEquals(this.postBox, other.postBox) &&
            Utils.enhancedDeepEquals(this.country, other.country) &&
            Utils.enhancedDeepEquals(this.superAdministrativeArea, other.superAdministrativeArea) &&
            Utils.enhancedDeepEquals(this.administrativeArea, other.administrativeArea) &&
            Utils.enhancedDeepEquals(this.subAdministrativeArea, other.subAdministrativeArea) &&
            Utils.enhancedDeepEquals(this.organization, other.organization) &&
            Utils.enhancedDeepEquals(this.location, other.location);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            lines, addressString, premise,
            building, subBuilding, thoroughfare,
            dependentThoroughfare, locality, dependentLocality,
            doubleDependentLocality, postalCode, postBox,
            country, superAdministrativeArea, administrativeArea,
            subAdministrativeArea, organization, location);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetJourneyStateDocumentCurrentAddress.class,
                "lines", lines,
                "addressString", addressString,
                "premise", premise,
                "building", building,
                "subBuilding", subBuilding,
                "thoroughfare", thoroughfare,
                "dependentThoroughfare", dependentThoroughfare,
                "locality", locality,
                "dependentLocality", dependentLocality,
                "doubleDependentLocality", doubleDependentLocality,
                "postalCode", postalCode,
                "postBox", postBox,
                "country", country,
                "superAdministrativeArea", superAdministrativeArea,
                "administrativeArea", administrativeArea,
                "subAdministrativeArea", subAdministrativeArea,
                "organization", organization,
                "location", location);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private List<String> lines;

        private String addressString;

        private String premise;

        private String building;

        private String subBuilding;

        private String thoroughfare;

        private String dependentThoroughfare;

        private String locality;

        private String dependentLocality;

        private String doubleDependentLocality;

        private String postalCode;

        private String postBox;

        private String country;

        private String superAdministrativeArea;

        private String administrativeArea;

        private String subAdministrativeArea;

        private String organization;

        private GetJourneyStateDocumentCurrentAddressLocation location;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Unformatted line based address
         */
        public Builder lines(@Nullable List<String> lines) {
            this.lines = lines;
            return this;
        }

        /**
         * The address as a single line
         */
        public Builder addressString(@Nullable String addressString) {
            this.addressString = addressString;
            return this;
        }

        /**
         * The primary delivery point for a premise or building. This could be a house number, a building name,
         * etc.
         */
        public Builder premise(@Nullable String premise) {
            this.premise = premise;
            return this;
        }

        /**
         * The name of a building or a building complex. In the US, this is the street number.
         */
        public Builder building(@Nullable String building) {
            this.building = building;
            return this;
        }

        /**
         * The name of a sub-building, such as a flat or apartment number.
         */
        public Builder subBuilding(@Nullable String subBuilding) {
            this.subBuilding = subBuilding;
            return this;
        }

        /**
         * This field holds the most common street or block data element within a country. For instance, USA
         * Street
         */
        public Builder thoroughfare(@Nullable String thoroughfare) {
            this.thoroughfare = thoroughfare;
            return this;
        }

        /**
         * The name of a dependent street or block, such as a street within a complex.
         */
        public Builder dependentThoroughfare(@Nullable String dependentThoroughfare) {
            this.dependentThoroughfare = dependentThoroughfare;
            return this;
        }

        /**
         * This field holds the most common population center data element within a country. For instance, USA
         * City, Canadian Municipality
         */
        public Builder locality(@Nullable String locality) {
            this.locality = locality;
            return this;
        }

        /**
         * This is a smaller area within a locality, such as a neighborhood or district. Like Manhattan in New
         * York City, or Soho in London.
         */
        public Builder dependentLocality(@Nullable String dependentLocality) {
            this.dependentLocality = dependentLocality;
            return this;
        }

        /**
         * This is an even smaller area within a dependent locality, often used in very detailed addresses.
         */
        public Builder doubleDependentLocality(@Nullable String doubleDependentLocality) {
            this.doubleDependentLocality = doubleDependentLocality;
            return this;
        }

        /**
         * This field contains the complete postal code for a particular delivery point, should such detail be
         * able to be determined. For example ZIP code in the US
         */
        public Builder postalCode(@Nullable String postalCode) {
            this.postalCode = postalCode;
            return this;
        }

        /**
         * This field contains the post box number associated with a particular delivery point, should one
         * exist.
         */
        public Builder postBox(@Nullable String postBox) {
            this.postBox = postBox;
            return this;
        }

        /**
         * Country the address is in. It must be a valid ISO2 or ISO3 country code
         */
        public Builder country(@Nullable String country) {
            this.country = country;
            return this;
        }

        public Builder superAdministrativeArea(@Nullable String superAdministrativeArea) {
            this.superAdministrativeArea = superAdministrativeArea;
            return this;
        }

        public Builder administrativeArea(@Nullable String administrativeArea) {
            this.administrativeArea = administrativeArea;
            return this;
        }

        public Builder subAdministrativeArea(@Nullable String subAdministrativeArea) {
            this.subAdministrativeArea = subAdministrativeArea;
            return this;
        }

        public Builder organization(@Nullable String organization) {
            this.organization = organization;
            return this;
        }

        public Builder location(@Nullable GetJourneyStateDocumentCurrentAddressLocation location) {
            this.location = location;
            return this;
        }

        public GetJourneyStateDocumentCurrentAddress build() {
            return new GetJourneyStateDocumentCurrentAddress(
                lines, addressString, premise,
                building, subBuilding, thoroughfare,
                dependentThoroughfare, locality, dependentLocality,
                doubleDependentLocality, postalCode, postBox,
                country, superAdministrativeArea, administrativeArea,
                subAdministrativeArea, organization, location);
        }

    }
}
