/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gbg.gocore.utils.Utils;
import java.lang.Override;
import java.lang.String;


public class GetJourneyStateDetailBoundingBox {

    @JsonProperty("x")
    private double x;


    @JsonProperty("y")
    private double y;


    @JsonProperty("width")
    private double width;


    @JsonProperty("height")
    private double height;

    @JsonCreator
    public GetJourneyStateDetailBoundingBox(
            @JsonProperty("x") double x,
            @JsonProperty("y") double y,
            @JsonProperty("width") double width,
            @JsonProperty("height") double height) {
        this.x = x;
        this.y = y;
        this.width = width;
        this.height = height;
    }

    public double x() {
        return this.x;
    }

    public double y() {
        return this.y;
    }

    public double width() {
        return this.width;
    }

    public double height() {
        return this.height;
    }

    public static Builder builder() {
        return new Builder();
    }


    public GetJourneyStateDetailBoundingBox withX(double x) {
        this.x = x;
        return this;
    }


    public GetJourneyStateDetailBoundingBox withY(double y) {
        this.y = y;
        return this;
    }


    public GetJourneyStateDetailBoundingBox withWidth(double width) {
        this.width = width;
        return this;
    }


    public GetJourneyStateDetailBoundingBox withHeight(double height) {
        this.height = height;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetJourneyStateDetailBoundingBox other = (GetJourneyStateDetailBoundingBox) o;
        return 
            Utils.enhancedDeepEquals(this.x, other.x) &&
            Utils.enhancedDeepEquals(this.y, other.y) &&
            Utils.enhancedDeepEquals(this.width, other.width) &&
            Utils.enhancedDeepEquals(this.height, other.height);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            x, y, width,
            height);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetJourneyStateDetailBoundingBox.class,
                "x", x,
                "y", y,
                "width", width,
                "height", height);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private double x;

        private double y;

        private double width;

        private double height;

        private Builder() {
          // force use of static builder() method
        }

        public Builder x(double x) {
            this.x = x;
            return this;
        }

        public Builder y(double y) {
            this.y = y;
            return this;
        }

        public Builder width(double width) {
            this.width = width;
            return this;
        }

        public Builder height(double height) {
            this.height = height;
            return this;
        }

        public GetJourneyStateDetailBoundingBox build() {
            return new GetJourneyStateDetailBoundingBox(
                x, y, width,
                height);
        }

    }
}
