/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
public class GetJourneyStateIdentityRelationship {

    public static final GetJourneyStateIdentityRelationship MOTHER = new GetJourneyStateIdentityRelationship("mother");
    public static final GetJourneyStateIdentityRelationship FATHER = new GetJourneyStateIdentityRelationship("father");
    public static final GetJourneyStateIdentityRelationship MATERNAL_GRAND_FATHER = new GetJourneyStateIdentityRelationship("maternalGrandFather");
    public static final GetJourneyStateIdentityRelationship MATERNAL_GRAND_MOTHER = new GetJourneyStateIdentityRelationship("maternalGrandMother");
    public static final GetJourneyStateIdentityRelationship PATERNAL_GRAND_FATHER = new GetJourneyStateIdentityRelationship("paternalGrandFather");
    public static final GetJourneyStateIdentityRelationship PATERNAL_GRAND_MOTHER = new GetJourneyStateIdentityRelationship("paternalGrandMother");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, GetJourneyStateIdentityRelationship> values = createValuesMap();
    private static final Map<String, GetJourneyStateIdentityRelationshipEnum> enums = createEnumsMap();

    private final String value;

    private GetJourneyStateIdentityRelationship(String value) {
        this.value = value;
    }

    /**
     * Returns a GetJourneyStateIdentityRelationship with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as GetJourneyStateIdentityRelationship
     */ 
    @JsonCreator
    public static GetJourneyStateIdentityRelationship of(String value) {
        synchronized (GetJourneyStateIdentityRelationship.class) {
            return values.computeIfAbsent(value, v -> new GetJourneyStateIdentityRelationship(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<GetJourneyStateIdentityRelationshipEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        GetJourneyStateIdentityRelationship other = (GetJourneyStateIdentityRelationship) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "GetJourneyStateIdentityRelationship [value=" + value + "]";
    }

    // return an array just like an enum
    public static GetJourneyStateIdentityRelationship[] values() {
        synchronized (GetJourneyStateIdentityRelationship.class) {
            return values.values().toArray(new GetJourneyStateIdentityRelationship[] {});
        }
    }

    private static final Map<String, GetJourneyStateIdentityRelationship> createValuesMap() {
        Map<String, GetJourneyStateIdentityRelationship> map = new LinkedHashMap<>();
        map.put("mother", MOTHER);
        map.put("father", FATHER);
        map.put("maternalGrandFather", MATERNAL_GRAND_FATHER);
        map.put("maternalGrandMother", MATERNAL_GRAND_MOTHER);
        map.put("paternalGrandFather", PATERNAL_GRAND_FATHER);
        map.put("paternalGrandMother", PATERNAL_GRAND_MOTHER);
        return map;
    }

    private static final Map<String, GetJourneyStateIdentityRelationshipEnum> createEnumsMap() {
        Map<String, GetJourneyStateIdentityRelationshipEnum> map = new HashMap<>();
        map.put("mother", GetJourneyStateIdentityRelationshipEnum.MOTHER);
        map.put("father", GetJourneyStateIdentityRelationshipEnum.FATHER);
        map.put("maternalGrandFather", GetJourneyStateIdentityRelationshipEnum.MATERNAL_GRAND_FATHER);
        map.put("maternalGrandMother", GetJourneyStateIdentityRelationshipEnum.MATERNAL_GRAND_MOTHER);
        map.put("paternalGrandFather", GetJourneyStateIdentityRelationshipEnum.PATERNAL_GRAND_FATHER);
        map.put("paternalGrandMother", GetJourneyStateIdentityRelationshipEnum.PATERNAL_GRAND_MOTHER);
        return map;
    }
    
    
    public enum GetJourneyStateIdentityRelationshipEnum {

        MOTHER("mother"),
        FATHER("father"),
        MATERNAL_GRAND_FATHER("maternalGrandFather"),
        MATERNAL_GRAND_MOTHER("maternalGrandMother"),
        PATERNAL_GRAND_FATHER("paternalGrandFather"),
        PATERNAL_GRAND_MOTHER("paternalGrandMother"),;

        private final String value;

        private GetJourneyStateIdentityRelationshipEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

