/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;


public class GetJourneyStateIdentity {
    /**
     * Title of an individual such as Mr, Mrs, Dr, Sir
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("title")
    private String title;

    /**
     * A person's name used by their collegues and friends to address them
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("firstName")
    private String firstName;

    /**
     * Any other registered names used by the individual, not aliases
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("middleNames")
    private List<String> middleNames;

    /**
     * Any family names for the individual
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("lastNames")
    private List<String> lastNames;

    /**
     * Any family names for the individual
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("lastNamesAtBirth")
    private List<String> lastNamesAtBirth;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("aliases")
    private List<GetJourneyStateIdentityAlias> aliases;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("relatedPersons")
    private List<GetJourneyStateIdentityRelatedPerson> relatedPersons;

    /**
     * Specified in year, month and day separated by -. For example 2017-1-1 or 2017-01-01 which conforms
     * to ISO 8601
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("dateOfBirth")
    private String dateOfBirth;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("gender")
    private String gender;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("currentAddress")
    private GetJourneyStateIdentityCurrentAddress currentAddress;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("previousAddresses")
    private List<GetJourneyStateIdentityPreviousAddress> previousAddresses;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("placeOfBirth")
    private GetJourneyStateIdentityPlaceOfBirth placeOfBirth;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("idNumbers")
    private List<GetJourneyStateIdentityIdNumber> idNumbers;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("phones")
    private List<GetJourneyStateIdentityPhone> phones;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("emails")
    private List<GetJourneyStateIdentityEmail> emails;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("socials")
    private List<GetJourneyStateIdentitySocial> socials;

    /**
     * The subject's mother's maiden name, used for identity verification
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("mothersMaidenName")
    private String mothersMaidenName;

    @JsonCreator
    public GetJourneyStateIdentity(
            @JsonProperty("title") @Nullable String title,
            @JsonProperty("firstName") @Nullable String firstName,
            @JsonProperty("middleNames") @Nullable List<String> middleNames,
            @JsonProperty("lastNames") @Nullable List<String> lastNames,
            @JsonProperty("lastNamesAtBirth") @Nullable List<String> lastNamesAtBirth,
            @JsonProperty("aliases") @Nullable List<GetJourneyStateIdentityAlias> aliases,
            @JsonProperty("relatedPersons") @Nullable List<GetJourneyStateIdentityRelatedPerson> relatedPersons,
            @JsonProperty("dateOfBirth") @Nullable String dateOfBirth,
            @JsonProperty("gender") @Nullable String gender,
            @JsonProperty("currentAddress") @Nullable GetJourneyStateIdentityCurrentAddress currentAddress,
            @JsonProperty("previousAddresses") @Nullable List<GetJourneyStateIdentityPreviousAddress> previousAddresses,
            @JsonProperty("placeOfBirth") @Nullable GetJourneyStateIdentityPlaceOfBirth placeOfBirth,
            @JsonProperty("idNumbers") @Nullable List<GetJourneyStateIdentityIdNumber> idNumbers,
            @JsonProperty("phones") @Nullable List<GetJourneyStateIdentityPhone> phones,
            @JsonProperty("emails") @Nullable List<GetJourneyStateIdentityEmail> emails,
            @JsonProperty("socials") @Nullable List<GetJourneyStateIdentitySocial> socials,
            @JsonProperty("mothersMaidenName") @Nullable String mothersMaidenName) {
        this.title = title;
        this.firstName = firstName;
        this.middleNames = middleNames;
        this.lastNames = lastNames;
        this.lastNamesAtBirth = lastNamesAtBirth;
        this.aliases = aliases;
        this.relatedPersons = relatedPersons;
        this.dateOfBirth = dateOfBirth;
        this.gender = gender;
        this.currentAddress = currentAddress;
        this.previousAddresses = previousAddresses;
        this.placeOfBirth = placeOfBirth;
        this.idNumbers = idNumbers;
        this.phones = phones;
        this.emails = emails;
        this.socials = socials;
        this.mothersMaidenName = mothersMaidenName;
    }
    
    public GetJourneyStateIdentity() {
        this(null, null, null,
            null, null, null,
            null, null, null,
            null, null, null,
            null, null, null,
            null, null);
    }

    /**
     * Title of an individual such as Mr, Mrs, Dr, Sir
     */
    public Optional<String> title() {
        return Optional.ofNullable(this.title);
    }

    /**
     * A person's name used by their collegues and friends to address them
     */
    public Optional<String> firstName() {
        return Optional.ofNullable(this.firstName);
    }

    /**
     * Any other registered names used by the individual, not aliases
     */
    public Optional<List<String>> middleNames() {
        return Optional.ofNullable(this.middleNames);
    }

    /**
     * Any family names for the individual
     */
    public Optional<List<String>> lastNames() {
        return Optional.ofNullable(this.lastNames);
    }

    /**
     * Any family names for the individual
     */
    public Optional<List<String>> lastNamesAtBirth() {
        return Optional.ofNullable(this.lastNamesAtBirth);
    }

    public Optional<List<GetJourneyStateIdentityAlias>> aliases() {
        return Optional.ofNullable(this.aliases);
    }

    public Optional<List<GetJourneyStateIdentityRelatedPerson>> relatedPersons() {
        return Optional.ofNullable(this.relatedPersons);
    }

    /**
     * Specified in year, month and day separated by -. For example 2017-1-1 or 2017-01-01 which conforms
     * to ISO 8601
     */
    public Optional<String> dateOfBirth() {
        return Optional.ofNullable(this.dateOfBirth);
    }

    public Optional<String> gender() {
        return Optional.ofNullable(this.gender);
    }

    public Optional<GetJourneyStateIdentityCurrentAddress> currentAddress() {
        return Optional.ofNullable(this.currentAddress);
    }

    public Optional<List<GetJourneyStateIdentityPreviousAddress>> previousAddresses() {
        return Optional.ofNullable(this.previousAddresses);
    }

    public Optional<GetJourneyStateIdentityPlaceOfBirth> placeOfBirth() {
        return Optional.ofNullable(this.placeOfBirth);
    }

    public Optional<List<GetJourneyStateIdentityIdNumber>> idNumbers() {
        return Optional.ofNullable(this.idNumbers);
    }

    public Optional<List<GetJourneyStateIdentityPhone>> phones() {
        return Optional.ofNullable(this.phones);
    }

    public Optional<List<GetJourneyStateIdentityEmail>> emails() {
        return Optional.ofNullable(this.emails);
    }

    public Optional<List<GetJourneyStateIdentitySocial>> socials() {
        return Optional.ofNullable(this.socials);
    }

    /**
     * The subject's mother's maiden name, used for identity verification
     */
    public Optional<String> mothersMaidenName() {
        return Optional.ofNullable(this.mothersMaidenName);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Title of an individual such as Mr, Mrs, Dr, Sir
     */
    public GetJourneyStateIdentity withTitle(@Nullable String title) {
        this.title = title;
        return this;
    }


    /**
     * A person's name used by their collegues and friends to address them
     */
    public GetJourneyStateIdentity withFirstName(@Nullable String firstName) {
        this.firstName = firstName;
        return this;
    }


    /**
     * Any other registered names used by the individual, not aliases
     */
    public GetJourneyStateIdentity withMiddleNames(@Nullable List<String> middleNames) {
        this.middleNames = middleNames;
        return this;
    }


    /**
     * Any family names for the individual
     */
    public GetJourneyStateIdentity withLastNames(@Nullable List<String> lastNames) {
        this.lastNames = lastNames;
        return this;
    }


    /**
     * Any family names for the individual
     */
    public GetJourneyStateIdentity withLastNamesAtBirth(@Nullable List<String> lastNamesAtBirth) {
        this.lastNamesAtBirth = lastNamesAtBirth;
        return this;
    }


    public GetJourneyStateIdentity withAliases(@Nullable List<GetJourneyStateIdentityAlias> aliases) {
        this.aliases = aliases;
        return this;
    }


    public GetJourneyStateIdentity withRelatedPersons(@Nullable List<GetJourneyStateIdentityRelatedPerson> relatedPersons) {
        this.relatedPersons = relatedPersons;
        return this;
    }


    /**
     * Specified in year, month and day separated by -. For example 2017-1-1 or 2017-01-01 which conforms
     * to ISO 8601
     */
    public GetJourneyStateIdentity withDateOfBirth(@Nullable String dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
        return this;
    }


    public GetJourneyStateIdentity withGender(@Nullable String gender) {
        this.gender = gender;
        return this;
    }


    public GetJourneyStateIdentity withCurrentAddress(@Nullable GetJourneyStateIdentityCurrentAddress currentAddress) {
        this.currentAddress = currentAddress;
        return this;
    }


    public GetJourneyStateIdentity withPreviousAddresses(@Nullable List<GetJourneyStateIdentityPreviousAddress> previousAddresses) {
        this.previousAddresses = previousAddresses;
        return this;
    }


    public GetJourneyStateIdentity withPlaceOfBirth(@Nullable GetJourneyStateIdentityPlaceOfBirth placeOfBirth) {
        this.placeOfBirth = placeOfBirth;
        return this;
    }


    public GetJourneyStateIdentity withIdNumbers(@Nullable List<GetJourneyStateIdentityIdNumber> idNumbers) {
        this.idNumbers = idNumbers;
        return this;
    }


    public GetJourneyStateIdentity withPhones(@Nullable List<GetJourneyStateIdentityPhone> phones) {
        this.phones = phones;
        return this;
    }


    public GetJourneyStateIdentity withEmails(@Nullable List<GetJourneyStateIdentityEmail> emails) {
        this.emails = emails;
        return this;
    }


    public GetJourneyStateIdentity withSocials(@Nullable List<GetJourneyStateIdentitySocial> socials) {
        this.socials = socials;
        return this;
    }


    /**
     * The subject's mother's maiden name, used for identity verification
     */
    public GetJourneyStateIdentity withMothersMaidenName(@Nullable String mothersMaidenName) {
        this.mothersMaidenName = mothersMaidenName;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetJourneyStateIdentity other = (GetJourneyStateIdentity) o;
        return 
            Utils.enhancedDeepEquals(this.title, other.title) &&
            Utils.enhancedDeepEquals(this.firstName, other.firstName) &&
            Utils.enhancedDeepEquals(this.middleNames, other.middleNames) &&
            Utils.enhancedDeepEquals(this.lastNames, other.lastNames) &&
            Utils.enhancedDeepEquals(this.lastNamesAtBirth, other.lastNamesAtBirth) &&
            Utils.enhancedDeepEquals(this.aliases, other.aliases) &&
            Utils.enhancedDeepEquals(this.relatedPersons, other.relatedPersons) &&
            Utils.enhancedDeepEquals(this.dateOfBirth, other.dateOfBirth) &&
            Utils.enhancedDeepEquals(this.gender, other.gender) &&
            Utils.enhancedDeepEquals(this.currentAddress, other.currentAddress) &&
            Utils.enhancedDeepEquals(this.previousAddresses, other.previousAddresses) &&
            Utils.enhancedDeepEquals(this.placeOfBirth, other.placeOfBirth) &&
            Utils.enhancedDeepEquals(this.idNumbers, other.idNumbers) &&
            Utils.enhancedDeepEquals(this.phones, other.phones) &&
            Utils.enhancedDeepEquals(this.emails, other.emails) &&
            Utils.enhancedDeepEquals(this.socials, other.socials) &&
            Utils.enhancedDeepEquals(this.mothersMaidenName, other.mothersMaidenName);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            title, firstName, middleNames,
            lastNames, lastNamesAtBirth, aliases,
            relatedPersons, dateOfBirth, gender,
            currentAddress, previousAddresses, placeOfBirth,
            idNumbers, phones, emails,
            socials, mothersMaidenName);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetJourneyStateIdentity.class,
                "title", title,
                "firstName", firstName,
                "middleNames", middleNames,
                "lastNames", lastNames,
                "lastNamesAtBirth", lastNamesAtBirth,
                "aliases", aliases,
                "relatedPersons", relatedPersons,
                "dateOfBirth", dateOfBirth,
                "gender", gender,
                "currentAddress", currentAddress,
                "previousAddresses", previousAddresses,
                "placeOfBirth", placeOfBirth,
                "idNumbers", idNumbers,
                "phones", phones,
                "emails", emails,
                "socials", socials,
                "mothersMaidenName", mothersMaidenName);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String title;

        private String firstName;

        private List<String> middleNames;

        private List<String> lastNames;

        private List<String> lastNamesAtBirth;

        private List<GetJourneyStateIdentityAlias> aliases;

        private List<GetJourneyStateIdentityRelatedPerson> relatedPersons;

        private String dateOfBirth;

        private String gender;

        private GetJourneyStateIdentityCurrentAddress currentAddress;

        private List<GetJourneyStateIdentityPreviousAddress> previousAddresses;

        private GetJourneyStateIdentityPlaceOfBirth placeOfBirth;

        private List<GetJourneyStateIdentityIdNumber> idNumbers;

        private List<GetJourneyStateIdentityPhone> phones;

        private List<GetJourneyStateIdentityEmail> emails;

        private List<GetJourneyStateIdentitySocial> socials;

        private String mothersMaidenName;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Title of an individual such as Mr, Mrs, Dr, Sir
         */
        public Builder title(@Nullable String title) {
            this.title = title;
            return this;
        }

        /**
         * A person's name used by their collegues and friends to address them
         */
        public Builder firstName(@Nullable String firstName) {
            this.firstName = firstName;
            return this;
        }

        /**
         * Any other registered names used by the individual, not aliases
         */
        public Builder middleNames(@Nullable List<String> middleNames) {
            this.middleNames = middleNames;
            return this;
        }

        /**
         * Any family names for the individual
         */
        public Builder lastNames(@Nullable List<String> lastNames) {
            this.lastNames = lastNames;
            return this;
        }

        /**
         * Any family names for the individual
         */
        public Builder lastNamesAtBirth(@Nullable List<String> lastNamesAtBirth) {
            this.lastNamesAtBirth = lastNamesAtBirth;
            return this;
        }

        public Builder aliases(@Nullable List<GetJourneyStateIdentityAlias> aliases) {
            this.aliases = aliases;
            return this;
        }

        public Builder relatedPersons(@Nullable List<GetJourneyStateIdentityRelatedPerson> relatedPersons) {
            this.relatedPersons = relatedPersons;
            return this;
        }

        /**
         * Specified in year, month and day separated by -. For example 2017-1-1 or 2017-01-01 which conforms
         * to ISO 8601
         */
        public Builder dateOfBirth(@Nullable String dateOfBirth) {
            this.dateOfBirth = dateOfBirth;
            return this;
        }

        public Builder gender(@Nullable String gender) {
            this.gender = gender;
            return this;
        }

        public Builder currentAddress(@Nullable GetJourneyStateIdentityCurrentAddress currentAddress) {
            this.currentAddress = currentAddress;
            return this;
        }

        public Builder previousAddresses(@Nullable List<GetJourneyStateIdentityPreviousAddress> previousAddresses) {
            this.previousAddresses = previousAddresses;
            return this;
        }

        public Builder placeOfBirth(@Nullable GetJourneyStateIdentityPlaceOfBirth placeOfBirth) {
            this.placeOfBirth = placeOfBirth;
            return this;
        }

        public Builder idNumbers(@Nullable List<GetJourneyStateIdentityIdNumber> idNumbers) {
            this.idNumbers = idNumbers;
            return this;
        }

        public Builder phones(@Nullable List<GetJourneyStateIdentityPhone> phones) {
            this.phones = phones;
            return this;
        }

        public Builder emails(@Nullable List<GetJourneyStateIdentityEmail> emails) {
            this.emails = emails;
            return this;
        }

        public Builder socials(@Nullable List<GetJourneyStateIdentitySocial> socials) {
            this.socials = socials;
            return this;
        }

        /**
         * The subject's mother's maiden name, used for identity verification
         */
        public Builder mothersMaidenName(@Nullable String mothersMaidenName) {
            this.mothersMaidenName = mothersMaidenName;
            return this;
        }

        public GetJourneyStateIdentity build() {
            return new GetJourneyStateIdentity(
                title, firstName, middleNames,
                lastNames, lastNamesAtBirth, aliases,
                relatedPersons, dateOfBirth, gender,
                currentAddress, previousAddresses, placeOfBirth,
                idNumbers, phones, emails,
                socials, mothersMaidenName);
        }

    }
}
