/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.gbg.gocore.utils.Response;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.io.InputStream;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.net.http.HttpResponse;
import java.util.Map;
import java.util.Optional;


public class GetTaskSchemaResponse implements Response {
    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * Task JSON Schema (or { processing: true } while modules execute)
     */
    private Map<String, Object> taskSchemaResponse;

    @JsonCreator
    public GetTaskSchemaResponse(
            @Nonnull String contentType,
            int statusCode,
            @Nonnull HttpResponse<InputStream> rawResponse,
            @Nullable Map<String, Object> taskSchemaResponse) {
        this.contentType = Optional.ofNullable(contentType)
            .orElseThrow(() -> new IllegalArgumentException("contentType cannot be null"));
        this.statusCode = statusCode;
        this.rawResponse = Optional.ofNullable(rawResponse)
            .orElseThrow(() -> new IllegalArgumentException("rawResponse cannot be null"));
        this.taskSchemaResponse = taskSchemaResponse;
    }
    
    public GetTaskSchemaResponse(
            @Nonnull String contentType,
            int statusCode,
            @Nonnull HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse,
            null);
    }

    /**
     * HTTP response content type for this operation
     */
    public String contentType() {
        return this.contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    public int statusCode() {
        return this.statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public HttpResponse<InputStream> rawResponse() {
        return this.rawResponse;
    }

    /**
     * Task JSON Schema (or { processing: true } while modules execute)
     */
    public Optional<Map<String, Object>> taskSchemaResponse() {
        return Optional.ofNullable(this.taskSchemaResponse);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * HTTP response content type for this operation
     */
    public GetTaskSchemaResponse withContentType(@Nonnull String contentType) {
        this.contentType = Utils.checkNotNull(contentType, "contentType");
        return this;
    }


    /**
     * HTTP response status code for this operation
     */
    public GetTaskSchemaResponse withStatusCode(int statusCode) {
        this.statusCode = statusCode;
        return this;
    }


    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public GetTaskSchemaResponse withRawResponse(@Nonnull HttpResponse<InputStream> rawResponse) {
        this.rawResponse = Utils.checkNotNull(rawResponse, "rawResponse");
        return this;
    }


    /**
     * Task JSON Schema (or { processing: true } while modules execute)
     */
    public GetTaskSchemaResponse withTaskSchemaResponse(@Nullable Map<String, Object> taskSchemaResponse) {
        this.taskSchemaResponse = taskSchemaResponse;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetTaskSchemaResponse other = (GetTaskSchemaResponse) o;
        return 
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse) &&
            Utils.enhancedDeepEquals(this.taskSchemaResponse, other.taskSchemaResponse);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contentType, statusCode, rawResponse,
            taskSchemaResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetTaskSchemaResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "taskSchemaResponse", taskSchemaResponse);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String contentType;

        private int statusCode;

        private HttpResponse<InputStream> rawResponse;

        private Map<String, Object> taskSchemaResponse;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(@Nonnull String contentType) {
            this.contentType = Utils.checkNotNull(contentType, "contentType");
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(@Nonnull HttpResponse<InputStream> rawResponse) {
            this.rawResponse = Utils.checkNotNull(rawResponse, "rawResponse");
            return this;
        }

        /**
         * Task JSON Schema (or { processing: true } while modules execute)
         */
        public Builder taskSchemaResponse(@Nullable Map<String, Object> taskSchemaResponse) {
            this.taskSchemaResponse = taskSchemaResponse;
            return this;
        }

        public GetTaskSchemaResponse build() {
            return new GetTaskSchemaResponse(
                contentType, statusCode, rawResponse,
                taskSchemaResponse);
        }

    }
}
