/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * GetTasksSchemaResponseBody
 * 
 * <p>Success
 */
public class GetTasksSchemaResponseBody {
    /**
     * Journey Instance Id, a unique identifier for a started journey instance.
     */
    @JsonProperty("instanceId")
    private String instanceId;


    @JsonProperty("status")
    private GetTasksSchemaStatus status;


    @JsonProperty("tasks")
    private List<GetTasksSchemaTask> tasks;


    @JsonProperty("schemas")
    private Map<String, Schemas> schemas;

    @JsonCreator
    public GetTasksSchemaResponseBody(
            @JsonProperty("instanceId") @Nonnull String instanceId,
            @JsonProperty("status") @Nonnull GetTasksSchemaStatus status,
            @JsonProperty("tasks") @Nonnull List<GetTasksSchemaTask> tasks,
            @JsonProperty("schemas") @Nonnull Map<String, Schemas> schemas) {
        schemas = Utils.emptyMapIfNull(schemas);
        this.instanceId = Optional.ofNullable(instanceId)
            .orElseThrow(() -> new IllegalArgumentException("instanceId cannot be null"));
        this.status = Optional.ofNullable(status)
            .orElseThrow(() -> new IllegalArgumentException("status cannot be null"));
        this.tasks = Optional.ofNullable(tasks)
            .orElseThrow(() -> new IllegalArgumentException("tasks cannot be null"));
        this.schemas = Optional.ofNullable(schemas)
            .orElseThrow(() -> new IllegalArgumentException("schemas cannot be null"));
    }

    /**
     * Journey Instance Id, a unique identifier for a started journey instance.
     */
    public String instanceId() {
        return this.instanceId;
    }

    public GetTasksSchemaStatus status() {
        return this.status;
    }

    public List<GetTasksSchemaTask> tasks() {
        return this.tasks;
    }

    public Map<String, Schemas> schemas() {
        return this.schemas;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Journey Instance Id, a unique identifier for a started journey instance.
     */
    public GetTasksSchemaResponseBody withInstanceId(@Nonnull String instanceId) {
        this.instanceId = Utils.checkNotNull(instanceId, "instanceId");
        return this;
    }


    public GetTasksSchemaResponseBody withStatus(@Nonnull GetTasksSchemaStatus status) {
        this.status = Utils.checkNotNull(status, "status");
        return this;
    }


    public GetTasksSchemaResponseBody withTasks(@Nonnull List<GetTasksSchemaTask> tasks) {
        this.tasks = Utils.checkNotNull(tasks, "tasks");
        return this;
    }


    public GetTasksSchemaResponseBody withSchemas(@Nonnull Map<String, Schemas> schemas) {
        this.schemas = Utils.checkNotNull(schemas, "schemas");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetTasksSchemaResponseBody other = (GetTasksSchemaResponseBody) o;
        return 
            Utils.enhancedDeepEquals(this.instanceId, other.instanceId) &&
            Utils.enhancedDeepEquals(this.status, other.status) &&
            Utils.enhancedDeepEquals(this.tasks, other.tasks) &&
            Utils.enhancedDeepEquals(this.schemas, other.schemas);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            instanceId, status, tasks,
            schemas);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetTasksSchemaResponseBody.class,
                "instanceId", instanceId,
                "status", status,
                "tasks", tasks,
                "schemas", schemas);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String instanceId;

        private GetTasksSchemaStatus status;

        private List<GetTasksSchemaTask> tasks;

        private Map<String, Schemas> schemas;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Journey Instance Id, a unique identifier for a started journey instance.
         */
        public Builder instanceId(@Nonnull String instanceId) {
            this.instanceId = Utils.checkNotNull(instanceId, "instanceId");
            return this;
        }

        public Builder status(@Nonnull GetTasksSchemaStatus status) {
            this.status = Utils.checkNotNull(status, "status");
            return this;
        }

        public Builder tasks(@Nonnull List<GetTasksSchemaTask> tasks) {
            this.tasks = Utils.checkNotNull(tasks, "tasks");
            return this;
        }

        public Builder schemas(@Nonnull Map<String, Schemas> schemas) {
            this.schemas = Utils.checkNotNull(schemas, "schemas");
            return this;
        }

        public GetTasksSchemaResponseBody build() {
            return new GetTasksSchemaResponseBody(
                instanceId, status, tasks,
                schemas);
        }

    }
}
