/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
public class GetTasksStatus {

    public static final GetTasksStatus COMPLETED = new GetTasksStatus("Completed");
    public static final GetTasksStatus IN_PROGRESS = new GetTasksStatus("InProgress");
    public static final GetTasksStatus FAILED = new GetTasksStatus("Failed");
    public static final GetTasksStatus PAUSED = new GetTasksStatus("Paused");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, GetTasksStatus> values = createValuesMap();
    private static final Map<String, GetTasksStatusEnum> enums = createEnumsMap();

    private final String value;

    private GetTasksStatus(String value) {
        this.value = value;
    }

    /**
     * Returns a GetTasksStatus with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as GetTasksStatus
     */ 
    @JsonCreator
    public static GetTasksStatus of(String value) {
        synchronized (GetTasksStatus.class) {
            return values.computeIfAbsent(value, v -> new GetTasksStatus(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<GetTasksStatusEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        GetTasksStatus other = (GetTasksStatus) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "GetTasksStatus [value=" + value + "]";
    }

    // return an array just like an enum
    public static GetTasksStatus[] values() {
        synchronized (GetTasksStatus.class) {
            return values.values().toArray(new GetTasksStatus[] {});
        }
    }

    private static final Map<String, GetTasksStatus> createValuesMap() {
        Map<String, GetTasksStatus> map = new LinkedHashMap<>();
        map.put("Completed", COMPLETED);
        map.put("InProgress", IN_PROGRESS);
        map.put("Failed", FAILED);
        map.put("Paused", PAUSED);
        return map;
    }

    private static final Map<String, GetTasksStatusEnum> createEnumsMap() {
        Map<String, GetTasksStatusEnum> map = new HashMap<>();
        map.put("Completed", GetTasksStatusEnum.COMPLETED);
        map.put("InProgress", GetTasksStatusEnum.IN_PROGRESS);
        map.put("Failed", GetTasksStatusEnum.FAILED);
        map.put("Paused", GetTasksStatusEnum.PAUSED);
        return map;
    }
    
    
    public enum GetTasksStatusEnum {

        COMPLETED("Completed"),
        IN_PROGRESS("InProgress"),
        FAILED("Failed"),
        PAUSED("Paused"),;

        private final String value;

        private GetTasksStatusEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

