/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * ManualReview
 * 
 * <p>Reviewer-supplied manual-review input: a required decision ordinal plus optional notes. Identity
 * fields are Captain-populated and rejected here.
 */
public class ManualReview {
    /**
     * Ordinal decision outcome (0-9) submitted by the reviewer
     */
    @JsonProperty("decision")
    private long decision;

    /**
     * Free-text justification or notes provided by the reviewer
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("notes")
    private String notes;

    @JsonCreator
    public ManualReview(
            @JsonProperty("decision") long decision,
            @JsonProperty("notes") @Nullable String notes) {
        this.decision = decision;
        this.notes = notes;
    }
    
    public ManualReview(
            long decision) {
        this(decision, null);
    }

    /**
     * Ordinal decision outcome (0-9) submitted by the reviewer
     */
    public long decision() {
        return this.decision;
    }

    /**
     * Free-text justification or notes provided by the reviewer
     */
    public Optional<String> notes() {
        return Optional.ofNullable(this.notes);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Ordinal decision outcome (0-9) submitted by the reviewer
     */
    public ManualReview withDecision(long decision) {
        this.decision = decision;
        return this;
    }


    /**
     * Free-text justification or notes provided by the reviewer
     */
    public ManualReview withNotes(@Nullable String notes) {
        this.notes = notes;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ManualReview other = (ManualReview) o;
        return 
            Utils.enhancedDeepEquals(this.decision, other.decision) &&
            Utils.enhancedDeepEquals(this.notes, other.notes);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            decision, notes);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ManualReview.class,
                "decision", decision,
                "notes", notes);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private long decision;

        private String notes;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Ordinal decision outcome (0-9) submitted by the reviewer
         */
        public Builder decision(long decision) {
            this.decision = decision;
            return this;
        }

        /**
         * Free-text justification or notes provided by the reviewer
         */
        public Builder notes(@Nullable String notes) {
            this.notes = notes;
            return this;
        }

        public ManualReview build() {
            return new ManualReview(
                decision, notes);
        }

    }
}
