/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * PostAsTokenOauth2ResponseBody
 * 
 * <p>Successfully retrieved access token.
 */
public class PostAsTokenOauth2ResponseBody {
    /**
     * The access token used for authentication.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("access_token")
    private String accessToken;

    /**
     * Token expiration time in seconds.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("expires_in")
    private Long expiresIn;

    /**
     * The type of token, usually 'Bearer'.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("token_type")
    private String tokenType;

    @JsonCreator
    public PostAsTokenOauth2ResponseBody(
            @JsonProperty("access_token") @Nullable String accessToken,
            @JsonProperty("expires_in") @Nullable Long expiresIn,
            @JsonProperty("token_type") @Nullable String tokenType) {
        this.accessToken = accessToken;
        this.expiresIn = expiresIn;
        this.tokenType = tokenType;
    }
    
    public PostAsTokenOauth2ResponseBody() {
        this(null, null, null);
    }

    /**
     * The access token used for authentication.
     */
    public Optional<String> accessToken() {
        return Optional.ofNullable(this.accessToken);
    }

    /**
     * Token expiration time in seconds.
     */
    public Optional<Long> expiresIn() {
        return Optional.ofNullable(this.expiresIn);
    }

    /**
     * The type of token, usually 'Bearer'.
     */
    public Optional<String> tokenType() {
        return Optional.ofNullable(this.tokenType);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The access token used for authentication.
     */
    public PostAsTokenOauth2ResponseBody withAccessToken(@Nullable String accessToken) {
        this.accessToken = accessToken;
        return this;
    }


    /**
     * Token expiration time in seconds.
     */
    public PostAsTokenOauth2ResponseBody withExpiresIn(@Nullable Long expiresIn) {
        this.expiresIn = expiresIn;
        return this;
    }


    /**
     * The type of token, usually 'Bearer'.
     */
    public PostAsTokenOauth2ResponseBody withTokenType(@Nullable String tokenType) {
        this.tokenType = tokenType;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PostAsTokenOauth2ResponseBody other = (PostAsTokenOauth2ResponseBody) o;
        return 
            Utils.enhancedDeepEquals(this.accessToken, other.accessToken) &&
            Utils.enhancedDeepEquals(this.expiresIn, other.expiresIn) &&
            Utils.enhancedDeepEquals(this.tokenType, other.tokenType);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            accessToken, expiresIn, tokenType);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PostAsTokenOauth2ResponseBody.class,
                "accessToken", accessToken,
                "expiresIn", expiresIn,
                "tokenType", tokenType);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String accessToken;

        private Long expiresIn;

        private String tokenType;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The access token used for authentication.
         */
        public Builder accessToken(@Nullable String accessToken) {
            this.accessToken = accessToken;
            return this;
        }

        /**
         * Token expiration time in seconds.
         */
        public Builder expiresIn(@Nullable Long expiresIn) {
            this.expiresIn = expiresIn;
            return this;
        }

        /**
         * The type of token, usually 'Bearer'.
         */
        public Builder tokenType(@Nullable String tokenType) {
            this.tokenType = tokenType;
            return this;
        }

        public PostAsTokenOauth2ResponseBody build() {
            return new PostAsTokenOauth2ResponseBody(
                accessToken, expiresIn, tokenType);
        }

    }
}
