/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class Resource {

    @JsonProperty("id")
    private String id;


    @JsonProperty("name")
    private String name;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("hash")
    private String hash;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("version")
    private String version;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("type")
    private ResourceType type;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    private Data data;

    @JsonCreator
    public Resource(
            @JsonProperty("id") @Nonnull String id,
            @JsonProperty("name") @Nonnull String name,
            @JsonProperty("hash") @Nullable String hash,
            @JsonProperty("version") @Nullable String version,
            @JsonProperty("type") @Nullable ResourceType type,
            @JsonProperty("data") @Nullable Data data) {
        this.id = Optional.ofNullable(id)
            .orElseThrow(() -> new IllegalArgumentException("id cannot be null"));
        this.name = Optional.ofNullable(name)
            .orElseThrow(() -> new IllegalArgumentException("name cannot be null"));
        this.hash = hash;
        this.version = version;
        this.type = type;
        this.data = data;
    }
    
    public Resource(
            @Nonnull String id,
            @Nonnull String name) {
        this(id, name, null,
            null, null, null);
    }

    public String id() {
        return this.id;
    }

    public String name() {
        return this.name;
    }

    public Optional<String> hash() {
        return Optional.ofNullable(this.hash);
    }

    public Optional<String> version() {
        return Optional.ofNullable(this.version);
    }

    public Optional<ResourceType> type() {
        return Optional.ofNullable(this.type);
    }

    public Optional<Data> data() {
        return Optional.ofNullable(this.data);
    }

    public static Builder builder() {
        return new Builder();
    }


    public Resource withId(@Nonnull String id) {
        this.id = Utils.checkNotNull(id, "id");
        return this;
    }


    public Resource withName(@Nonnull String name) {
        this.name = Utils.checkNotNull(name, "name");
        return this;
    }


    public Resource withHash(@Nullable String hash) {
        this.hash = hash;
        return this;
    }


    public Resource withVersion(@Nullable String version) {
        this.version = version;
        return this;
    }


    public Resource withType(@Nullable ResourceType type) {
        this.type = type;
        return this;
    }


    public Resource withData(@Nullable Data data) {
        this.data = data;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Resource other = (Resource) o;
        return 
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.hash, other.hash) &&
            Utils.enhancedDeepEquals(this.version, other.version) &&
            Utils.enhancedDeepEquals(this.type, other.type) &&
            Utils.enhancedDeepEquals(this.data, other.data);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            id, name, hash,
            version, type, data);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Resource.class,
                "id", id,
                "name", name,
                "hash", hash,
                "version", version,
                "type", type,
                "data", data);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String id;

        private String name;

        private String hash;

        private String version;

        private ResourceType type;

        private Data data;

        private Builder() {
          // force use of static builder() method
        }

        public Builder id(@Nonnull String id) {
            this.id = Utils.checkNotNull(id, "id");
            return this;
        }

        public Builder name(@Nonnull String name) {
            this.name = Utils.checkNotNull(name, "name");
            return this;
        }

        public Builder hash(@Nullable String hash) {
            this.hash = hash;
            return this;
        }

        public Builder version(@Nullable String version) {
            this.version = version;
            return this;
        }

        public Builder type(@Nullable ResourceType type) {
            this.type = type;
            return this;
        }

        public Builder data(@Nullable Data data) {
            this.data = data;
            return this;
        }

        public Resource build() {
            return new Resource(
                id, name, hash,
                version, type, data);
        }

    }
}
