/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class RetrieveAddressRequest {
    /**
     * Journey Instance Id, a unique identifier for a started journey instance.
     */
    @JsonProperty("instanceId")
    private String instanceId;


    @JsonProperty("addressId")
    private String addressId;

    @JsonCreator
    public RetrieveAddressRequest(
            @JsonProperty("instanceId") @Nonnull String instanceId,
            @JsonProperty("addressId") @Nonnull String addressId) {
        this.instanceId = Optional.ofNullable(instanceId)
            .orElseThrow(() -> new IllegalArgumentException("instanceId cannot be null"));
        this.addressId = Optional.ofNullable(addressId)
            .orElseThrow(() -> new IllegalArgumentException("addressId cannot be null"));
    }

    /**
     * Journey Instance Id, a unique identifier for a started journey instance.
     */
    public String instanceId() {
        return this.instanceId;
    }

    public String addressId() {
        return this.addressId;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Journey Instance Id, a unique identifier for a started journey instance.
     */
    public RetrieveAddressRequest withInstanceId(@Nonnull String instanceId) {
        this.instanceId = Utils.checkNotNull(instanceId, "instanceId");
        return this;
    }


    public RetrieveAddressRequest withAddressId(@Nonnull String addressId) {
        this.addressId = Utils.checkNotNull(addressId, "addressId");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RetrieveAddressRequest other = (RetrieveAddressRequest) o;
        return 
            Utils.enhancedDeepEquals(this.instanceId, other.instanceId) &&
            Utils.enhancedDeepEquals(this.addressId, other.addressId);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            instanceId, addressId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(RetrieveAddressRequest.class,
                "instanceId", instanceId,
                "addressId", addressId);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String instanceId;

        private String addressId;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Journey Instance Id, a unique identifier for a started journey instance.
         */
        public Builder instanceId(@Nonnull String instanceId) {
            this.instanceId = Utils.checkNotNull(instanceId, "instanceId");
            return this;
        }

        public Builder addressId(@Nonnull String addressId) {
            this.addressId = Utils.checkNotNull(addressId, "addressId");
            return this;
        }

        public RetrieveAddressRequest build() {
            return new RetrieveAddressRequest(
                instanceId, addressId);
        }

    }
}
