/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;


public class StartJourneyExtraction {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("aggregatedFields")
    private List<StartJourneyAggregatedField> aggregatedFields;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("extractedFields")
    private List<StartJourneyExtractedField> extractedFields;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("extractedImages")
    private List<StartJourneyExtractedImage> extractedImages;

    @JsonCreator
    public StartJourneyExtraction(
            @JsonProperty("aggregatedFields") @Nullable List<StartJourneyAggregatedField> aggregatedFields,
            @JsonProperty("extractedFields") @Nullable List<StartJourneyExtractedField> extractedFields,
            @JsonProperty("extractedImages") @Nullable List<StartJourneyExtractedImage> extractedImages) {
        this.aggregatedFields = aggregatedFields;
        this.extractedFields = extractedFields;
        this.extractedImages = extractedImages;
    }
    
    public StartJourneyExtraction() {
        this(null, null, null);
    }

    public Optional<List<StartJourneyAggregatedField>> aggregatedFields() {
        return Optional.ofNullable(this.aggregatedFields);
    }

    public Optional<List<StartJourneyExtractedField>> extractedFields() {
        return Optional.ofNullable(this.extractedFields);
    }

    public Optional<List<StartJourneyExtractedImage>> extractedImages() {
        return Optional.ofNullable(this.extractedImages);
    }

    public static Builder builder() {
        return new Builder();
    }


    public StartJourneyExtraction withAggregatedFields(@Nullable List<StartJourneyAggregatedField> aggregatedFields) {
        this.aggregatedFields = aggregatedFields;
        return this;
    }


    public StartJourneyExtraction withExtractedFields(@Nullable List<StartJourneyExtractedField> extractedFields) {
        this.extractedFields = extractedFields;
        return this;
    }


    public StartJourneyExtraction withExtractedImages(@Nullable List<StartJourneyExtractedImage> extractedImages) {
        this.extractedImages = extractedImages;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        StartJourneyExtraction other = (StartJourneyExtraction) o;
        return 
            Utils.enhancedDeepEquals(this.aggregatedFields, other.aggregatedFields) &&
            Utils.enhancedDeepEquals(this.extractedFields, other.extractedFields) &&
            Utils.enhancedDeepEquals(this.extractedImages, other.extractedImages);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            aggregatedFields, extractedFields, extractedImages);
    }
    
    @Override
    public String toString() {
        return Utils.toString(StartJourneyExtraction.class,
                "aggregatedFields", aggregatedFields,
                "extractedFields", extractedFields,
                "extractedImages", extractedImages);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private List<StartJourneyAggregatedField> aggregatedFields;

        private List<StartJourneyExtractedField> extractedFields;

        private List<StartJourneyExtractedImage> extractedImages;

        private Builder() {
          // force use of static builder() method
        }

        public Builder aggregatedFields(@Nullable List<StartJourneyAggregatedField> aggregatedFields) {
            this.aggregatedFields = aggregatedFields;
            return this;
        }

        public Builder extractedFields(@Nullable List<StartJourneyExtractedField> extractedFields) {
            this.extractedFields = extractedFields;
            return this;
        }

        public Builder extractedImages(@Nullable List<StartJourneyExtractedImage> extractedImages) {
            this.extractedImages = extractedImages;
            return this;
        }

        public StartJourneyExtraction build() {
            return new StartJourneyExtraction(
                aggregatedFields, extractedFields, extractedImages);
        }

    }
}
