/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;


public class StartJourneySubject {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("identity")
    private StartJourneyIdentity identity;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("entities")
    private List<StartJourneyEntity> entities;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("documents")
    private List<StartJourneyDocument> documents;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("biometrics")
    private List<StartJourneyBiometricUnion> biometrics;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("sessions")
    private List<StartJourneySession> sessions;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("consent")
    private List<StartJourneyConsent> consent;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("accounts")
    private List<StartJourneyAccount> accounts;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("kba")
    private StartJourneyKba kba;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("uid")
    private String uid;

    @JsonCreator
    public StartJourneySubject(
            @JsonProperty("identity") @Nullable StartJourneyIdentity identity,
            @JsonProperty("entities") @Nullable List<StartJourneyEntity> entities,
            @JsonProperty("documents") @Nullable List<StartJourneyDocument> documents,
            @JsonProperty("biometrics") @Nullable List<StartJourneyBiometricUnion> biometrics,
            @JsonProperty("sessions") @Nullable List<StartJourneySession> sessions,
            @JsonProperty("consent") @Nullable List<StartJourneyConsent> consent,
            @JsonProperty("accounts") @Nullable List<StartJourneyAccount> accounts,
            @JsonProperty("kba") @Nullable StartJourneyKba kba,
            @JsonProperty("uid") @Nullable String uid) {
        this.identity = identity;
        this.entities = entities;
        this.documents = documents;
        this.biometrics = biometrics;
        this.sessions = sessions;
        this.consent = consent;
        this.accounts = accounts;
        this.kba = kba;
        this.uid = uid;
    }
    
    public StartJourneySubject() {
        this(null, null, null,
            null, null, null,
            null, null, null);
    }

    public Optional<StartJourneyIdentity> identity() {
        return Optional.ofNullable(this.identity);
    }

    public Optional<List<StartJourneyEntity>> entities() {
        return Optional.ofNullable(this.entities);
    }

    public Optional<List<StartJourneyDocument>> documents() {
        return Optional.ofNullable(this.documents);
    }

    public Optional<List<StartJourneyBiometricUnion>> biometrics() {
        return Optional.ofNullable(this.biometrics);
    }

    public Optional<List<StartJourneySession>> sessions() {
        return Optional.ofNullable(this.sessions);
    }

    public Optional<List<StartJourneyConsent>> consent() {
        return Optional.ofNullable(this.consent);
    }

    public Optional<List<StartJourneyAccount>> accounts() {
        return Optional.ofNullable(this.accounts);
    }

    public Optional<StartJourneyKba> kba() {
        return Optional.ofNullable(this.kba);
    }

    public Optional<String> uid() {
        return Optional.ofNullable(this.uid);
    }

    public static Builder builder() {
        return new Builder();
    }


    public StartJourneySubject withIdentity(@Nullable StartJourneyIdentity identity) {
        this.identity = identity;
        return this;
    }


    public StartJourneySubject withEntities(@Nullable List<StartJourneyEntity> entities) {
        this.entities = entities;
        return this;
    }


    public StartJourneySubject withDocuments(@Nullable List<StartJourneyDocument> documents) {
        this.documents = documents;
        return this;
    }


    public StartJourneySubject withBiometrics(@Nullable List<StartJourneyBiometricUnion> biometrics) {
        this.biometrics = biometrics;
        return this;
    }


    public StartJourneySubject withSessions(@Nullable List<StartJourneySession> sessions) {
        this.sessions = sessions;
        return this;
    }


    public StartJourneySubject withConsent(@Nullable List<StartJourneyConsent> consent) {
        this.consent = consent;
        return this;
    }


    public StartJourneySubject withAccounts(@Nullable List<StartJourneyAccount> accounts) {
        this.accounts = accounts;
        return this;
    }


    public StartJourneySubject withKba(@Nullable StartJourneyKba kba) {
        this.kba = kba;
        return this;
    }


    public StartJourneySubject withUid(@Nullable String uid) {
        this.uid = uid;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        StartJourneySubject other = (StartJourneySubject) o;
        return 
            Utils.enhancedDeepEquals(this.identity, other.identity) &&
            Utils.enhancedDeepEquals(this.entities, other.entities) &&
            Utils.enhancedDeepEquals(this.documents, other.documents) &&
            Utils.enhancedDeepEquals(this.biometrics, other.biometrics) &&
            Utils.enhancedDeepEquals(this.sessions, other.sessions) &&
            Utils.enhancedDeepEquals(this.consent, other.consent) &&
            Utils.enhancedDeepEquals(this.accounts, other.accounts) &&
            Utils.enhancedDeepEquals(this.kba, other.kba) &&
            Utils.enhancedDeepEquals(this.uid, other.uid);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            identity, entities, documents,
            biometrics, sessions, consent,
            accounts, kba, uid);
    }
    
    @Override
    public String toString() {
        return Utils.toString(StartJourneySubject.class,
                "identity", identity,
                "entities", entities,
                "documents", documents,
                "biometrics", biometrics,
                "sessions", sessions,
                "consent", consent,
                "accounts", accounts,
                "kba", kba,
                "uid", uid);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private StartJourneyIdentity identity;

        private List<StartJourneyEntity> entities;

        private List<StartJourneyDocument> documents;

        private List<StartJourneyBiometricUnion> biometrics;

        private List<StartJourneySession> sessions;

        private List<StartJourneyConsent> consent;

        private List<StartJourneyAccount> accounts;

        private StartJourneyKba kba;

        private String uid;

        private Builder() {
          // force use of static builder() method
        }

        public Builder identity(@Nullable StartJourneyIdentity identity) {
            this.identity = identity;
            return this;
        }

        public Builder entities(@Nullable List<StartJourneyEntity> entities) {
            this.entities = entities;
            return this;
        }

        public Builder documents(@Nullable List<StartJourneyDocument> documents) {
            this.documents = documents;
            return this;
        }

        public Builder biometrics(@Nullable List<StartJourneyBiometricUnion> biometrics) {
            this.biometrics = biometrics;
            return this;
        }

        public Builder sessions(@Nullable List<StartJourneySession> sessions) {
            this.sessions = sessions;
            return this;
        }

        public Builder consent(@Nullable List<StartJourneyConsent> consent) {
            this.consent = consent;
            return this;
        }

        public Builder accounts(@Nullable List<StartJourneyAccount> accounts) {
            this.accounts = accounts;
            return this;
        }

        public Builder kba(@Nullable StartJourneyKba kba) {
            this.kba = kba;
            return this;
        }

        public Builder uid(@Nullable String uid) {
            this.uid = uid;
            return this;
        }

        public StartJourneySubject build() {
            return new StartJourneySubject(
                identity, entities, documents,
                biometrics, sessions, consent,
                accounts, kba, uid);
        }

    }
}
