/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class StartJourneyIdentityCurrentAddressLocation {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("latitude")
    private String latitude;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("longitude")
    private String longitude;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("geoAccuracy")
    private String geoAccuracy;

    /**
     * A What3words designation associated with this location with '.' separator.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("what3words")
    private String what3words;

    @JsonCreator
    public StartJourneyIdentityCurrentAddressLocation(
            @JsonProperty("latitude") @Nullable String latitude,
            @JsonProperty("longitude") @Nullable String longitude,
            @JsonProperty("geoAccuracy") @Nullable String geoAccuracy,
            @JsonProperty("what3words") @Nullable String what3words) {
        this.latitude = latitude;
        this.longitude = longitude;
        this.geoAccuracy = geoAccuracy;
        this.what3words = what3words;
    }
    
    public StartJourneyIdentityCurrentAddressLocation() {
        this(null, null, null,
            null);
    }

    public Optional<String> latitude() {
        return Optional.ofNullable(this.latitude);
    }

    public Optional<String> longitude() {
        return Optional.ofNullable(this.longitude);
    }

    public Optional<String> geoAccuracy() {
        return Optional.ofNullable(this.geoAccuracy);
    }

    /**
     * A What3words designation associated with this location with '.' separator.
     */
    public Optional<String> what3words() {
        return Optional.ofNullable(this.what3words);
    }

    public static Builder builder() {
        return new Builder();
    }


    public StartJourneyIdentityCurrentAddressLocation withLatitude(@Nullable String latitude) {
        this.latitude = latitude;
        return this;
    }


    public StartJourneyIdentityCurrentAddressLocation withLongitude(@Nullable String longitude) {
        this.longitude = longitude;
        return this;
    }


    public StartJourneyIdentityCurrentAddressLocation withGeoAccuracy(@Nullable String geoAccuracy) {
        this.geoAccuracy = geoAccuracy;
        return this;
    }


    /**
     * A What3words designation associated with this location with '.' separator.
     */
    public StartJourneyIdentityCurrentAddressLocation withWhat3words(@Nullable String what3words) {
        this.what3words = what3words;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        StartJourneyIdentityCurrentAddressLocation other = (StartJourneyIdentityCurrentAddressLocation) o;
        return 
            Utils.enhancedDeepEquals(this.latitude, other.latitude) &&
            Utils.enhancedDeepEquals(this.longitude, other.longitude) &&
            Utils.enhancedDeepEquals(this.geoAccuracy, other.geoAccuracy) &&
            Utils.enhancedDeepEquals(this.what3words, other.what3words);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            latitude, longitude, geoAccuracy,
            what3words);
    }
    
    @Override
    public String toString() {
        return Utils.toString(StartJourneyIdentityCurrentAddressLocation.class,
                "latitude", latitude,
                "longitude", longitude,
                "geoAccuracy", geoAccuracy,
                "what3words", what3words);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String latitude;

        private String longitude;

        private String geoAccuracy;

        private String what3words;

        private Builder() {
          // force use of static builder() method
        }

        public Builder latitude(@Nullable String latitude) {
            this.latitude = latitude;
            return this;
        }

        public Builder longitude(@Nullable String longitude) {
            this.longitude = longitude;
            return this;
        }

        public Builder geoAccuracy(@Nullable String geoAccuracy) {
            this.geoAccuracy = geoAccuracy;
            return this;
        }

        /**
         * A What3words designation associated with this location with '.' separator.
         */
        public Builder what3words(@Nullable String what3words) {
            this.what3words = what3words;
            return this;
        }

        public StartJourneyIdentityCurrentAddressLocation build() {
            return new StartJourneyIdentityCurrentAddressLocation(
                latitude, longitude, geoAccuracy,
                what3words);
        }

    }
}
