/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;


public class StartJourneyAnswer {

    @JsonProperty("id")
    private long id;


    @JsonProperty("choices")
    private List<String> choices;

    @JsonCreator
    public StartJourneyAnswer(
            @JsonProperty("id") long id,
            @JsonProperty("choices") @Nonnull List<String> choices) {
        this.id = id;
        this.choices = Optional.ofNullable(choices)
            .orElseThrow(() -> new IllegalArgumentException("choices cannot be null"));
    }

    public long id() {
        return this.id;
    }

    public List<String> choices() {
        return this.choices;
    }

    public static Builder builder() {
        return new Builder();
    }


    public StartJourneyAnswer withId(long id) {
        this.id = id;
        return this;
    }


    public StartJourneyAnswer withChoices(@Nonnull List<String> choices) {
        this.choices = Utils.checkNotNull(choices, "choices");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        StartJourneyAnswer other = (StartJourneyAnswer) o;
        return 
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.choices, other.choices);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            id, choices);
    }
    
    @Override
    public String toString() {
        return Utils.toString(StartJourneyAnswer.class,
                "id", id,
                "choices", choices);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private long id;

        private List<String> choices;

        private Builder() {
          // force use of static builder() method
        }

        public Builder id(long id) {
            this.id = id;
            return this;
        }

        public Builder choices(@Nonnull List<String> choices) {
            this.choices = Utils.checkNotNull(choices, "choices");
            return this;
        }

        public StartJourneyAnswer build() {
            return new StartJourneyAnswer(
                id, choices);
        }

    }
}
