/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class StartJourneyBiometric2 {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    private String id;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("type")
    private String type;


    @JsonProperty("selfieImage")
    private String selfieImage;


    @JsonProperty("anchorImage")
    private String anchorImage;

    @JsonCreator
    public StartJourneyBiometric2(
            @JsonProperty("id") @Nullable String id,
            @JsonProperty("type") @Nullable String type,
            @JsonProperty("selfieImage") @Nonnull String selfieImage,
            @JsonProperty("anchorImage") @Nonnull String anchorImage) {
        this.id = id;
        this.type = type;
        this.selfieImage = Optional.ofNullable(selfieImage)
            .orElseThrow(() -> new IllegalArgumentException("selfieImage cannot be null"));
        this.anchorImage = Optional.ofNullable(anchorImage)
            .orElseThrow(() -> new IllegalArgumentException("anchorImage cannot be null"));
    }
    
    public StartJourneyBiometric2(
            @Nonnull String selfieImage,
            @Nonnull String anchorImage) {
        this(null, null, selfieImage,
            anchorImage);
    }

    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }

    public Optional<String> type() {
        return Optional.ofNullable(this.type);
    }

    public String selfieImage() {
        return this.selfieImage;
    }

    public String anchorImage() {
        return this.anchorImage;
    }

    public static Builder builder() {
        return new Builder();
    }


    public StartJourneyBiometric2 withId(@Nullable String id) {
        this.id = id;
        return this;
    }


    public StartJourneyBiometric2 withType(@Nullable String type) {
        this.type = type;
        return this;
    }


    public StartJourneyBiometric2 withSelfieImage(@Nonnull String selfieImage) {
        this.selfieImage = Utils.checkNotNull(selfieImage, "selfieImage");
        return this;
    }


    public StartJourneyBiometric2 withAnchorImage(@Nonnull String anchorImage) {
        this.anchorImage = Utils.checkNotNull(anchorImage, "anchorImage");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        StartJourneyBiometric2 other = (StartJourneyBiometric2) o;
        return 
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.type, other.type) &&
            Utils.enhancedDeepEquals(this.selfieImage, other.selfieImage) &&
            Utils.enhancedDeepEquals(this.anchorImage, other.anchorImage);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            id, type, selfieImage,
            anchorImage);
    }
    
    @Override
    public String toString() {
        return Utils.toString(StartJourneyBiometric2.class,
                "id", id,
                "type", type,
                "selfieImage", selfieImage,
                "anchorImage", anchorImage);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String id;

        private String type;

        private String selfieImage;

        private String anchorImage;

        private Builder() {
          // force use of static builder() method
        }

        public Builder id(@Nullable String id) {
            this.id = id;
            return this;
        }

        public Builder type(@Nullable String type) {
            this.type = type;
            return this;
        }

        public Builder selfieImage(@Nonnull String selfieImage) {
            this.selfieImage = Utils.checkNotNull(selfieImage, "selfieImage");
            return this;
        }

        public Builder anchorImage(@Nonnull String anchorImage) {
            this.anchorImage = Utils.checkNotNull(anchorImage, "anchorImage");
            return this;
        }

        public StartJourneyBiometric2 build() {
            return new StartJourneyBiometric2(
                id, type, selfieImage,
                anchorImage);
        }

    }
}
