/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum SubmitInteractionConsentType {
    ROLLUP("rollup"),
    EXPLICIT("explicit"),
    IMPLICIT("implicit");

    @JsonValue
    private final String value;

    SubmitInteractionConsentType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<SubmitInteractionConsentType> fromValue(String value) {
        for (SubmitInteractionConsentType o: SubmitInteractionConsentType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

