/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;


public class SubmitInteractionQuestion {

    @JsonProperty("id")
    private long id;


    @JsonProperty("questionText")
    private String questionText;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("helpText")
    private String helpText;


    @JsonProperty("choices")
    private List<SubmitInteractionChoice> choices;

    @JsonCreator
    public SubmitInteractionQuestion(
            @JsonProperty("id") long id,
            @JsonProperty("questionText") @Nonnull String questionText,
            @JsonProperty("helpText") @Nullable String helpText,
            @JsonProperty("choices") @Nonnull List<SubmitInteractionChoice> choices) {
        this.id = id;
        this.questionText = Optional.ofNullable(questionText)
            .orElseThrow(() -> new IllegalArgumentException("questionText cannot be null"));
        this.helpText = helpText;
        this.choices = Optional.ofNullable(choices)
            .orElseThrow(() -> new IllegalArgumentException("choices cannot be null"));
    }
    
    public SubmitInteractionQuestion(
            long id,
            @Nonnull String questionText,
            @Nonnull List<SubmitInteractionChoice> choices) {
        this(id, questionText, null,
            choices);
    }

    public long id() {
        return this.id;
    }

    public String questionText() {
        return this.questionText;
    }

    public Optional<String> helpText() {
        return Optional.ofNullable(this.helpText);
    }

    public List<SubmitInteractionChoice> choices() {
        return this.choices;
    }

    public static Builder builder() {
        return new Builder();
    }


    public SubmitInteractionQuestion withId(long id) {
        this.id = id;
        return this;
    }


    public SubmitInteractionQuestion withQuestionText(@Nonnull String questionText) {
        this.questionText = Utils.checkNotNull(questionText, "questionText");
        return this;
    }


    public SubmitInteractionQuestion withHelpText(@Nullable String helpText) {
        this.helpText = helpText;
        return this;
    }


    public SubmitInteractionQuestion withChoices(@Nonnull List<SubmitInteractionChoice> choices) {
        this.choices = Utils.checkNotNull(choices, "choices");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SubmitInteractionQuestion other = (SubmitInteractionQuestion) o;
        return 
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.questionText, other.questionText) &&
            Utils.enhancedDeepEquals(this.helpText, other.helpText) &&
            Utils.enhancedDeepEquals(this.choices, other.choices);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            id, questionText, helpText,
            choices);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SubmitInteractionQuestion.class,
                "id", id,
                "questionText", questionText,
                "helpText", helpText,
                "choices", choices);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private long id;

        private String questionText;

        private String helpText;

        private List<SubmitInteractionChoice> choices;

        private Builder() {
          // force use of static builder() method
        }

        public Builder id(long id) {
            this.id = id;
            return this;
        }

        public Builder questionText(@Nonnull String questionText) {
            this.questionText = Utils.checkNotNull(questionText, "questionText");
            return this;
        }

        public Builder helpText(@Nullable String helpText) {
            this.helpText = helpText;
            return this;
        }

        public Builder choices(@Nonnull List<SubmitInteractionChoice> choices) {
            this.choices = Utils.checkNotNull(choices, "choices");
            return this;
        }

        public SubmitInteractionQuestion build() {
            return new SubmitInteractionQuestion(
                id, questionText, helpText,
                choices);
        }

    }
}
