/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum SubmitInteractionDocumentRelationship {
    MOTHER("mother"),
    FATHER("father"),
    MATERNAL_GRAND_FATHER("maternalGrandFather"),
    MATERNAL_GRAND_MOTHER("maternalGrandMother"),
    PATERNAL_GRAND_FATHER("paternalGrandFather"),
    PATERNAL_GRAND_MOTHER("paternalGrandMother");

    @JsonValue
    private final String value;

    SubmitInteractionDocumentRelationship(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<SubmitInteractionDocumentRelationship> fromValue(String value) {
        for (SubmitInteractionDocumentRelationship o: SubmitInteractionDocumentRelationship.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

