/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum SubmitInteractionBiometricType {
    STORED_FACE("storedFace");

    @JsonValue
    private final String value;

    SubmitInteractionBiometricType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<SubmitInteractionBiometricType> fromValue(String value) {
        for (SubmitInteractionBiometricType o: SubmitInteractionBiometricType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

