/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;


public class SubmitInteractionSession {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("user")
    private SubmitInteractionUser user;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("client")
    private SubmitInteractionClient client;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("device")
    private SubmitInteractionSessionDevice device;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("trace")
    private SubmitInteractionTrace trace;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("span")
    private SubmitInteractionSpan span;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("transaction")
    private SubmitInteractionTransaction transaction;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("auth")
    private List<SubmitInteractionSessionAuth> auth;

    @JsonCreator
    public SubmitInteractionSession(
            @JsonProperty("user") @Nullable SubmitInteractionUser user,
            @JsonProperty("client") @Nullable SubmitInteractionClient client,
            @JsonProperty("device") @Nullable SubmitInteractionSessionDevice device,
            @JsonProperty("trace") @Nullable SubmitInteractionTrace trace,
            @JsonProperty("span") @Nullable SubmitInteractionSpan span,
            @JsonProperty("transaction") @Nullable SubmitInteractionTransaction transaction,
            @JsonProperty("auth") @Nullable List<SubmitInteractionSessionAuth> auth) {
        this.user = user;
        this.client = client;
        this.device = device;
        this.trace = trace;
        this.span = span;
        this.transaction = transaction;
        this.auth = auth;
    }
    
    public SubmitInteractionSession() {
        this(null, null, null,
            null, null, null,
            null);
    }

    public Optional<SubmitInteractionUser> user() {
        return Optional.ofNullable(this.user);
    }

    public Optional<SubmitInteractionClient> client() {
        return Optional.ofNullable(this.client);
    }

    public Optional<SubmitInteractionSessionDevice> device() {
        return Optional.ofNullable(this.device);
    }

    public Optional<SubmitInteractionTrace> trace() {
        return Optional.ofNullable(this.trace);
    }

    public Optional<SubmitInteractionSpan> span() {
        return Optional.ofNullable(this.span);
    }

    public Optional<SubmitInteractionTransaction> transaction() {
        return Optional.ofNullable(this.transaction);
    }

    public Optional<List<SubmitInteractionSessionAuth>> auth() {
        return Optional.ofNullable(this.auth);
    }

    public static Builder builder() {
        return new Builder();
    }


    public SubmitInteractionSession withUser(@Nullable SubmitInteractionUser user) {
        this.user = user;
        return this;
    }


    public SubmitInteractionSession withClient(@Nullable SubmitInteractionClient client) {
        this.client = client;
        return this;
    }


    public SubmitInteractionSession withDevice(@Nullable SubmitInteractionSessionDevice device) {
        this.device = device;
        return this;
    }


    public SubmitInteractionSession withTrace(@Nullable SubmitInteractionTrace trace) {
        this.trace = trace;
        return this;
    }


    public SubmitInteractionSession withSpan(@Nullable SubmitInteractionSpan span) {
        this.span = span;
        return this;
    }


    public SubmitInteractionSession withTransaction(@Nullable SubmitInteractionTransaction transaction) {
        this.transaction = transaction;
        return this;
    }


    public SubmitInteractionSession withAuth(@Nullable List<SubmitInteractionSessionAuth> auth) {
        this.auth = auth;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SubmitInteractionSession other = (SubmitInteractionSession) o;
        return 
            Utils.enhancedDeepEquals(this.user, other.user) &&
            Utils.enhancedDeepEquals(this.client, other.client) &&
            Utils.enhancedDeepEquals(this.device, other.device) &&
            Utils.enhancedDeepEquals(this.trace, other.trace) &&
            Utils.enhancedDeepEquals(this.span, other.span) &&
            Utils.enhancedDeepEquals(this.transaction, other.transaction) &&
            Utils.enhancedDeepEquals(this.auth, other.auth);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            user, client, device,
            trace, span, transaction,
            auth);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SubmitInteractionSession.class,
                "user", user,
                "client", client,
                "device", device,
                "trace", trace,
                "span", span,
                "transaction", transaction,
                "auth", auth);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private SubmitInteractionUser user;

        private SubmitInteractionClient client;

        private SubmitInteractionSessionDevice device;

        private SubmitInteractionTrace trace;

        private SubmitInteractionSpan span;

        private SubmitInteractionTransaction transaction;

        private List<SubmitInteractionSessionAuth> auth;

        private Builder() {
          // force use of static builder() method
        }

        public Builder user(@Nullable SubmitInteractionUser user) {
            this.user = user;
            return this;
        }

        public Builder client(@Nullable SubmitInteractionClient client) {
            this.client = client;
            return this;
        }

        public Builder device(@Nullable SubmitInteractionSessionDevice device) {
            this.device = device;
            return this;
        }

        public Builder trace(@Nullable SubmitInteractionTrace trace) {
            this.trace = trace;
            return this;
        }

        public Builder span(@Nullable SubmitInteractionSpan span) {
            this.span = span;
            return this;
        }

        public Builder transaction(@Nullable SubmitInteractionTransaction transaction) {
            this.transaction = transaction;
            return this;
        }

        public Builder auth(@Nullable List<SubmitInteractionSessionAuth> auth) {
            this.auth = auth;
            return this;
        }

        public SubmitInteractionSession build() {
            return new SubmitInteractionSession(
                user, client, device,
                trace, span, transaction,
                auth);
        }

    }
}
