/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum SubmitInteractionResult {
    SUCCESS("Success"),
    FAILURE("Failure"),
    SKIPPED("Skipped");

    @JsonValue
    private final String value;

    SubmitInteractionResult(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<SubmitInteractionResult> fromValue(String value) {
        for (SubmitInteractionResult o: SubmitInteractionResult.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

