/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class SubmitInteractionContext {

    @JsonProperty("subject")
    private SubmitInteractionSubject subject;

    @JsonCreator
    public SubmitInteractionContext(
            @JsonProperty("subject") @Nonnull SubmitInteractionSubject subject) {
        this.subject = Optional.ofNullable(subject)
            .orElseThrow(() -> new IllegalArgumentException("subject cannot be null"));
    }

    public SubmitInteractionSubject subject() {
        return this.subject;
    }

    public static Builder builder() {
        return new Builder();
    }


    public SubmitInteractionContext withSubject(@Nonnull SubmitInteractionSubject subject) {
        this.subject = Utils.checkNotNull(subject, "subject");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SubmitInteractionContext other = (SubmitInteractionContext) o;
        return 
            Utils.enhancedDeepEquals(this.subject, other.subject);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            subject);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SubmitInteractionContext.class,
                "subject", subject);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private SubmitInteractionSubject subject;

        private Builder() {
          // force use of static builder() method
        }

        public Builder subject(@Nonnull SubmitInteractionSubject subject) {
            this.subject = Utils.checkNotNull(subject, "subject");
            return this;
        }

        public SubmitInteractionContext build() {
            return new SubmitInteractionContext(
                subject);
        }

    }
}
