/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;


public class SubmitInteractionIdentity {
    /**
     * Title of an individual such as Mr, Mrs, Dr, Sir
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("title")
    private String title;

    /**
     * A person's name used by their collegues and friends to address them
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("firstName")
    private String firstName;

    /**
     * Any other registered names used by the individual, not aliases
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("middleNames")
    private List<String> middleNames;

    /**
     * Any family names for the individual
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("lastNames")
    private List<String> lastNames;

    /**
     * Any family names for the individual
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("lastNamesAtBirth")
    private List<String> lastNamesAtBirth;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("aliases")
    private List<SubmitInteractionIdentityAlias> aliases;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("relatedPersons")
    private List<SubmitInteractionIdentityRelatedPerson> relatedPersons;

    /**
     * Specified in year, month and day separated by -. For example 2017-1-1 or 2017-01-01 which conforms
     * to ISO 8601
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("dateOfBirth")
    private String dateOfBirth;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("gender")
    private String gender;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("currentAddress")
    private SubmitInteractionIdentityCurrentAddress currentAddress;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("previousAddresses")
    private List<SubmitInteractionIdentityPreviousAddress> previousAddresses;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("placeOfBirth")
    private SubmitInteractionIdentityPlaceOfBirth placeOfBirth;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("idNumbers")
    private List<SubmitInteractionIdentityIdNumber> idNumbers;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("phones")
    private List<SubmitInteractionIdentityPhone> phones;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("emails")
    private List<SubmitInteractionIdentityEmail> emails;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("socials")
    private List<SubmitInteractionIdentitySocial> socials;

    /**
     * The subject's mother's maiden name, used for identity verification
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("mothersMaidenName")
    private String mothersMaidenName;

    @JsonCreator
    public SubmitInteractionIdentity(
            @JsonProperty("title") @Nullable String title,
            @JsonProperty("firstName") @Nullable String firstName,
            @JsonProperty("middleNames") @Nullable List<String> middleNames,
            @JsonProperty("lastNames") @Nullable List<String> lastNames,
            @JsonProperty("lastNamesAtBirth") @Nullable List<String> lastNamesAtBirth,
            @JsonProperty("aliases") @Nullable List<SubmitInteractionIdentityAlias> aliases,
            @JsonProperty("relatedPersons") @Nullable List<SubmitInteractionIdentityRelatedPerson> relatedPersons,
            @JsonProperty("dateOfBirth") @Nullable String dateOfBirth,
            @JsonProperty("gender") @Nullable String gender,
            @JsonProperty("currentAddress") @Nullable SubmitInteractionIdentityCurrentAddress currentAddress,
            @JsonProperty("previousAddresses") @Nullable List<SubmitInteractionIdentityPreviousAddress> previousAddresses,
            @JsonProperty("placeOfBirth") @Nullable SubmitInteractionIdentityPlaceOfBirth placeOfBirth,
            @JsonProperty("idNumbers") @Nullable List<SubmitInteractionIdentityIdNumber> idNumbers,
            @JsonProperty("phones") @Nullable List<SubmitInteractionIdentityPhone> phones,
            @JsonProperty("emails") @Nullable List<SubmitInteractionIdentityEmail> emails,
            @JsonProperty("socials") @Nullable List<SubmitInteractionIdentitySocial> socials,
            @JsonProperty("mothersMaidenName") @Nullable String mothersMaidenName) {
        this.title = title;
        this.firstName = firstName;
        this.middleNames = middleNames;
        this.lastNames = lastNames;
        this.lastNamesAtBirth = lastNamesAtBirth;
        this.aliases = aliases;
        this.relatedPersons = relatedPersons;
        this.dateOfBirth = dateOfBirth;
        this.gender = gender;
        this.currentAddress = currentAddress;
        this.previousAddresses = previousAddresses;
        this.placeOfBirth = placeOfBirth;
        this.idNumbers = idNumbers;
        this.phones = phones;
        this.emails = emails;
        this.socials = socials;
        this.mothersMaidenName = mothersMaidenName;
    }
    
    public SubmitInteractionIdentity() {
        this(null, null, null,
            null, null, null,
            null, null, null,
            null, null, null,
            null, null, null,
            null, null);
    }

    /**
     * Title of an individual such as Mr, Mrs, Dr, Sir
     */
    public Optional<String> title() {
        return Optional.ofNullable(this.title);
    }

    /**
     * A person's name used by their collegues and friends to address them
     */
    public Optional<String> firstName() {
        return Optional.ofNullable(this.firstName);
    }

    /**
     * Any other registered names used by the individual, not aliases
     */
    public Optional<List<String>> middleNames() {
        return Optional.ofNullable(this.middleNames);
    }

    /**
     * Any family names for the individual
     */
    public Optional<List<String>> lastNames() {
        return Optional.ofNullable(this.lastNames);
    }

    /**
     * Any family names for the individual
     */
    public Optional<List<String>> lastNamesAtBirth() {
        return Optional.ofNullable(this.lastNamesAtBirth);
    }

    public Optional<List<SubmitInteractionIdentityAlias>> aliases() {
        return Optional.ofNullable(this.aliases);
    }

    public Optional<List<SubmitInteractionIdentityRelatedPerson>> relatedPersons() {
        return Optional.ofNullable(this.relatedPersons);
    }

    /**
     * Specified in year, month and day separated by -. For example 2017-1-1 or 2017-01-01 which conforms
     * to ISO 8601
     */
    public Optional<String> dateOfBirth() {
        return Optional.ofNullable(this.dateOfBirth);
    }

    public Optional<String> gender() {
        return Optional.ofNullable(this.gender);
    }

    public Optional<SubmitInteractionIdentityCurrentAddress> currentAddress() {
        return Optional.ofNullable(this.currentAddress);
    }

    public Optional<List<SubmitInteractionIdentityPreviousAddress>> previousAddresses() {
        return Optional.ofNullable(this.previousAddresses);
    }

    public Optional<SubmitInteractionIdentityPlaceOfBirth> placeOfBirth() {
        return Optional.ofNullable(this.placeOfBirth);
    }

    public Optional<List<SubmitInteractionIdentityIdNumber>> idNumbers() {
        return Optional.ofNullable(this.idNumbers);
    }

    public Optional<List<SubmitInteractionIdentityPhone>> phones() {
        return Optional.ofNullable(this.phones);
    }

    public Optional<List<SubmitInteractionIdentityEmail>> emails() {
        return Optional.ofNullable(this.emails);
    }

    public Optional<List<SubmitInteractionIdentitySocial>> socials() {
        return Optional.ofNullable(this.socials);
    }

    /**
     * The subject's mother's maiden name, used for identity verification
     */
    public Optional<String> mothersMaidenName() {
        return Optional.ofNullable(this.mothersMaidenName);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Title of an individual such as Mr, Mrs, Dr, Sir
     */
    public SubmitInteractionIdentity withTitle(@Nullable String title) {
        this.title = title;
        return this;
    }


    /**
     * A person's name used by their collegues and friends to address them
     */
    public SubmitInteractionIdentity withFirstName(@Nullable String firstName) {
        this.firstName = firstName;
        return this;
    }


    /**
     * Any other registered names used by the individual, not aliases
     */
    public SubmitInteractionIdentity withMiddleNames(@Nullable List<String> middleNames) {
        this.middleNames = middleNames;
        return this;
    }


    /**
     * Any family names for the individual
     */
    public SubmitInteractionIdentity withLastNames(@Nullable List<String> lastNames) {
        this.lastNames = lastNames;
        return this;
    }


    /**
     * Any family names for the individual
     */
    public SubmitInteractionIdentity withLastNamesAtBirth(@Nullable List<String> lastNamesAtBirth) {
        this.lastNamesAtBirth = lastNamesAtBirth;
        return this;
    }


    public SubmitInteractionIdentity withAliases(@Nullable List<SubmitInteractionIdentityAlias> aliases) {
        this.aliases = aliases;
        return this;
    }


    public SubmitInteractionIdentity withRelatedPersons(@Nullable List<SubmitInteractionIdentityRelatedPerson> relatedPersons) {
        this.relatedPersons = relatedPersons;
        return this;
    }


    /**
     * Specified in year, month and day separated by -. For example 2017-1-1 or 2017-01-01 which conforms
     * to ISO 8601
     */
    public SubmitInteractionIdentity withDateOfBirth(@Nullable String dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
        return this;
    }


    public SubmitInteractionIdentity withGender(@Nullable String gender) {
        this.gender = gender;
        return this;
    }


    public SubmitInteractionIdentity withCurrentAddress(@Nullable SubmitInteractionIdentityCurrentAddress currentAddress) {
        this.currentAddress = currentAddress;
        return this;
    }


    public SubmitInteractionIdentity withPreviousAddresses(@Nullable List<SubmitInteractionIdentityPreviousAddress> previousAddresses) {
        this.previousAddresses = previousAddresses;
        return this;
    }


    public SubmitInteractionIdentity withPlaceOfBirth(@Nullable SubmitInteractionIdentityPlaceOfBirth placeOfBirth) {
        this.placeOfBirth = placeOfBirth;
        return this;
    }


    public SubmitInteractionIdentity withIdNumbers(@Nullable List<SubmitInteractionIdentityIdNumber> idNumbers) {
        this.idNumbers = idNumbers;
        return this;
    }


    public SubmitInteractionIdentity withPhones(@Nullable List<SubmitInteractionIdentityPhone> phones) {
        this.phones = phones;
        return this;
    }


    public SubmitInteractionIdentity withEmails(@Nullable List<SubmitInteractionIdentityEmail> emails) {
        this.emails = emails;
        return this;
    }


    public SubmitInteractionIdentity withSocials(@Nullable List<SubmitInteractionIdentitySocial> socials) {
        this.socials = socials;
        return this;
    }


    /**
     * The subject's mother's maiden name, used for identity verification
     */
    public SubmitInteractionIdentity withMothersMaidenName(@Nullable String mothersMaidenName) {
        this.mothersMaidenName = mothersMaidenName;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SubmitInteractionIdentity other = (SubmitInteractionIdentity) o;
        return 
            Utils.enhancedDeepEquals(this.title, other.title) &&
            Utils.enhancedDeepEquals(this.firstName, other.firstName) &&
            Utils.enhancedDeepEquals(this.middleNames, other.middleNames) &&
            Utils.enhancedDeepEquals(this.lastNames, other.lastNames) &&
            Utils.enhancedDeepEquals(this.lastNamesAtBirth, other.lastNamesAtBirth) &&
            Utils.enhancedDeepEquals(this.aliases, other.aliases) &&
            Utils.enhancedDeepEquals(this.relatedPersons, other.relatedPersons) &&
            Utils.enhancedDeepEquals(this.dateOfBirth, other.dateOfBirth) &&
            Utils.enhancedDeepEquals(this.gender, other.gender) &&
            Utils.enhancedDeepEquals(this.currentAddress, other.currentAddress) &&
            Utils.enhancedDeepEquals(this.previousAddresses, other.previousAddresses) &&
            Utils.enhancedDeepEquals(this.placeOfBirth, other.placeOfBirth) &&
            Utils.enhancedDeepEquals(this.idNumbers, other.idNumbers) &&
            Utils.enhancedDeepEquals(this.phones, other.phones) &&
            Utils.enhancedDeepEquals(this.emails, other.emails) &&
            Utils.enhancedDeepEquals(this.socials, other.socials) &&
            Utils.enhancedDeepEquals(this.mothersMaidenName, other.mothersMaidenName);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            title, firstName, middleNames,
            lastNames, lastNamesAtBirth, aliases,
            relatedPersons, dateOfBirth, gender,
            currentAddress, previousAddresses, placeOfBirth,
            idNumbers, phones, emails,
            socials, mothersMaidenName);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SubmitInteractionIdentity.class,
                "title", title,
                "firstName", firstName,
                "middleNames", middleNames,
                "lastNames", lastNames,
                "lastNamesAtBirth", lastNamesAtBirth,
                "aliases", aliases,
                "relatedPersons", relatedPersons,
                "dateOfBirth", dateOfBirth,
                "gender", gender,
                "currentAddress", currentAddress,
                "previousAddresses", previousAddresses,
                "placeOfBirth", placeOfBirth,
                "idNumbers", idNumbers,
                "phones", phones,
                "emails", emails,
                "socials", socials,
                "mothersMaidenName", mothersMaidenName);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String title;

        private String firstName;

        private List<String> middleNames;

        private List<String> lastNames;

        private List<String> lastNamesAtBirth;

        private List<SubmitInteractionIdentityAlias> aliases;

        private List<SubmitInteractionIdentityRelatedPerson> relatedPersons;

        private String dateOfBirth;

        private String gender;

        private SubmitInteractionIdentityCurrentAddress currentAddress;

        private List<SubmitInteractionIdentityPreviousAddress> previousAddresses;

        private SubmitInteractionIdentityPlaceOfBirth placeOfBirth;

        private List<SubmitInteractionIdentityIdNumber> idNumbers;

        private List<SubmitInteractionIdentityPhone> phones;

        private List<SubmitInteractionIdentityEmail> emails;

        private List<SubmitInteractionIdentitySocial> socials;

        private String mothersMaidenName;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Title of an individual such as Mr, Mrs, Dr, Sir
         */
        public Builder title(@Nullable String title) {
            this.title = title;
            return this;
        }

        /**
         * A person's name used by their collegues and friends to address them
         */
        public Builder firstName(@Nullable String firstName) {
            this.firstName = firstName;
            return this;
        }

        /**
         * Any other registered names used by the individual, not aliases
         */
        public Builder middleNames(@Nullable List<String> middleNames) {
            this.middleNames = middleNames;
            return this;
        }

        /**
         * Any family names for the individual
         */
        public Builder lastNames(@Nullable List<String> lastNames) {
            this.lastNames = lastNames;
            return this;
        }

        /**
         * Any family names for the individual
         */
        public Builder lastNamesAtBirth(@Nullable List<String> lastNamesAtBirth) {
            this.lastNamesAtBirth = lastNamesAtBirth;
            return this;
        }

        public Builder aliases(@Nullable List<SubmitInteractionIdentityAlias> aliases) {
            this.aliases = aliases;
            return this;
        }

        public Builder relatedPersons(@Nullable List<SubmitInteractionIdentityRelatedPerson> relatedPersons) {
            this.relatedPersons = relatedPersons;
            return this;
        }

        /**
         * Specified in year, month and day separated by -. For example 2017-1-1 or 2017-01-01 which conforms
         * to ISO 8601
         */
        public Builder dateOfBirth(@Nullable String dateOfBirth) {
            this.dateOfBirth = dateOfBirth;
            return this;
        }

        public Builder gender(@Nullable String gender) {
            this.gender = gender;
            return this;
        }

        public Builder currentAddress(@Nullable SubmitInteractionIdentityCurrentAddress currentAddress) {
            this.currentAddress = currentAddress;
            return this;
        }

        public Builder previousAddresses(@Nullable List<SubmitInteractionIdentityPreviousAddress> previousAddresses) {
            this.previousAddresses = previousAddresses;
            return this;
        }

        public Builder placeOfBirth(@Nullable SubmitInteractionIdentityPlaceOfBirth placeOfBirth) {
            this.placeOfBirth = placeOfBirth;
            return this;
        }

        public Builder idNumbers(@Nullable List<SubmitInteractionIdentityIdNumber> idNumbers) {
            this.idNumbers = idNumbers;
            return this;
        }

        public Builder phones(@Nullable List<SubmitInteractionIdentityPhone> phones) {
            this.phones = phones;
            return this;
        }

        public Builder emails(@Nullable List<SubmitInteractionIdentityEmail> emails) {
            this.emails = emails;
            return this;
        }

        public Builder socials(@Nullable List<SubmitInteractionIdentitySocial> socials) {
            this.socials = socials;
            return this;
        }

        /**
         * The subject's mother's maiden name, used for identity verification
         */
        public Builder mothersMaidenName(@Nullable String mothersMaidenName) {
            this.mothersMaidenName = mothersMaidenName;
            return this;
        }

        public SubmitInteractionIdentity build() {
            return new SubmitInteractionIdentity(
                title, firstName, middleNames,
                lastNames, lastNamesAtBirth, aliases,
                relatedPersons, dateOfBirth, gender,
                currentAddress, previousAddresses, placeOfBirth,
                idNumbers, phones, emails,
                socials, mothersMaidenName);
        }

    }
}
