/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.util.Map;
import java.util.Optional;


public class UpdateTaskRequest {
    /**
     * Journey Instance Id, a unique identifier for a started journey instance.
     */
    @JsonProperty("instanceId")
    private String instanceId;

    /**
     * Task Id, a unique identifier for a task assigned to an End User during a Journey.
     */
    @JsonProperty("taskId")
    private String taskId;


    @JsonProperty("intent")
    private Intent intent;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("context")
    private UpdateTaskContext context;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    private Map<String, Object> data;

    @JsonCreator
    public UpdateTaskRequest(
            @JsonProperty("instanceId") @Nonnull String instanceId,
            @JsonProperty("taskId") @Nonnull String taskId,
            @JsonProperty("intent") @Nonnull Intent intent,
            @JsonProperty("context") @Nullable UpdateTaskContext context,
            @JsonProperty("data") @Nullable Map<String, Object> data) {
        this.instanceId = Optional.ofNullable(instanceId)
            .orElseThrow(() -> new IllegalArgumentException("instanceId cannot be null"));
        this.taskId = Optional.ofNullable(taskId)
            .orElseThrow(() -> new IllegalArgumentException("taskId cannot be null"));
        this.intent = Optional.ofNullable(intent)
            .orElseThrow(() -> new IllegalArgumentException("intent cannot be null"));
        this.context = context;
        this.data = data;
    }
    
    public UpdateTaskRequest(
            @Nonnull String instanceId,
            @Nonnull String taskId,
            @Nonnull Intent intent) {
        this(instanceId, taskId, intent,
            null, null);
    }

    /**
     * Journey Instance Id, a unique identifier for a started journey instance.
     */
    public String instanceId() {
        return this.instanceId;
    }

    /**
     * Task Id, a unique identifier for a task assigned to an End User during a Journey.
     */
    public String taskId() {
        return this.taskId;
    }

    public Intent intent() {
        return this.intent;
    }

    public Optional<UpdateTaskContext> context() {
        return Optional.ofNullable(this.context);
    }

    public Optional<Map<String, Object>> data() {
        return Optional.ofNullable(this.data);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Journey Instance Id, a unique identifier for a started journey instance.
     */
    public UpdateTaskRequest withInstanceId(@Nonnull String instanceId) {
        this.instanceId = Utils.checkNotNull(instanceId, "instanceId");
        return this;
    }


    /**
     * Task Id, a unique identifier for a task assigned to an End User during a Journey.
     */
    public UpdateTaskRequest withTaskId(@Nonnull String taskId) {
        this.taskId = Utils.checkNotNull(taskId, "taskId");
        return this;
    }


    public UpdateTaskRequest withIntent(@Nonnull Intent intent) {
        this.intent = Utils.checkNotNull(intent, "intent");
        return this;
    }


    public UpdateTaskRequest withContext(@Nullable UpdateTaskContext context) {
        this.context = context;
        return this;
    }


    public UpdateTaskRequest withData(@Nullable Map<String, Object> data) {
        this.data = data;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdateTaskRequest other = (UpdateTaskRequest) o;
        return 
            Utils.enhancedDeepEquals(this.instanceId, other.instanceId) &&
            Utils.enhancedDeepEquals(this.taskId, other.taskId) &&
            Utils.enhancedDeepEquals(this.intent, other.intent) &&
            Utils.enhancedDeepEquals(this.context, other.context) &&
            Utils.enhancedDeepEquals(this.data, other.data);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            instanceId, taskId, intent,
            context, data);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UpdateTaskRequest.class,
                "instanceId", instanceId,
                "taskId", taskId,
                "intent", intent,
                "context", context,
                "data", data);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String instanceId;

        private String taskId;

        private Intent intent;

        private UpdateTaskContext context;

        private Map<String, Object> data;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Journey Instance Id, a unique identifier for a started journey instance.
         */
        public Builder instanceId(@Nonnull String instanceId) {
            this.instanceId = Utils.checkNotNull(instanceId, "instanceId");
            return this;
        }

        /**
         * Task Id, a unique identifier for a task assigned to an End User during a Journey.
         */
        public Builder taskId(@Nonnull String taskId) {
            this.taskId = Utils.checkNotNull(taskId, "taskId");
            return this;
        }

        public Builder intent(@Nonnull Intent intent) {
            this.intent = Utils.checkNotNull(intent, "intent");
            return this;
        }

        public Builder context(@Nullable UpdateTaskContext context) {
            this.context = context;
            return this;
        }

        public Builder data(@Nullable Map<String, Object> data) {
            this.data = data;
            return this;
        }

        public UpdateTaskRequest build() {
            return new UpdateTaskRequest(
                instanceId, taskId, intent,
                context, data);
        }

    }
}
