/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;


public class UpdateTaskClassification {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("ids")
    private List<String> ids;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("category")
    private String category;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("type")
    private String type;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("subtype")
    private String subtype;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("isDoubleSided")
    private Boolean isDoubleSided;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("hasNFC")
    private Boolean hasNFC;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("year")
    private String year;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("countryCode")
    private String countryCode;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("countryName")
    private String countryName;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("stateCode")
    private String stateCode;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("stateName")
    private String stateName;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("sides")
    private List<UpdateTaskSide> sides;

    @JsonCreator
    public UpdateTaskClassification(
            @JsonProperty("ids") @Nullable List<String> ids,
            @JsonProperty("category") @Nullable String category,
            @JsonProperty("type") @Nullable String type,
            @JsonProperty("subtype") @Nullable String subtype,
            @JsonProperty("isDoubleSided") @Nullable Boolean isDoubleSided,
            @JsonProperty("hasNFC") @Nullable Boolean hasNFC,
            @JsonProperty("year") @Nullable String year,
            @JsonProperty("countryCode") @Nullable String countryCode,
            @JsonProperty("countryName") @Nullable String countryName,
            @JsonProperty("stateCode") @Nullable String stateCode,
            @JsonProperty("stateName") @Nullable String stateName,
            @JsonProperty("sides") @Nullable List<UpdateTaskSide> sides) {
        this.ids = ids;
        this.category = category;
        this.type = type;
        this.subtype = subtype;
        this.isDoubleSided = isDoubleSided;
        this.hasNFC = hasNFC;
        this.year = year;
        this.countryCode = countryCode;
        this.countryName = countryName;
        this.stateCode = stateCode;
        this.stateName = stateName;
        this.sides = sides;
    }
    
    public UpdateTaskClassification() {
        this(null, null, null,
            null, null, null,
            null, null, null,
            null, null, null);
    }

    public Optional<List<String>> ids() {
        return Optional.ofNullable(this.ids);
    }

    public Optional<String> category() {
        return Optional.ofNullable(this.category);
    }

    public Optional<String> type() {
        return Optional.ofNullable(this.type);
    }

    public Optional<String> subtype() {
        return Optional.ofNullable(this.subtype);
    }

    public Optional<Boolean> isDoubleSided() {
        return Optional.ofNullable(this.isDoubleSided);
    }

    public Optional<Boolean> hasNFC() {
        return Optional.ofNullable(this.hasNFC);
    }

    public Optional<String> year() {
        return Optional.ofNullable(this.year);
    }

    public Optional<String> countryCode() {
        return Optional.ofNullable(this.countryCode);
    }

    public Optional<String> countryName() {
        return Optional.ofNullable(this.countryName);
    }

    public Optional<String> stateCode() {
        return Optional.ofNullable(this.stateCode);
    }

    public Optional<String> stateName() {
        return Optional.ofNullable(this.stateName);
    }

    public Optional<List<UpdateTaskSide>> sides() {
        return Optional.ofNullable(this.sides);
    }

    public static Builder builder() {
        return new Builder();
    }


    public UpdateTaskClassification withIds(@Nullable List<String> ids) {
        this.ids = ids;
        return this;
    }


    public UpdateTaskClassification withCategory(@Nullable String category) {
        this.category = category;
        return this;
    }


    public UpdateTaskClassification withType(@Nullable String type) {
        this.type = type;
        return this;
    }


    public UpdateTaskClassification withSubtype(@Nullable String subtype) {
        this.subtype = subtype;
        return this;
    }


    public UpdateTaskClassification withIsDoubleSided(@Nullable Boolean isDoubleSided) {
        this.isDoubleSided = isDoubleSided;
        return this;
    }


    public UpdateTaskClassification withHasNFC(@Nullable Boolean hasNFC) {
        this.hasNFC = hasNFC;
        return this;
    }


    public UpdateTaskClassification withYear(@Nullable String year) {
        this.year = year;
        return this;
    }


    public UpdateTaskClassification withCountryCode(@Nullable String countryCode) {
        this.countryCode = countryCode;
        return this;
    }


    public UpdateTaskClassification withCountryName(@Nullable String countryName) {
        this.countryName = countryName;
        return this;
    }


    public UpdateTaskClassification withStateCode(@Nullable String stateCode) {
        this.stateCode = stateCode;
        return this;
    }


    public UpdateTaskClassification withStateName(@Nullable String stateName) {
        this.stateName = stateName;
        return this;
    }


    public UpdateTaskClassification withSides(@Nullable List<UpdateTaskSide> sides) {
        this.sides = sides;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdateTaskClassification other = (UpdateTaskClassification) o;
        return 
            Utils.enhancedDeepEquals(this.ids, other.ids) &&
            Utils.enhancedDeepEquals(this.category, other.category) &&
            Utils.enhancedDeepEquals(this.type, other.type) &&
            Utils.enhancedDeepEquals(this.subtype, other.subtype) &&
            Utils.enhancedDeepEquals(this.isDoubleSided, other.isDoubleSided) &&
            Utils.enhancedDeepEquals(this.hasNFC, other.hasNFC) &&
            Utils.enhancedDeepEquals(this.year, other.year) &&
            Utils.enhancedDeepEquals(this.countryCode, other.countryCode) &&
            Utils.enhancedDeepEquals(this.countryName, other.countryName) &&
            Utils.enhancedDeepEquals(this.stateCode, other.stateCode) &&
            Utils.enhancedDeepEquals(this.stateName, other.stateName) &&
            Utils.enhancedDeepEquals(this.sides, other.sides);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            ids, category, type,
            subtype, isDoubleSided, hasNFC,
            year, countryCode, countryName,
            stateCode, stateName, sides);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UpdateTaskClassification.class,
                "ids", ids,
                "category", category,
                "type", type,
                "subtype", subtype,
                "isDoubleSided", isDoubleSided,
                "hasNFC", hasNFC,
                "year", year,
                "countryCode", countryCode,
                "countryName", countryName,
                "stateCode", stateCode,
                "stateName", stateName,
                "sides", sides);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private List<String> ids;

        private String category;

        private String type;

        private String subtype;

        private Boolean isDoubleSided;

        private Boolean hasNFC;

        private String year;

        private String countryCode;

        private String countryName;

        private String stateCode;

        private String stateName;

        private List<UpdateTaskSide> sides;

        private Builder() {
          // force use of static builder() method
        }

        public Builder ids(@Nullable List<String> ids) {
            this.ids = ids;
            return this;
        }

        public Builder category(@Nullable String category) {
            this.category = category;
            return this;
        }

        public Builder type(@Nullable String type) {
            this.type = type;
            return this;
        }

        public Builder subtype(@Nullable String subtype) {
            this.subtype = subtype;
            return this;
        }

        public Builder isDoubleSided(@Nullable Boolean isDoubleSided) {
            this.isDoubleSided = isDoubleSided;
            return this;
        }

        public Builder hasNFC(@Nullable Boolean hasNFC) {
            this.hasNFC = hasNFC;
            return this;
        }

        public Builder year(@Nullable String year) {
            this.year = year;
            return this;
        }

        public Builder countryCode(@Nullable String countryCode) {
            this.countryCode = countryCode;
            return this;
        }

        public Builder countryName(@Nullable String countryName) {
            this.countryName = countryName;
            return this;
        }

        public Builder stateCode(@Nullable String stateCode) {
            this.stateCode = stateCode;
            return this;
        }

        public Builder stateName(@Nullable String stateName) {
            this.stateName = stateName;
            return this;
        }

        public Builder sides(@Nullable List<UpdateTaskSide> sides) {
            this.sides = sides;
            return this;
        }

        public UpdateTaskClassification build() {
            return new UpdateTaskClassification(
                ids, category, type,
                subtype, isDoubleSided, hasNFC,
                year, countryCode, countryName,
                stateCode, stateName, sides);
        }

    }
}
