/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class UpdateTaskAggregatedFieldRegionOfInterest {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("boundingBox")
    private UpdateTaskAggregatedFieldBoundingBox boundingBox;


    @JsonProperty("side")
    private String side;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("spectrum")
    private String spectrum;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("imageId")
    private String imageId;

    @JsonCreator
    public UpdateTaskAggregatedFieldRegionOfInterest(
            @JsonProperty("boundingBox") @Nullable UpdateTaskAggregatedFieldBoundingBox boundingBox,
            @JsonProperty("side") @Nonnull String side,
            @JsonProperty("spectrum") @Nullable String spectrum,
            @JsonProperty("imageId") @Nullable String imageId) {
        this.boundingBox = boundingBox;
        this.side = Optional.ofNullable(side)
            .orElseThrow(() -> new IllegalArgumentException("side cannot be null"));
        this.spectrum = spectrum;
        this.imageId = imageId;
    }
    
    public UpdateTaskAggregatedFieldRegionOfInterest(
            @Nonnull String side) {
        this(null, side, null,
            null);
    }

    public Optional<UpdateTaskAggregatedFieldBoundingBox> boundingBox() {
        return Optional.ofNullable(this.boundingBox);
    }

    public String side() {
        return this.side;
    }

    public Optional<String> spectrum() {
        return Optional.ofNullable(this.spectrum);
    }

    public Optional<String> imageId() {
        return Optional.ofNullable(this.imageId);
    }

    public static Builder builder() {
        return new Builder();
    }


    public UpdateTaskAggregatedFieldRegionOfInterest withBoundingBox(@Nullable UpdateTaskAggregatedFieldBoundingBox boundingBox) {
        this.boundingBox = boundingBox;
        return this;
    }


    public UpdateTaskAggregatedFieldRegionOfInterest withSide(@Nonnull String side) {
        this.side = Utils.checkNotNull(side, "side");
        return this;
    }


    public UpdateTaskAggregatedFieldRegionOfInterest withSpectrum(@Nullable String spectrum) {
        this.spectrum = spectrum;
        return this;
    }


    public UpdateTaskAggregatedFieldRegionOfInterest withImageId(@Nullable String imageId) {
        this.imageId = imageId;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdateTaskAggregatedFieldRegionOfInterest other = (UpdateTaskAggregatedFieldRegionOfInterest) o;
        return 
            Utils.enhancedDeepEquals(this.boundingBox, other.boundingBox) &&
            Utils.enhancedDeepEquals(this.side, other.side) &&
            Utils.enhancedDeepEquals(this.spectrum, other.spectrum) &&
            Utils.enhancedDeepEquals(this.imageId, other.imageId);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            boundingBox, side, spectrum,
            imageId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UpdateTaskAggregatedFieldRegionOfInterest.class,
                "boundingBox", boundingBox,
                "side", side,
                "spectrum", spectrum,
                "imageId", imageId);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private UpdateTaskAggregatedFieldBoundingBox boundingBox;

        private String side;

        private String spectrum;

        private String imageId;

        private Builder() {
          // force use of static builder() method
        }

        public Builder boundingBox(@Nullable UpdateTaskAggregatedFieldBoundingBox boundingBox) {
            this.boundingBox = boundingBox;
            return this;
        }

        public Builder side(@Nonnull String side) {
            this.side = Utils.checkNotNull(side, "side");
            return this;
        }

        public Builder spectrum(@Nullable String spectrum) {
            this.spectrum = spectrum;
            return this;
        }

        public Builder imageId(@Nullable String imageId) {
            this.imageId = imageId;
            return this;
        }

        public UpdateTaskAggregatedFieldRegionOfInterest build() {
            return new UpdateTaskAggregatedFieldRegionOfInterest(
                boundingBox, side, spectrum,
                imageId);
        }

    }
}
