/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class UpdateTaskDocumentDevice {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("type")
    private String type;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("model")
    private String model;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("hasContactlessReader")
    private Boolean hasContactlessReader;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("hasMagneticStripeReader")
    private Boolean hasMagneticStripeReader;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("hasCamera")
    private Boolean hasCamera;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("serialNumber")
    private String serialNumber;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("manufacturer")
    private String manufacturer;

    @JsonCreator
    public UpdateTaskDocumentDevice(
            @JsonProperty("type") @Nullable String type,
            @JsonProperty("model") @Nullable String model,
            @JsonProperty("hasContactlessReader") @Nullable Boolean hasContactlessReader,
            @JsonProperty("hasMagneticStripeReader") @Nullable Boolean hasMagneticStripeReader,
            @JsonProperty("hasCamera") @Nullable Boolean hasCamera,
            @JsonProperty("serialNumber") @Nullable String serialNumber,
            @JsonProperty("manufacturer") @Nullable String manufacturer) {
        this.type = type;
        this.model = model;
        this.hasContactlessReader = hasContactlessReader;
        this.hasMagneticStripeReader = hasMagneticStripeReader;
        this.hasCamera = hasCamera;
        this.serialNumber = serialNumber;
        this.manufacturer = manufacturer;
    }
    
    public UpdateTaskDocumentDevice() {
        this(null, null, null,
            null, null, null,
            null);
    }

    public Optional<String> type() {
        return Optional.ofNullable(this.type);
    }

    public Optional<String> model() {
        return Optional.ofNullable(this.model);
    }

    public Optional<Boolean> hasContactlessReader() {
        return Optional.ofNullable(this.hasContactlessReader);
    }

    public Optional<Boolean> hasMagneticStripeReader() {
        return Optional.ofNullable(this.hasMagneticStripeReader);
    }

    public Optional<Boolean> hasCamera() {
        return Optional.ofNullable(this.hasCamera);
    }

    public Optional<String> serialNumber() {
        return Optional.ofNullable(this.serialNumber);
    }

    public Optional<String> manufacturer() {
        return Optional.ofNullable(this.manufacturer);
    }

    public static Builder builder() {
        return new Builder();
    }


    public UpdateTaskDocumentDevice withType(@Nullable String type) {
        this.type = type;
        return this;
    }


    public UpdateTaskDocumentDevice withModel(@Nullable String model) {
        this.model = model;
        return this;
    }


    public UpdateTaskDocumentDevice withHasContactlessReader(@Nullable Boolean hasContactlessReader) {
        this.hasContactlessReader = hasContactlessReader;
        return this;
    }


    public UpdateTaskDocumentDevice withHasMagneticStripeReader(@Nullable Boolean hasMagneticStripeReader) {
        this.hasMagneticStripeReader = hasMagneticStripeReader;
        return this;
    }


    public UpdateTaskDocumentDevice withHasCamera(@Nullable Boolean hasCamera) {
        this.hasCamera = hasCamera;
        return this;
    }


    public UpdateTaskDocumentDevice withSerialNumber(@Nullable String serialNumber) {
        this.serialNumber = serialNumber;
        return this;
    }


    public UpdateTaskDocumentDevice withManufacturer(@Nullable String manufacturer) {
        this.manufacturer = manufacturer;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdateTaskDocumentDevice other = (UpdateTaskDocumentDevice) o;
        return 
            Utils.enhancedDeepEquals(this.type, other.type) &&
            Utils.enhancedDeepEquals(this.model, other.model) &&
            Utils.enhancedDeepEquals(this.hasContactlessReader, other.hasContactlessReader) &&
            Utils.enhancedDeepEquals(this.hasMagneticStripeReader, other.hasMagneticStripeReader) &&
            Utils.enhancedDeepEquals(this.hasCamera, other.hasCamera) &&
            Utils.enhancedDeepEquals(this.serialNumber, other.serialNumber) &&
            Utils.enhancedDeepEquals(this.manufacturer, other.manufacturer);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            type, model, hasContactlessReader,
            hasMagneticStripeReader, hasCamera, serialNumber,
            manufacturer);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UpdateTaskDocumentDevice.class,
                "type", type,
                "model", model,
                "hasContactlessReader", hasContactlessReader,
                "hasMagneticStripeReader", hasMagneticStripeReader,
                "hasCamera", hasCamera,
                "serialNumber", serialNumber,
                "manufacturer", manufacturer);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String type;

        private String model;

        private Boolean hasContactlessReader;

        private Boolean hasMagneticStripeReader;

        private Boolean hasCamera;

        private String serialNumber;

        private String manufacturer;

        private Builder() {
          // force use of static builder() method
        }

        public Builder type(@Nullable String type) {
            this.type = type;
            return this;
        }

        public Builder model(@Nullable String model) {
            this.model = model;
            return this;
        }

        public Builder hasContactlessReader(@Nullable Boolean hasContactlessReader) {
            this.hasContactlessReader = hasContactlessReader;
            return this;
        }

        public Builder hasMagneticStripeReader(@Nullable Boolean hasMagneticStripeReader) {
            this.hasMagneticStripeReader = hasMagneticStripeReader;
            return this;
        }

        public Builder hasCamera(@Nullable Boolean hasCamera) {
            this.hasCamera = hasCamera;
            return this;
        }

        public Builder serialNumber(@Nullable String serialNumber) {
            this.serialNumber = serialNumber;
            return this;
        }

        public Builder manufacturer(@Nullable String manufacturer) {
            this.manufacturer = manufacturer;
            return this;
        }

        public UpdateTaskDocumentDevice build() {
            return new UpdateTaskDocumentDevice(
                type, model, hasContactlessReader,
                hasMagneticStripeReader, hasCamera, serialNumber,
                manufacturer);
        }

    }
}
