/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class UpdateTaskSessionDevice {

    @JsonProperty("id")
    private String id;


    @JsonProperty("manufacturer")
    private String manufacturer;


    @JsonProperty("model")
    private UpdateTaskModel model;

    @JsonCreator
    public UpdateTaskSessionDevice(
            @JsonProperty("id") @Nonnull String id,
            @JsonProperty("manufacturer") @Nonnull String manufacturer,
            @JsonProperty("model") @Nonnull UpdateTaskModel model) {
        this.id = Optional.ofNullable(id)
            .orElseThrow(() -> new IllegalArgumentException("id cannot be null"));
        this.manufacturer = Optional.ofNullable(manufacturer)
            .orElseThrow(() -> new IllegalArgumentException("manufacturer cannot be null"));
        this.model = Optional.ofNullable(model)
            .orElseThrow(() -> new IllegalArgumentException("model cannot be null"));
    }

    public String id() {
        return this.id;
    }

    public String manufacturer() {
        return this.manufacturer;
    }

    public UpdateTaskModel model() {
        return this.model;
    }

    public static Builder builder() {
        return new Builder();
    }


    public UpdateTaskSessionDevice withId(@Nonnull String id) {
        this.id = Utils.checkNotNull(id, "id");
        return this;
    }


    public UpdateTaskSessionDevice withManufacturer(@Nonnull String manufacturer) {
        this.manufacturer = Utils.checkNotNull(manufacturer, "manufacturer");
        return this;
    }


    public UpdateTaskSessionDevice withModel(@Nonnull UpdateTaskModel model) {
        this.model = Utils.checkNotNull(model, "model");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdateTaskSessionDevice other = (UpdateTaskSessionDevice) o;
        return 
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.manufacturer, other.manufacturer) &&
            Utils.enhancedDeepEquals(this.model, other.model);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            id, manufacturer, model);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UpdateTaskSessionDevice.class,
                "id", id,
                "manufacturer", manufacturer,
                "model", model);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String id;

        private String manufacturer;

        private UpdateTaskModel model;

        private Builder() {
          // force use of static builder() method
        }

        public Builder id(@Nonnull String id) {
            this.id = Utils.checkNotNull(id, "id");
            return this;
        }

        public Builder manufacturer(@Nonnull String manufacturer) {
            this.manufacturer = Utils.checkNotNull(manufacturer, "manufacturer");
            return this;
        }

        public Builder model(@Nonnull UpdateTaskModel model) {
            this.model = Utils.checkNotNull(model, "model");
            return this;
        }

        public UpdateTaskSessionDevice build() {
            return new UpdateTaskSessionDevice(
                id, manufacturer, model);
        }

    }
}
