/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class UpdateTaskUser {

    @JsonProperty("id")
    private String id;


    @JsonProperty("email")
    private String email;


    @JsonProperty("domain")
    private String domain;

    @JsonCreator
    public UpdateTaskUser(
            @JsonProperty("id") @Nonnull String id,
            @JsonProperty("email") @Nonnull String email,
            @JsonProperty("domain") @Nonnull String domain) {
        this.id = Optional.ofNullable(id)
            .orElseThrow(() -> new IllegalArgumentException("id cannot be null"));
        this.email = Optional.ofNullable(email)
            .orElseThrow(() -> new IllegalArgumentException("email cannot be null"));
        this.domain = Optional.ofNullable(domain)
            .orElseThrow(() -> new IllegalArgumentException("domain cannot be null"));
    }

    public String id() {
        return this.id;
    }

    public String email() {
        return this.email;
    }

    public String domain() {
        return this.domain;
    }

    public static Builder builder() {
        return new Builder();
    }


    public UpdateTaskUser withId(@Nonnull String id) {
        this.id = Utils.checkNotNull(id, "id");
        return this;
    }


    public UpdateTaskUser withEmail(@Nonnull String email) {
        this.email = Utils.checkNotNull(email, "email");
        return this;
    }


    public UpdateTaskUser withDomain(@Nonnull String domain) {
        this.domain = Utils.checkNotNull(domain, "domain");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdateTaskUser other = (UpdateTaskUser) o;
        return 
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.email, other.email) &&
            Utils.enhancedDeepEquals(this.domain, other.domain);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            id, email, domain);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UpdateTaskUser.class,
                "id", id,
                "email", email,
                "domain", domain);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String id;

        private String email;

        private String domain;

        private Builder() {
          // force use of static builder() method
        }

        public Builder id(@Nonnull String id) {
            this.id = Utils.checkNotNull(id, "id");
            return this;
        }

        public Builder email(@Nonnull String email) {
            this.email = Utils.checkNotNull(email, "email");
            return this;
        }

        public Builder domain(@Nonnull String domain) {
            this.domain = Utils.checkNotNull(domain, "domain");
            return this;
        }

        public UpdateTaskUser build() {
            return new UpdateTaskUser(
                id, email, domain);
        }

    }
}
