/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class DeviceRefreshResponse {

    @JsonProperty("endUserToken")
    private String endUserToken;


    @JsonProperty("expiresIn")
    private double expiresIn;


    @JsonProperty("instanceId")
    private String instanceId;


    @JsonProperty("resumeCredential")
    private String resumeCredential;


    @JsonProperty("credentialExpiresAt")
    private String credentialExpiresAt;


    @JsonProperty("credentialExpiresIn")
    private double credentialExpiresIn;


    @JsonProperty("linkExpiresAt")
    private String linkExpiresAt;

    @JsonCreator
    public DeviceRefreshResponse(
            @JsonProperty("endUserToken") @Nonnull String endUserToken,
            @JsonProperty("expiresIn") double expiresIn,
            @JsonProperty("instanceId") @Nonnull String instanceId,
            @JsonProperty("resumeCredential") @Nonnull String resumeCredential,
            @JsonProperty("credentialExpiresAt") @Nonnull String credentialExpiresAt,
            @JsonProperty("credentialExpiresIn") double credentialExpiresIn,
            @JsonProperty("linkExpiresAt") @Nonnull String linkExpiresAt) {
        this.endUserToken = Optional.ofNullable(endUserToken)
            .orElseThrow(() -> new IllegalArgumentException("endUserToken cannot be null"));
        this.expiresIn = expiresIn;
        this.instanceId = Optional.ofNullable(instanceId)
            .orElseThrow(() -> new IllegalArgumentException("instanceId cannot be null"));
        this.resumeCredential = Optional.ofNullable(resumeCredential)
            .orElseThrow(() -> new IllegalArgumentException("resumeCredential cannot be null"));
        this.credentialExpiresAt = Optional.ofNullable(credentialExpiresAt)
            .orElseThrow(() -> new IllegalArgumentException("credentialExpiresAt cannot be null"));
        this.credentialExpiresIn = credentialExpiresIn;
        this.linkExpiresAt = Optional.ofNullable(linkExpiresAt)
            .orElseThrow(() -> new IllegalArgumentException("linkExpiresAt cannot be null"));
    }

    public String endUserToken() {
        return this.endUserToken;
    }

    public double expiresIn() {
        return this.expiresIn;
    }

    public String instanceId() {
        return this.instanceId;
    }

    public String resumeCredential() {
        return this.resumeCredential;
    }

    public String credentialExpiresAt() {
        return this.credentialExpiresAt;
    }

    public double credentialExpiresIn() {
        return this.credentialExpiresIn;
    }

    public String linkExpiresAt() {
        return this.linkExpiresAt;
    }

    public static Builder builder() {
        return new Builder();
    }


    public DeviceRefreshResponse withEndUserToken(@Nonnull String endUserToken) {
        this.endUserToken = Utils.checkNotNull(endUserToken, "endUserToken");
        return this;
    }


    public DeviceRefreshResponse withExpiresIn(double expiresIn) {
        this.expiresIn = expiresIn;
        return this;
    }


    public DeviceRefreshResponse withInstanceId(@Nonnull String instanceId) {
        this.instanceId = Utils.checkNotNull(instanceId, "instanceId");
        return this;
    }


    public DeviceRefreshResponse withResumeCredential(@Nonnull String resumeCredential) {
        this.resumeCredential = Utils.checkNotNull(resumeCredential, "resumeCredential");
        return this;
    }


    public DeviceRefreshResponse withCredentialExpiresAt(@Nonnull String credentialExpiresAt) {
        this.credentialExpiresAt = Utils.checkNotNull(credentialExpiresAt, "credentialExpiresAt");
        return this;
    }


    public DeviceRefreshResponse withCredentialExpiresIn(double credentialExpiresIn) {
        this.credentialExpiresIn = credentialExpiresIn;
        return this;
    }


    public DeviceRefreshResponse withLinkExpiresAt(@Nonnull String linkExpiresAt) {
        this.linkExpiresAt = Utils.checkNotNull(linkExpiresAt, "linkExpiresAt");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DeviceRefreshResponse other = (DeviceRefreshResponse) o;
        return 
            Utils.enhancedDeepEquals(this.endUserToken, other.endUserToken) &&
            Utils.enhancedDeepEquals(this.expiresIn, other.expiresIn) &&
            Utils.enhancedDeepEquals(this.instanceId, other.instanceId) &&
            Utils.enhancedDeepEquals(this.resumeCredential, other.resumeCredential) &&
            Utils.enhancedDeepEquals(this.credentialExpiresAt, other.credentialExpiresAt) &&
            Utils.enhancedDeepEquals(this.credentialExpiresIn, other.credentialExpiresIn) &&
            Utils.enhancedDeepEquals(this.linkExpiresAt, other.linkExpiresAt);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            endUserToken, expiresIn, instanceId,
            resumeCredential, credentialExpiresAt, credentialExpiresIn,
            linkExpiresAt);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DeviceRefreshResponse.class,
                "endUserToken", endUserToken,
                "expiresIn", expiresIn,
                "instanceId", instanceId,
                "resumeCredential", resumeCredential,
                "credentialExpiresAt", credentialExpiresAt,
                "credentialExpiresIn", credentialExpiresIn,
                "linkExpiresAt", linkExpiresAt);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String endUserToken;

        private double expiresIn;

        private String instanceId;

        private String resumeCredential;

        private String credentialExpiresAt;

        private double credentialExpiresIn;

        private String linkExpiresAt;

        private Builder() {
          // force use of static builder() method
        }

        public Builder endUserToken(@Nonnull String endUserToken) {
            this.endUserToken = Utils.checkNotNull(endUserToken, "endUserToken");
            return this;
        }

        public Builder expiresIn(double expiresIn) {
            this.expiresIn = expiresIn;
            return this;
        }

        public Builder instanceId(@Nonnull String instanceId) {
            this.instanceId = Utils.checkNotNull(instanceId, "instanceId");
            return this;
        }

        public Builder resumeCredential(@Nonnull String resumeCredential) {
            this.resumeCredential = Utils.checkNotNull(resumeCredential, "resumeCredential");
            return this;
        }

        public Builder credentialExpiresAt(@Nonnull String credentialExpiresAt) {
            this.credentialExpiresAt = Utils.checkNotNull(credentialExpiresAt, "credentialExpiresAt");
            return this;
        }

        public Builder credentialExpiresIn(double credentialExpiresIn) {
            this.credentialExpiresIn = credentialExpiresIn;
            return this;
        }

        public Builder linkExpiresAt(@Nonnull String linkExpiresAt) {
            this.linkExpiresAt = Utils.checkNotNull(linkExpiresAt, "linkExpiresAt");
            return this;
        }

        public DeviceRefreshResponse build() {
            return new DeviceRefreshResponse(
                endUserToken, expiresIn, instanceId,
                resumeCredential, credentialExpiresAt, credentialExpiresIn,
                linkExpiresAt);
        }

    }
}
