/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Double;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class DeviceConnectResponse {

    @JsonProperty("endUserToken")
    private String endUserToken;


    @JsonProperty("tokenType")
    private DeviceConnectResponseTokenType tokenType;


    @JsonProperty("expiresIn")
    private double expiresIn;


    @JsonProperty("instanceId")
    private String instanceId;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("resumeCredential")
    private String resumeCredential;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("credentialExpiresAt")
    private String credentialExpiresAt;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("credentialExpiresIn")
    private Double credentialExpiresIn;

    @JsonCreator
    public DeviceConnectResponse(
            @JsonProperty("endUserToken") @Nonnull String endUserToken,
            @JsonProperty("tokenType") @Nonnull DeviceConnectResponseTokenType tokenType,
            @JsonProperty("expiresIn") double expiresIn,
            @JsonProperty("instanceId") @Nonnull String instanceId,
            @JsonProperty("resumeCredential") @Nullable String resumeCredential,
            @JsonProperty("credentialExpiresAt") @Nullable String credentialExpiresAt,
            @JsonProperty("credentialExpiresIn") @Nullable Double credentialExpiresIn) {
        this.endUserToken = Optional.ofNullable(endUserToken)
            .orElseThrow(() -> new IllegalArgumentException("endUserToken cannot be null"));
        this.tokenType = Optional.ofNullable(tokenType)
            .orElseThrow(() -> new IllegalArgumentException("tokenType cannot be null"));
        this.expiresIn = expiresIn;
        this.instanceId = Optional.ofNullable(instanceId)
            .orElseThrow(() -> new IllegalArgumentException("instanceId cannot be null"));
        this.resumeCredential = resumeCredential;
        this.credentialExpiresAt = credentialExpiresAt;
        this.credentialExpiresIn = credentialExpiresIn;
    }
    
    public DeviceConnectResponse(
            @Nonnull String endUserToken,
            @Nonnull DeviceConnectResponseTokenType tokenType,
            double expiresIn,
            @Nonnull String instanceId) {
        this(endUserToken, tokenType, expiresIn,
            instanceId, null, null,
            null);
    }

    public String endUserToken() {
        return this.endUserToken;
    }

    public DeviceConnectResponseTokenType tokenType() {
        return this.tokenType;
    }

    public double expiresIn() {
        return this.expiresIn;
    }

    public String instanceId() {
        return this.instanceId;
    }

    public Optional<String> resumeCredential() {
        return Optional.ofNullable(this.resumeCredential);
    }

    public Optional<String> credentialExpiresAt() {
        return Optional.ofNullable(this.credentialExpiresAt);
    }

    public Optional<Double> credentialExpiresIn() {
        return Optional.ofNullable(this.credentialExpiresIn);
    }

    public static Builder builder() {
        return new Builder();
    }


    public DeviceConnectResponse withEndUserToken(@Nonnull String endUserToken) {
        this.endUserToken = Utils.checkNotNull(endUserToken, "endUserToken");
        return this;
    }


    public DeviceConnectResponse withTokenType(@Nonnull DeviceConnectResponseTokenType tokenType) {
        this.tokenType = Utils.checkNotNull(tokenType, "tokenType");
        return this;
    }


    public DeviceConnectResponse withExpiresIn(double expiresIn) {
        this.expiresIn = expiresIn;
        return this;
    }


    public DeviceConnectResponse withInstanceId(@Nonnull String instanceId) {
        this.instanceId = Utils.checkNotNull(instanceId, "instanceId");
        return this;
    }


    public DeviceConnectResponse withResumeCredential(@Nullable String resumeCredential) {
        this.resumeCredential = resumeCredential;
        return this;
    }


    public DeviceConnectResponse withCredentialExpiresAt(@Nullable String credentialExpiresAt) {
        this.credentialExpiresAt = credentialExpiresAt;
        return this;
    }


    public DeviceConnectResponse withCredentialExpiresIn(@Nullable Double credentialExpiresIn) {
        this.credentialExpiresIn = credentialExpiresIn;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DeviceConnectResponse other = (DeviceConnectResponse) o;
        return 
            Utils.enhancedDeepEquals(this.endUserToken, other.endUserToken) &&
            Utils.enhancedDeepEquals(this.tokenType, other.tokenType) &&
            Utils.enhancedDeepEquals(this.expiresIn, other.expiresIn) &&
            Utils.enhancedDeepEquals(this.instanceId, other.instanceId) &&
            Utils.enhancedDeepEquals(this.resumeCredential, other.resumeCredential) &&
            Utils.enhancedDeepEquals(this.credentialExpiresAt, other.credentialExpiresAt) &&
            Utils.enhancedDeepEquals(this.credentialExpiresIn, other.credentialExpiresIn);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            endUserToken, tokenType, expiresIn,
            instanceId, resumeCredential, credentialExpiresAt,
            credentialExpiresIn);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DeviceConnectResponse.class,
                "endUserToken", endUserToken,
                "tokenType", tokenType,
                "expiresIn", expiresIn,
                "instanceId", instanceId,
                "resumeCredential", resumeCredential,
                "credentialExpiresAt", credentialExpiresAt,
                "credentialExpiresIn", credentialExpiresIn);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String endUserToken;

        private DeviceConnectResponseTokenType tokenType;

        private double expiresIn;

        private String instanceId;

        private String resumeCredential;

        private String credentialExpiresAt;

        private Double credentialExpiresIn;

        private Builder() {
          // force use of static builder() method
        }

        public Builder endUserToken(@Nonnull String endUserToken) {
            this.endUserToken = Utils.checkNotNull(endUserToken, "endUserToken");
            return this;
        }

        public Builder tokenType(@Nonnull DeviceConnectResponseTokenType tokenType) {
            this.tokenType = Utils.checkNotNull(tokenType, "tokenType");
            return this;
        }

        public Builder expiresIn(double expiresIn) {
            this.expiresIn = expiresIn;
            return this;
        }

        public Builder instanceId(@Nonnull String instanceId) {
            this.instanceId = Utils.checkNotNull(instanceId, "instanceId");
            return this;
        }

        public Builder resumeCredential(@Nullable String resumeCredential) {
            this.resumeCredential = resumeCredential;
            return this;
        }

        public Builder credentialExpiresAt(@Nullable String credentialExpiresAt) {
            this.credentialExpiresAt = credentialExpiresAt;
            return this;
        }

        public Builder credentialExpiresIn(@Nullable Double credentialExpiresIn) {
            this.credentialExpiresIn = credentialExpiresIn;
            return this;
        }

        public DeviceConnectResponse build() {
            return new DeviceConnectResponse(
                endUserToken, tokenType, expiresIn,
                instanceId, resumeCredential, credentialExpiresAt,
                credentialExpiresIn);
        }

    }
}
