/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;


public class DeviceStartResponse {

    @JsonProperty("connectToken")
    private String connectToken;


    @JsonProperty("tokenType")
    private DeviceStartResponseTokenType tokenType;


    @JsonProperty("expiresIn")
    private double expiresIn;


    @JsonProperty("scope")
    private List<String> scope;

    @JsonCreator
    public DeviceStartResponse(
            @JsonProperty("connectToken") @Nonnull String connectToken,
            @JsonProperty("tokenType") @Nonnull DeviceStartResponseTokenType tokenType,
            @JsonProperty("expiresIn") double expiresIn,
            @JsonProperty("scope") @Nonnull List<String> scope) {
        this.connectToken = Optional.ofNullable(connectToken)
            .orElseThrow(() -> new IllegalArgumentException("connectToken cannot be null"));
        this.tokenType = Optional.ofNullable(tokenType)
            .orElseThrow(() -> new IllegalArgumentException("tokenType cannot be null"));
        this.expiresIn = expiresIn;
        this.scope = Optional.ofNullable(scope)
            .orElseThrow(() -> new IllegalArgumentException("scope cannot be null"));
    }

    public String connectToken() {
        return this.connectToken;
    }

    public DeviceStartResponseTokenType tokenType() {
        return this.tokenType;
    }

    public double expiresIn() {
        return this.expiresIn;
    }

    public List<String> scope() {
        return this.scope;
    }

    public static Builder builder() {
        return new Builder();
    }


    public DeviceStartResponse withConnectToken(@Nonnull String connectToken) {
        this.connectToken = Utils.checkNotNull(connectToken, "connectToken");
        return this;
    }


    public DeviceStartResponse withTokenType(@Nonnull DeviceStartResponseTokenType tokenType) {
        this.tokenType = Utils.checkNotNull(tokenType, "tokenType");
        return this;
    }


    public DeviceStartResponse withExpiresIn(double expiresIn) {
        this.expiresIn = expiresIn;
        return this;
    }


    public DeviceStartResponse withScope(@Nonnull List<String> scope) {
        this.scope = Utils.checkNotNull(scope, "scope");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DeviceStartResponse other = (DeviceStartResponse) o;
        return 
            Utils.enhancedDeepEquals(this.connectToken, other.connectToken) &&
            Utils.enhancedDeepEquals(this.tokenType, other.tokenType) &&
            Utils.enhancedDeepEquals(this.expiresIn, other.expiresIn) &&
            Utils.enhancedDeepEquals(this.scope, other.scope);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            connectToken, tokenType, expiresIn,
            scope);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DeviceStartResponse.class,
                "connectToken", connectToken,
                "tokenType", tokenType,
                "expiresIn", expiresIn,
                "scope", scope);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String connectToken;

        private DeviceStartResponseTokenType tokenType;

        private double expiresIn;

        private List<String> scope;

        private Builder() {
          // force use of static builder() method
        }

        public Builder connectToken(@Nonnull String connectToken) {
            this.connectToken = Utils.checkNotNull(connectToken, "connectToken");
            return this;
        }

        public Builder tokenType(@Nonnull DeviceStartResponseTokenType tokenType) {
            this.tokenType = Utils.checkNotNull(tokenType, "tokenType");
            return this;
        }

        public Builder expiresIn(double expiresIn) {
            this.expiresIn = expiresIn;
            return this;
        }

        public Builder scope(@Nonnull List<String> scope) {
            this.scope = Utils.checkNotNull(scope, "scope");
            return this;
        }

        public DeviceStartResponse build() {
            return new DeviceStartResponse(
                connectToken, tokenType, expiresIn,
                scope);
        }

    }
}
