/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class GbgError {

    @JsonProperty("code")
    private String code;


    @JsonProperty("name")
    private String name;


    @JsonProperty("problem")
    private String problem;


    @JsonProperty("action")
    private String action;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("location")
    private LocationEnum location;

    @JsonCreator
    public GbgError(
            @JsonProperty("code") @Nonnull String code,
            @JsonProperty("name") @Nonnull String name,
            @JsonProperty("problem") @Nonnull String problem,
            @JsonProperty("action") @Nonnull String action,
            @JsonProperty("location") @Nullable LocationEnum location) {
        this.code = Optional.ofNullable(code)
            .orElseThrow(() -> new IllegalArgumentException("code cannot be null"));
        this.name = Optional.ofNullable(name)
            .orElseThrow(() -> new IllegalArgumentException("name cannot be null"));
        this.problem = Optional.ofNullable(problem)
            .orElseThrow(() -> new IllegalArgumentException("problem cannot be null"));
        this.action = Optional.ofNullable(action)
            .orElseThrow(() -> new IllegalArgumentException("action cannot be null"));
        this.location = location;
    }
    
    public GbgError(
            @Nonnull String code,
            @Nonnull String name,
            @Nonnull String problem,
            @Nonnull String action) {
        this(code, name, problem,
            action, null);
    }

    public String code() {
        return this.code;
    }

    public String name() {
        return this.name;
    }

    public String problem() {
        return this.problem;
    }

    public String action() {
        return this.action;
    }

    public Optional<LocationEnum> location() {
        return Optional.ofNullable(this.location);
    }

    public static Builder builder() {
        return new Builder();
    }


    public GbgError withCode(@Nonnull String code) {
        this.code = Utils.checkNotNull(code, "code");
        return this;
    }


    public GbgError withName(@Nonnull String name) {
        this.name = Utils.checkNotNull(name, "name");
        return this;
    }


    public GbgError withProblem(@Nonnull String problem) {
        this.problem = Utils.checkNotNull(problem, "problem");
        return this;
    }


    public GbgError withAction(@Nonnull String action) {
        this.action = Utils.checkNotNull(action, "action");
        return this;
    }


    public GbgError withLocation(@Nullable LocationEnum location) {
        this.location = location;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GbgError other = (GbgError) o;
        return 
            Utils.enhancedDeepEquals(this.code, other.code) &&
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.problem, other.problem) &&
            Utils.enhancedDeepEquals(this.action, other.action) &&
            Utils.enhancedDeepEquals(this.location, other.location);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            code, name, problem,
            action, location);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GbgError.class,
                "code", code,
                "name", name,
                "problem", problem,
                "action", action,
                "location", location);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String code;

        private String name;

        private String problem;

        private String action;

        private LocationEnum location;

        private Builder() {
          // force use of static builder() method
        }

        public Builder code(@Nonnull String code) {
            this.code = Utils.checkNotNull(code, "code");
            return this;
        }

        public Builder name(@Nonnull String name) {
            this.name = Utils.checkNotNull(name, "name");
            return this;
        }

        public Builder problem(@Nonnull String problem) {
            this.problem = Utils.checkNotNull(problem, "problem");
            return this;
        }

        public Builder action(@Nonnull String action) {
            this.action = Utils.checkNotNull(action, "action");
            return this;
        }

        public Builder location(@Nullable LocationEnum location) {
            this.location = location;
            return this;
        }

        public GbgError build() {
            return new GbgError(
                code, name, problem,
                action, location);
        }

    }
}
