/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
public class LocationEnum {

    public static final LocationEnum PATH = new LocationEnum("Path");
    public static final LocationEnum AUTHORIZATION = new LocationEnum("Authorization");
    public static final LocationEnum HEADER = new LocationEnum("Header");
    public static final LocationEnum QUERY_STRING = new LocationEnum("Query String");
    public static final LocationEnum REQUEST = new LocationEnum("Request");
    public static final LocationEnum BODY = new LocationEnum("Body");
    public static final LocationEnum SERVICE = new LocationEnum("Service");
    public static final LocationEnum FLOW = new LocationEnum("Flow");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, LocationEnum> values = createValuesMap();
    private static final Map<String, LocationEnumEnum> enums = createEnumsMap();

    private final String value;

    private LocationEnum(String value) {
        this.value = value;
    }

    /**
     * Returns a LocationEnum with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as LocationEnum
     */ 
    @JsonCreator
    public static LocationEnum of(String value) {
        synchronized (LocationEnum.class) {
            return values.computeIfAbsent(value, v -> new LocationEnum(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<LocationEnumEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        LocationEnum other = (LocationEnum) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "LocationEnum [value=" + value + "]";
    }

    // return an array just like an enum
    public static LocationEnum[] values() {
        synchronized (LocationEnum.class) {
            return values.values().toArray(new LocationEnum[] {});
        }
    }

    private static final Map<String, LocationEnum> createValuesMap() {
        Map<String, LocationEnum> map = new LinkedHashMap<>();
        map.put("Path", PATH);
        map.put("Authorization", AUTHORIZATION);
        map.put("Header", HEADER);
        map.put("Query String", QUERY_STRING);
        map.put("Request", REQUEST);
        map.put("Body", BODY);
        map.put("Service", SERVICE);
        map.put("Flow", FLOW);
        return map;
    }

    private static final Map<String, LocationEnumEnum> createEnumsMap() {
        Map<String, LocationEnumEnum> map = new HashMap<>();
        map.put("Path", LocationEnumEnum.PATH);
        map.put("Authorization", LocationEnumEnum.AUTHORIZATION);
        map.put("Header", LocationEnumEnum.HEADER);
        map.put("Query String", LocationEnumEnum.QUERY_STRING);
        map.put("Request", LocationEnumEnum.REQUEST);
        map.put("Body", LocationEnumEnum.BODY);
        map.put("Service", LocationEnumEnum.SERVICE);
        map.put("Flow", LocationEnumEnum.FLOW);
        return map;
    }
    
    
    public enum LocationEnumEnum {

        PATH("Path"),
        AUTHORIZATION("Authorization"),
        HEADER("Header"),
        QUERY_STRING("Query String"),
        REQUEST("Request"),
        BODY("Body"),
        SERVICE("Service"),
        FLOW("Flow"),;

        private final String value;

        private LocationEnumEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

