/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
public class SandboxScenarioTier {

    public static final SandboxScenarioTier PLATFORM = new SandboxScenarioTier("platform");
    public static final SandboxScenarioTier ORG = new SandboxScenarioTier("org");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, SandboxScenarioTier> values = createValuesMap();
    private static final Map<String, SandboxScenarioTierEnum> enums = createEnumsMap();

    private final String value;

    private SandboxScenarioTier(String value) {
        this.value = value;
    }

    /**
     * Returns a SandboxScenarioTier with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as SandboxScenarioTier
     */ 
    @JsonCreator
    public static SandboxScenarioTier of(String value) {
        synchronized (SandboxScenarioTier.class) {
            return values.computeIfAbsent(value, v -> new SandboxScenarioTier(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<SandboxScenarioTierEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        SandboxScenarioTier other = (SandboxScenarioTier) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "SandboxScenarioTier [value=" + value + "]";
    }

    // return an array just like an enum
    public static SandboxScenarioTier[] values() {
        synchronized (SandboxScenarioTier.class) {
            return values.values().toArray(new SandboxScenarioTier[] {});
        }
    }

    private static final Map<String, SandboxScenarioTier> createValuesMap() {
        Map<String, SandboxScenarioTier> map = new LinkedHashMap<>();
        map.put("platform", PLATFORM);
        map.put("org", ORG);
        return map;
    }

    private static final Map<String, SandboxScenarioTierEnum> createEnumsMap() {
        Map<String, SandboxScenarioTierEnum> map = new HashMap<>();
        map.put("platform", SandboxScenarioTierEnum.PLATFORM);
        map.put("org", SandboxScenarioTierEnum.ORG);
        return map;
    }
    
    
    public enum SandboxScenarioTierEnum {

        PLATFORM("platform"),
        ORG("org"),;

        private final String value;

        private SandboxScenarioTierEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

