/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.Map;
import java.util.Optional;


public class SandboxScenario {

    @JsonProperty("name")
    private String name;


    @JsonProperty("journeyId")
    private String journeyId;


    @JsonProperty("tier")
    private SandboxScenarioTier tier;


    @JsonProperty("data")
    private Map<String, Object> data;

    /**
     * When the scenario was last saved (ISO 8601).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("lastModifiedTime")
    private OffsetDateTime lastModifiedTime;

    /**
     * Principal (JWT sub) who last saved the scenario.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("lastModifiedBy")
    private String lastModifiedBy;

    @JsonCreator
    public SandboxScenario(
            @JsonProperty("name") @Nonnull String name,
            @JsonProperty("journeyId") @Nonnull String journeyId,
            @JsonProperty("tier") @Nonnull SandboxScenarioTier tier,
            @JsonProperty("data") @Nonnull Map<String, Object> data,
            @JsonProperty("lastModifiedTime") @Nullable OffsetDateTime lastModifiedTime,
            @JsonProperty("lastModifiedBy") @Nullable String lastModifiedBy) {
        data = Utils.emptyMapIfNull(data);
        this.name = Optional.ofNullable(name)
            .orElseThrow(() -> new IllegalArgumentException("name cannot be null"));
        this.journeyId = Optional.ofNullable(journeyId)
            .orElseThrow(() -> new IllegalArgumentException("journeyId cannot be null"));
        this.tier = Optional.ofNullable(tier)
            .orElseThrow(() -> new IllegalArgumentException("tier cannot be null"));
        this.data = Optional.ofNullable(data)
            .orElseThrow(() -> new IllegalArgumentException("data cannot be null"));
        this.lastModifiedTime = lastModifiedTime;
        this.lastModifiedBy = lastModifiedBy;
    }
    
    public SandboxScenario(
            @Nonnull String name,
            @Nonnull String journeyId,
            @Nonnull SandboxScenarioTier tier,
            @Nonnull Map<String, Object> data) {
        this(name, journeyId, tier,
            data, null, null);
    }

    public String name() {
        return this.name;
    }

    public String journeyId() {
        return this.journeyId;
    }

    public SandboxScenarioTier tier() {
        return this.tier;
    }

    public Map<String, Object> data() {
        return this.data;
    }

    /**
     * When the scenario was last saved (ISO 8601).
     */
    public Optional<OffsetDateTime> lastModifiedTime() {
        return Optional.ofNullable(this.lastModifiedTime);
    }

    /**
     * Principal (JWT sub) who last saved the scenario.
     */
    public Optional<String> lastModifiedBy() {
        return Optional.ofNullable(this.lastModifiedBy);
    }

    public static Builder builder() {
        return new Builder();
    }


    public SandboxScenario withName(@Nonnull String name) {
        this.name = Utils.checkNotNull(name, "name");
        return this;
    }


    public SandboxScenario withJourneyId(@Nonnull String journeyId) {
        this.journeyId = Utils.checkNotNull(journeyId, "journeyId");
        return this;
    }


    public SandboxScenario withTier(@Nonnull SandboxScenarioTier tier) {
        this.tier = Utils.checkNotNull(tier, "tier");
        return this;
    }


    public SandboxScenario withData(@Nonnull Map<String, Object> data) {
        this.data = Utils.checkNotNull(data, "data");
        return this;
    }


    /**
     * When the scenario was last saved (ISO 8601).
     */
    public SandboxScenario withLastModifiedTime(@Nullable OffsetDateTime lastModifiedTime) {
        this.lastModifiedTime = lastModifiedTime;
        return this;
    }


    /**
     * Principal (JWT sub) who last saved the scenario.
     */
    public SandboxScenario withLastModifiedBy(@Nullable String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SandboxScenario other = (SandboxScenario) o;
        return 
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.journeyId, other.journeyId) &&
            Utils.enhancedDeepEquals(this.tier, other.tier) &&
            Utils.enhancedDeepEquals(this.data, other.data) &&
            Utils.enhancedDeepEquals(this.lastModifiedTime, other.lastModifiedTime) &&
            Utils.enhancedDeepEquals(this.lastModifiedBy, other.lastModifiedBy);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            name, journeyId, tier,
            data, lastModifiedTime, lastModifiedBy);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SandboxScenario.class,
                "name", name,
                "journeyId", journeyId,
                "tier", tier,
                "data", data,
                "lastModifiedTime", lastModifiedTime,
                "lastModifiedBy", lastModifiedBy);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String name;

        private String journeyId;

        private SandboxScenarioTier tier;

        private Map<String, Object> data;

        private OffsetDateTime lastModifiedTime;

        private String lastModifiedBy;

        private Builder() {
          // force use of static builder() method
        }

        public Builder name(@Nonnull String name) {
            this.name = Utils.checkNotNull(name, "name");
            return this;
        }

        public Builder journeyId(@Nonnull String journeyId) {
            this.journeyId = Utils.checkNotNull(journeyId, "journeyId");
            return this;
        }

        public Builder tier(@Nonnull SandboxScenarioTier tier) {
            this.tier = Utils.checkNotNull(tier, "tier");
            return this;
        }

        public Builder data(@Nonnull Map<String, Object> data) {
            this.data = Utils.checkNotNull(data, "data");
            return this;
        }

        /**
         * When the scenario was last saved (ISO 8601).
         */
        public Builder lastModifiedTime(@Nullable OffsetDateTime lastModifiedTime) {
            this.lastModifiedTime = lastModifiedTime;
            return this;
        }

        /**
         * Principal (JWT sub) who last saved the scenario.
         */
        public Builder lastModifiedBy(@Nullable String lastModifiedBy) {
            this.lastModifiedBy = lastModifiedBy;
            return this;
        }

        public SandboxScenario build() {
            return new SandboxScenario(
                name, journeyId, tier,
                data, lastModifiedTime, lastModifiedBy);
        }

    }
}
