/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;


public class SchemaFetchResponse {

    @JsonProperty("deliveryId")
    private String deliveryId;


    @JsonProperty("resolvedVersion")
    private String resolvedVersion;


    @JsonProperty("schemas")
    private List<Schema> schemas;

    @JsonCreator
    public SchemaFetchResponse(
            @JsonProperty("deliveryId") @Nonnull String deliveryId,
            @JsonProperty("resolvedVersion") @Nonnull String resolvedVersion,
            @JsonProperty("schemas") @Nonnull List<Schema> schemas) {
        this.deliveryId = Optional.ofNullable(deliveryId)
            .orElseThrow(() -> new IllegalArgumentException("deliveryId cannot be null"));
        this.resolvedVersion = Optional.ofNullable(resolvedVersion)
            .orElseThrow(() -> new IllegalArgumentException("resolvedVersion cannot be null"));
        this.schemas = Optional.ofNullable(schemas)
            .orElseThrow(() -> new IllegalArgumentException("schemas cannot be null"));
    }

    public String deliveryId() {
        return this.deliveryId;
    }

    public String resolvedVersion() {
        return this.resolvedVersion;
    }

    public List<Schema> schemas() {
        return this.schemas;
    }

    public static Builder builder() {
        return new Builder();
    }


    public SchemaFetchResponse withDeliveryId(@Nonnull String deliveryId) {
        this.deliveryId = Utils.checkNotNull(deliveryId, "deliveryId");
        return this;
    }


    public SchemaFetchResponse withResolvedVersion(@Nonnull String resolvedVersion) {
        this.resolvedVersion = Utils.checkNotNull(resolvedVersion, "resolvedVersion");
        return this;
    }


    public SchemaFetchResponse withSchemas(@Nonnull List<Schema> schemas) {
        this.schemas = Utils.checkNotNull(schemas, "schemas");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SchemaFetchResponse other = (SchemaFetchResponse) o;
        return 
            Utils.enhancedDeepEquals(this.deliveryId, other.deliveryId) &&
            Utils.enhancedDeepEquals(this.resolvedVersion, other.resolvedVersion) &&
            Utils.enhancedDeepEquals(this.schemas, other.schemas);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            deliveryId, resolvedVersion, schemas);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SchemaFetchResponse.class,
                "deliveryId", deliveryId,
                "resolvedVersion", resolvedVersion,
                "schemas", schemas);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String deliveryId;

        private String resolvedVersion;

        private List<Schema> schemas;

        private Builder() {
          // force use of static builder() method
        }

        public Builder deliveryId(@Nonnull String deliveryId) {
            this.deliveryId = Utils.checkNotNull(deliveryId, "deliveryId");
            return this;
        }

        public Builder resolvedVersion(@Nonnull String resolvedVersion) {
            this.resolvedVersion = Utils.checkNotNull(resolvedVersion, "resolvedVersion");
            return this;
        }

        public Builder schemas(@Nonnull List<Schema> schemas) {
            this.schemas = Utils.checkNotNull(schemas, "schemas");
            return this;
        }

        public SchemaFetchResponse build() {
            return new SchemaFetchResponse(
                deliveryId, resolvedVersion, schemas);
        }

    }
}
