/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;


public class SlimIdentity {
    /**
     * Title of an individual such as Mr, Mrs, Dr, Sir
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("title")
    private String title;

    /**
     * A person's name used by their collegues and friends to address them
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("firstName")
    private String firstName;

    /**
     * Any other registered names used by the individual, not aliases
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("middleNames")
    private List<String> middleNames;

    /**
     * Any family names for the individual
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("lastNames")
    private List<String> lastNames;

    /**
     * Any family names for the individual
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("lastNamesAtBirth")
    private List<String> lastNamesAtBirth;

    /**
     * Specified in year, month and day separated by -. For example 2017-1-1 or 2017-01-01 which conforms
     * to ISO 8601
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("dateOfBirth")
    private String dateOfBirth;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("gender")
    private String gender;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("currentAddress")
    private CurrentAddress currentAddress;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("placeOfBirth")
    private PlaceOfBirth placeOfBirth;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("idNumbers")
    private List<IdNumber> idNumbers;

    @JsonCreator
    public SlimIdentity(
            @JsonProperty("title") @Nullable String title,
            @JsonProperty("firstName") @Nullable String firstName,
            @JsonProperty("middleNames") @Nullable List<String> middleNames,
            @JsonProperty("lastNames") @Nullable List<String> lastNames,
            @JsonProperty("lastNamesAtBirth") @Nullable List<String> lastNamesAtBirth,
            @JsonProperty("dateOfBirth") @Nullable String dateOfBirth,
            @JsonProperty("gender") @Nullable String gender,
            @JsonProperty("currentAddress") @Nullable CurrentAddress currentAddress,
            @JsonProperty("placeOfBirth") @Nullable PlaceOfBirth placeOfBirth,
            @JsonProperty("idNumbers") @Nullable List<IdNumber> idNumbers) {
        this.title = title;
        this.firstName = firstName;
        this.middleNames = middleNames;
        this.lastNames = lastNames;
        this.lastNamesAtBirth = lastNamesAtBirth;
        this.dateOfBirth = dateOfBirth;
        this.gender = gender;
        this.currentAddress = currentAddress;
        this.placeOfBirth = placeOfBirth;
        this.idNumbers = idNumbers;
    }
    
    public SlimIdentity() {
        this(null, null, null,
            null, null, null,
            null, null, null,
            null);
    }

    /**
     * Title of an individual such as Mr, Mrs, Dr, Sir
     */
    public Optional<String> title() {
        return Optional.ofNullable(this.title);
    }

    /**
     * A person's name used by their collegues and friends to address them
     */
    public Optional<String> firstName() {
        return Optional.ofNullable(this.firstName);
    }

    /**
     * Any other registered names used by the individual, not aliases
     */
    public Optional<List<String>> middleNames() {
        return Optional.ofNullable(this.middleNames);
    }

    /**
     * Any family names for the individual
     */
    public Optional<List<String>> lastNames() {
        return Optional.ofNullable(this.lastNames);
    }

    /**
     * Any family names for the individual
     */
    public Optional<List<String>> lastNamesAtBirth() {
        return Optional.ofNullable(this.lastNamesAtBirth);
    }

    /**
     * Specified in year, month and day separated by -. For example 2017-1-1 or 2017-01-01 which conforms
     * to ISO 8601
     */
    public Optional<String> dateOfBirth() {
        return Optional.ofNullable(this.dateOfBirth);
    }

    public Optional<String> gender() {
        return Optional.ofNullable(this.gender);
    }

    public Optional<CurrentAddress> currentAddress() {
        return Optional.ofNullable(this.currentAddress);
    }

    public Optional<PlaceOfBirth> placeOfBirth() {
        return Optional.ofNullable(this.placeOfBirth);
    }

    public Optional<List<IdNumber>> idNumbers() {
        return Optional.ofNullable(this.idNumbers);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Title of an individual such as Mr, Mrs, Dr, Sir
     */
    public SlimIdentity withTitle(@Nullable String title) {
        this.title = title;
        return this;
    }


    /**
     * A person's name used by their collegues and friends to address them
     */
    public SlimIdentity withFirstName(@Nullable String firstName) {
        this.firstName = firstName;
        return this;
    }


    /**
     * Any other registered names used by the individual, not aliases
     */
    public SlimIdentity withMiddleNames(@Nullable List<String> middleNames) {
        this.middleNames = middleNames;
        return this;
    }


    /**
     * Any family names for the individual
     */
    public SlimIdentity withLastNames(@Nullable List<String> lastNames) {
        this.lastNames = lastNames;
        return this;
    }


    /**
     * Any family names for the individual
     */
    public SlimIdentity withLastNamesAtBirth(@Nullable List<String> lastNamesAtBirth) {
        this.lastNamesAtBirth = lastNamesAtBirth;
        return this;
    }


    /**
     * Specified in year, month and day separated by -. For example 2017-1-1 or 2017-01-01 which conforms
     * to ISO 8601
     */
    public SlimIdentity withDateOfBirth(@Nullable String dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
        return this;
    }


    public SlimIdentity withGender(@Nullable String gender) {
        this.gender = gender;
        return this;
    }


    public SlimIdentity withCurrentAddress(@Nullable CurrentAddress currentAddress) {
        this.currentAddress = currentAddress;
        return this;
    }


    public SlimIdentity withPlaceOfBirth(@Nullable PlaceOfBirth placeOfBirth) {
        this.placeOfBirth = placeOfBirth;
        return this;
    }


    public SlimIdentity withIdNumbers(@Nullable List<IdNumber> idNumbers) {
        this.idNumbers = idNumbers;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SlimIdentity other = (SlimIdentity) o;
        return 
            Utils.enhancedDeepEquals(this.title, other.title) &&
            Utils.enhancedDeepEquals(this.firstName, other.firstName) &&
            Utils.enhancedDeepEquals(this.middleNames, other.middleNames) &&
            Utils.enhancedDeepEquals(this.lastNames, other.lastNames) &&
            Utils.enhancedDeepEquals(this.lastNamesAtBirth, other.lastNamesAtBirth) &&
            Utils.enhancedDeepEquals(this.dateOfBirth, other.dateOfBirth) &&
            Utils.enhancedDeepEquals(this.gender, other.gender) &&
            Utils.enhancedDeepEquals(this.currentAddress, other.currentAddress) &&
            Utils.enhancedDeepEquals(this.placeOfBirth, other.placeOfBirth) &&
            Utils.enhancedDeepEquals(this.idNumbers, other.idNumbers);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            title, firstName, middleNames,
            lastNames, lastNamesAtBirth, dateOfBirth,
            gender, currentAddress, placeOfBirth,
            idNumbers);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SlimIdentity.class,
                "title", title,
                "firstName", firstName,
                "middleNames", middleNames,
                "lastNames", lastNames,
                "lastNamesAtBirth", lastNamesAtBirth,
                "dateOfBirth", dateOfBirth,
                "gender", gender,
                "currentAddress", currentAddress,
                "placeOfBirth", placeOfBirth,
                "idNumbers", idNumbers);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String title;

        private String firstName;

        private List<String> middleNames;

        private List<String> lastNames;

        private List<String> lastNamesAtBirth;

        private String dateOfBirth;

        private String gender;

        private CurrentAddress currentAddress;

        private PlaceOfBirth placeOfBirth;

        private List<IdNumber> idNumbers;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Title of an individual such as Mr, Mrs, Dr, Sir
         */
        public Builder title(@Nullable String title) {
            this.title = title;
            return this;
        }

        /**
         * A person's name used by their collegues and friends to address them
         */
        public Builder firstName(@Nullable String firstName) {
            this.firstName = firstName;
            return this;
        }

        /**
         * Any other registered names used by the individual, not aliases
         */
        public Builder middleNames(@Nullable List<String> middleNames) {
            this.middleNames = middleNames;
            return this;
        }

        /**
         * Any family names for the individual
         */
        public Builder lastNames(@Nullable List<String> lastNames) {
            this.lastNames = lastNames;
            return this;
        }

        /**
         * Any family names for the individual
         */
        public Builder lastNamesAtBirth(@Nullable List<String> lastNamesAtBirth) {
            this.lastNamesAtBirth = lastNamesAtBirth;
            return this;
        }

        /**
         * Specified in year, month and day separated by -. For example 2017-1-1 or 2017-01-01 which conforms
         * to ISO 8601
         */
        public Builder dateOfBirth(@Nullable String dateOfBirth) {
            this.dateOfBirth = dateOfBirth;
            return this;
        }

        public Builder gender(@Nullable String gender) {
            this.gender = gender;
            return this;
        }

        public Builder currentAddress(@Nullable CurrentAddress currentAddress) {
            this.currentAddress = currentAddress;
            return this;
        }

        public Builder placeOfBirth(@Nullable PlaceOfBirth placeOfBirth) {
            this.placeOfBirth = placeOfBirth;
            return this;
        }

        public Builder idNumbers(@Nullable List<IdNumber> idNumbers) {
            this.idNumbers = idNumbers;
            return this;
        }

        public SlimIdentity build() {
            return new SlimIdentity(
                title, firstName, middleNames,
                lastNames, lastNamesAtBirth, dateOfBirth,
                gender, currentAddress, placeOfBirth,
                idNumbers);
        }

    }
}
