/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;


public class SlimStateFetchResponse {

    @JsonProperty("instanceId")
    private String instanceId;


    @JsonProperty("status")
    private SlimStateFetchResponseStatus status;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("journey")
    private SlimJourney journey;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("steps")
    private List<SlimStep> steps;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("result")
    private SlimResult result;

    @JsonCreator
    public SlimStateFetchResponse(
            @JsonProperty("instanceId") @Nonnull String instanceId,
            @JsonProperty("status") @Nonnull SlimStateFetchResponseStatus status,
            @JsonProperty("journey") @Nullable SlimJourney journey,
            @JsonProperty("steps") @Nullable List<SlimStep> steps,
            @JsonProperty("result") @Nullable SlimResult result) {
        this.instanceId = Optional.ofNullable(instanceId)
            .orElseThrow(() -> new IllegalArgumentException("instanceId cannot be null"));
        this.status = Optional.ofNullable(status)
            .orElseThrow(() -> new IllegalArgumentException("status cannot be null"));
        this.journey = journey;
        this.steps = steps;
        this.result = result;
    }
    
    public SlimStateFetchResponse(
            @Nonnull String instanceId,
            @Nonnull SlimStateFetchResponseStatus status) {
        this(instanceId, status, null,
            null, null);
    }

    public String instanceId() {
        return this.instanceId;
    }

    public SlimStateFetchResponseStatus status() {
        return this.status;
    }

    public Optional<SlimJourney> journey() {
        return Optional.ofNullable(this.journey);
    }

    public Optional<List<SlimStep>> steps() {
        return Optional.ofNullable(this.steps);
    }

    public Optional<SlimResult> result() {
        return Optional.ofNullable(this.result);
    }

    public static Builder builder() {
        return new Builder();
    }


    public SlimStateFetchResponse withInstanceId(@Nonnull String instanceId) {
        this.instanceId = Utils.checkNotNull(instanceId, "instanceId");
        return this;
    }


    public SlimStateFetchResponse withStatus(@Nonnull SlimStateFetchResponseStatus status) {
        this.status = Utils.checkNotNull(status, "status");
        return this;
    }


    public SlimStateFetchResponse withJourney(@Nullable SlimJourney journey) {
        this.journey = journey;
        return this;
    }


    public SlimStateFetchResponse withSteps(@Nullable List<SlimStep> steps) {
        this.steps = steps;
        return this;
    }


    public SlimStateFetchResponse withResult(@Nullable SlimResult result) {
        this.result = result;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SlimStateFetchResponse other = (SlimStateFetchResponse) o;
        return 
            Utils.enhancedDeepEquals(this.instanceId, other.instanceId) &&
            Utils.enhancedDeepEquals(this.status, other.status) &&
            Utils.enhancedDeepEquals(this.journey, other.journey) &&
            Utils.enhancedDeepEquals(this.steps, other.steps) &&
            Utils.enhancedDeepEquals(this.result, other.result);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            instanceId, status, journey,
            steps, result);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SlimStateFetchResponse.class,
                "instanceId", instanceId,
                "status", status,
                "journey", journey,
                "steps", steps,
                "result", result);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String instanceId;

        private SlimStateFetchResponseStatus status;

        private SlimJourney journey;

        private List<SlimStep> steps;

        private SlimResult result;

        private Builder() {
          // force use of static builder() method
        }

        public Builder instanceId(@Nonnull String instanceId) {
            this.instanceId = Utils.checkNotNull(instanceId, "instanceId");
            return this;
        }

        public Builder status(@Nonnull SlimStateFetchResponseStatus status) {
            this.status = Utils.checkNotNull(status, "status");
            return this;
        }

        public Builder journey(@Nullable SlimJourney journey) {
            this.journey = journey;
            return this;
        }

        public Builder steps(@Nullable List<SlimStep> steps) {
            this.steps = steps;
            return this;
        }

        public Builder result(@Nullable SlimResult result) {
            this.result = result;
            return this;
        }

        public SlimStateFetchResponse build() {
            return new SlimStateFetchResponse(
                instanceId, status, journey,
                steps, result);
        }

    }
}
