/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gbg.gocore.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Optional;


public class SlimInteractionFetchResponse {

    @JsonProperty("instanceId")
    private String instanceId;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("interactionId")
    private String interactionId;


    @JsonProperty("journey")
    private SlimInteractionFetchResponseJourney journey;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("interaction")
    private Map<String, Object> interaction;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("processing")
    private Boolean processing;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("outstanding")
    private List<String> outstanding;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("outstandingGroups")
    private List<SlimInteractionFetchResponseOutstandingGroup> outstandingGroups;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("instructions")
    private List<String> instructions;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("result")
    private SlimResult result;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("joinedDevice")
    private SlimInteractionFetchResponseJoinedDevice joinedDevice;

    @JsonCreator
    public SlimInteractionFetchResponse(
            @JsonProperty("instanceId") @Nonnull String instanceId,
            @JsonProperty("interactionId") @Nullable String interactionId,
            @JsonProperty("journey") @Nonnull SlimInteractionFetchResponseJourney journey,
            @JsonProperty("interaction") @Nullable Map<String, Object> interaction,
            @JsonProperty("processing") @Nullable Boolean processing,
            @JsonProperty("outstanding") @Nullable List<String> outstanding,
            @JsonProperty("outstandingGroups") @Nullable List<SlimInteractionFetchResponseOutstandingGroup> outstandingGroups,
            @JsonProperty("instructions") @Nullable List<String> instructions,
            @JsonProperty("result") @Nullable SlimResult result,
            @JsonProperty("joinedDevice") @Nullable SlimInteractionFetchResponseJoinedDevice joinedDevice) {
        this.instanceId = Optional.ofNullable(instanceId)
            .orElseThrow(() -> new IllegalArgumentException("instanceId cannot be null"));
        this.interactionId = interactionId;
        this.journey = Optional.ofNullable(journey)
            .orElseThrow(() -> new IllegalArgumentException("journey cannot be null"));
        this.interaction = interaction;
        this.processing = processing;
        this.outstanding = outstanding;
        this.outstandingGroups = outstandingGroups;
        this.instructions = instructions;
        this.result = result;
        this.joinedDevice = joinedDevice;
    }
    
    public SlimInteractionFetchResponse(
            @Nonnull String instanceId,
            @Nonnull SlimInteractionFetchResponseJourney journey) {
        this(instanceId, null, journey,
            null, null, null,
            null, null, null,
            null);
    }

    public String instanceId() {
        return this.instanceId;
    }

    public Optional<String> interactionId() {
        return Optional.ofNullable(this.interactionId);
    }

    public SlimInteractionFetchResponseJourney journey() {
        return this.journey;
    }

    public Optional<Map<String, Object>> interaction() {
        return Optional.ofNullable(this.interaction);
    }

    public Optional<Boolean> processing() {
        return Optional.ofNullable(this.processing);
    }

    public Optional<List<String>> outstanding() {
        return Optional.ofNullable(this.outstanding);
    }

    public Optional<List<SlimInteractionFetchResponseOutstandingGroup>> outstandingGroups() {
        return Optional.ofNullable(this.outstandingGroups);
    }

    public Optional<List<String>> instructions() {
        return Optional.ofNullable(this.instructions);
    }

    public Optional<SlimResult> result() {
        return Optional.ofNullable(this.result);
    }

    public Optional<SlimInteractionFetchResponseJoinedDevice> joinedDevice() {
        return Optional.ofNullable(this.joinedDevice);
    }

    public static Builder builder() {
        return new Builder();
    }


    public SlimInteractionFetchResponse withInstanceId(@Nonnull String instanceId) {
        this.instanceId = Utils.checkNotNull(instanceId, "instanceId");
        return this;
    }


    public SlimInteractionFetchResponse withInteractionId(@Nullable String interactionId) {
        this.interactionId = interactionId;
        return this;
    }


    public SlimInteractionFetchResponse withJourney(@Nonnull SlimInteractionFetchResponseJourney journey) {
        this.journey = Utils.checkNotNull(journey, "journey");
        return this;
    }


    public SlimInteractionFetchResponse withInteraction(@Nullable Map<String, Object> interaction) {
        this.interaction = interaction;
        return this;
    }


    public SlimInteractionFetchResponse withProcessing(@Nullable Boolean processing) {
        this.processing = processing;
        return this;
    }


    public SlimInteractionFetchResponse withOutstanding(@Nullable List<String> outstanding) {
        this.outstanding = outstanding;
        return this;
    }


    public SlimInteractionFetchResponse withOutstandingGroups(@Nullable List<SlimInteractionFetchResponseOutstandingGroup> outstandingGroups) {
        this.outstandingGroups = outstandingGroups;
        return this;
    }


    public SlimInteractionFetchResponse withInstructions(@Nullable List<String> instructions) {
        this.instructions = instructions;
        return this;
    }


    public SlimInteractionFetchResponse withResult(@Nullable SlimResult result) {
        this.result = result;
        return this;
    }


    public SlimInteractionFetchResponse withJoinedDevice(@Nullable SlimInteractionFetchResponseJoinedDevice joinedDevice) {
        this.joinedDevice = joinedDevice;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SlimInteractionFetchResponse other = (SlimInteractionFetchResponse) o;
        return 
            Utils.enhancedDeepEquals(this.instanceId, other.instanceId) &&
            Utils.enhancedDeepEquals(this.interactionId, other.interactionId) &&
            Utils.enhancedDeepEquals(this.journey, other.journey) &&
            Utils.enhancedDeepEquals(this.interaction, other.interaction) &&
            Utils.enhancedDeepEquals(this.processing, other.processing) &&
            Utils.enhancedDeepEquals(this.outstanding, other.outstanding) &&
            Utils.enhancedDeepEquals(this.outstandingGroups, other.outstandingGroups) &&
            Utils.enhancedDeepEquals(this.instructions, other.instructions) &&
            Utils.enhancedDeepEquals(this.result, other.result) &&
            Utils.enhancedDeepEquals(this.joinedDevice, other.joinedDevice);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            instanceId, interactionId, journey,
            interaction, processing, outstanding,
            outstandingGroups, instructions, result,
            joinedDevice);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SlimInteractionFetchResponse.class,
                "instanceId", instanceId,
                "interactionId", interactionId,
                "journey", journey,
                "interaction", interaction,
                "processing", processing,
                "outstanding", outstanding,
                "outstandingGroups", outstandingGroups,
                "instructions", instructions,
                "result", result,
                "joinedDevice", joinedDevice);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String instanceId;

        private String interactionId;

        private SlimInteractionFetchResponseJourney journey;

        private Map<String, Object> interaction;

        private Boolean processing;

        private List<String> outstanding;

        private List<SlimInteractionFetchResponseOutstandingGroup> outstandingGroups;

        private List<String> instructions;

        private SlimResult result;

        private SlimInteractionFetchResponseJoinedDevice joinedDevice;

        private Builder() {
          // force use of static builder() method
        }

        public Builder instanceId(@Nonnull String instanceId) {
            this.instanceId = Utils.checkNotNull(instanceId, "instanceId");
            return this;
        }

        public Builder interactionId(@Nullable String interactionId) {
            this.interactionId = interactionId;
            return this;
        }

        public Builder journey(@Nonnull SlimInteractionFetchResponseJourney journey) {
            this.journey = Utils.checkNotNull(journey, "journey");
            return this;
        }

        public Builder interaction(@Nullable Map<String, Object> interaction) {
            this.interaction = interaction;
            return this;
        }

        public Builder processing(@Nullable Boolean processing) {
            this.processing = processing;
            return this;
        }

        public Builder outstanding(@Nullable List<String> outstanding) {
            this.outstanding = outstanding;
            return this;
        }

        public Builder outstandingGroups(@Nullable List<SlimInteractionFetchResponseOutstandingGroup> outstandingGroups) {
            this.outstandingGroups = outstandingGroups;
            return this;
        }

        public Builder instructions(@Nullable List<String> instructions) {
            this.instructions = instructions;
            return this;
        }

        public Builder result(@Nullable SlimResult result) {
            this.result = result;
            return this;
        }

        public Builder joinedDevice(@Nullable SlimInteractionFetchResponseJoinedDevice joinedDevice) {
            this.joinedDevice = joinedDevice;
            return this;
        }

        public SlimInteractionFetchResponse build() {
            return new SlimInteractionFetchResponse(
                instanceId, interactionId, journey,
                interaction, processing, outstanding,
                outstandingGroups, instructions, result,
                joinedDevice);
        }

    }
}
