/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore;

import static com.gbg.gocore.operations.Operations.AsyncRequestOperation;

import com.gbg.gocore.models.operations.CreateHandoffTokenRequest;
import com.gbg.gocore.models.operations.CreateHandoffTokenSecurity;
import com.gbg.gocore.models.operations.DeleteInstanceRequest;
import com.gbg.gocore.models.operations.async.CreateHandoffTokenRequestBuilder;
import com.gbg.gocore.models.operations.async.CreateHandoffTokenResponse;
import com.gbg.gocore.models.operations.async.DeleteInstanceRequestBuilder;
import com.gbg.gocore.models.operations.async.DeleteInstanceResponse;
import com.gbg.gocore.operations.CreateHandoffToken;
import com.gbg.gocore.operations.DeleteInstance;
import com.gbg.gocore.utils.Headers;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.concurrent.CompletableFuture;


public class AsyncInstances {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final Instances syncSDK;

    AsyncInstances(Instances syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public Instances toSync() {
        return syncSDK;
    }


    /**
     * Mint a fresh position-scoped handoff token
     * 
     * <p>Mints a fresh page-mode delivery-token + connect-secret pair pointing at the same instance, stamped
     * devicePosition=joined, so a second device can join. Device-token only, and only from the device that
     * started the journey; customer tokens and already-joined devices are rejected with 403. Returns {
     * instanceUrl, devicePosition, expiresIn }.
     * 
     * @return The async call builder
     */
    public CreateHandoffTokenRequestBuilder handoffToken() {
        return new CreateHandoffTokenRequestBuilder(sdkConfiguration);
    }

    /**
     * Mint a fresh position-scoped handoff token
     * 
     * <p>Mints a fresh page-mode delivery-token + connect-secret pair pointing at the same instance, stamped
     * devicePosition=joined, so a second device can join. Device-token only, and only from the device that
     * started the journey; customer tokens and already-joined devices are rejected with 403. Returns {
     * instanceUrl, devicePosition, expiresIn }.
     * 
     * @param security The security details to use for authentication.
     * @param instanceId 
     * @return {@code CompletableFuture<CreateHandoffTokenResponse>} - The async response
     */
    public CompletableFuture<CreateHandoffTokenResponse> handoffToken(@Nonnull CreateHandoffTokenSecurity security, @Nonnull String instanceId) {
        CreateHandoffTokenRequest request = new CreateHandoffTokenRequest(instanceId);
        AsyncRequestOperation<CreateHandoffTokenRequest, CreateHandoffTokenResponse> operation
              = new CreateHandoffToken.Async(sdkConfiguration, security, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Delete journey state
     * 
     * <p>Permanently deletes a completed journey instance (REQ-02-002).
     * 
     * <p>If set, this operation will use Security#customerAccess from the global security.
     * 
     * @return The async call builder
     */
    public DeleteInstanceRequestBuilder delete() {
        return new DeleteInstanceRequestBuilder(sdkConfiguration);
    }

    /**
     * Delete journey state
     * 
     * <p>Permanently deletes a completed journey instance (REQ-02-002).
     * 
     * <p>If set, this operation will use Security#customerAccess from the global security.
     * 
     * @return {@code CompletableFuture<DeleteInstanceResponse>} - The async response
     */
    public CompletableFuture<DeleteInstanceResponse> deleteDirect() {
        return delete(null);
    }

    /**
     * Delete journey state
     * 
     * <p>Permanently deletes a completed journey instance (REQ-02-002).
     * 
     * <p>If set, this operation will use Security#customerAccess from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<DeleteInstanceResponse>} - The async response
     */
    public CompletableFuture<DeleteInstanceResponse> delete(@Nullable DeleteInstanceRequest request) {
        AsyncRequestOperation<DeleteInstanceRequest, DeleteInstanceResponse> operation
              = new DeleteInstance.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
