/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gbg.gocore;

import static com.gbg.gocore.operations.Operations.RequestOperation;
import static com.gbg.gocore.operations.Operations.RequestlessOperation;

import com.gbg.gocore.models.operations.AddDeviceRequest;
import com.gbg.gocore.models.operations.AddDeviceRequestBuilder;
import com.gbg.gocore.models.operations.AddDeviceResponse;
import com.gbg.gocore.models.operations.DeviceConnectRequestBuilder;
import com.gbg.gocore.models.operations.DeviceConnectResponse;
import com.gbg.gocore.models.operations.DeviceRefreshRequestBuilder;
import com.gbg.gocore.models.operations.DeviceRefreshResponse;
import com.gbg.gocore.models.operations.DeviceValidateRequestBuilder;
import com.gbg.gocore.models.operations.DeviceValidateResponse;
import com.gbg.gocore.models.operations.DeviceValidateSecurity;
import com.gbg.gocore.operations.AddDevice;
import com.gbg.gocore.operations.DeviceConnect;
import com.gbg.gocore.operations.DeviceRefresh;
import com.gbg.gocore.operations.DeviceValidate;
import com.gbg.gocore.utils.Headers;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;


public class Devices {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncDevices asyncSDK;

    Devices(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncDevices(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncDevices toAsync() {
        return asyncSDK;
    }

    /**
     * Generate connect token
     * 
     * <p>Generates a one-time connect token for device onboarding.
     * 
     * <p>If set, this operation will use Security#customerAccess from the global security.
     * 
     * @return The call builder
     */
    public AddDeviceRequestBuilder add() {
        return new AddDeviceRequestBuilder(sdkConfiguration);
    }

    /**
     * Generate connect token
     * 
     * <p>Generates a one-time connect token for device onboarding.
     * 
     * <p>If set, this operation will use Security#customerAccess from the global security.
     * 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public AddDeviceResponse addDirect() {
        return add(null);
    }

    /**
     * Generate connect token
     * 
     * <p>Generates a one-time connect token for device onboarding.
     * 
     * <p>If set, this operation will use Security#customerAccess from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public AddDeviceResponse add(@Nullable AddDeviceRequest request) {
        RequestOperation<AddDeviceRequest, AddDeviceResponse> operation
              = new AddDevice.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Complete the device-onboarding handshake
     * 
     * <p>Completes the device-onboarding handshake. See partner integration guide.
     * 
     * @return The call builder
     */
    public DeviceConnectRequestBuilder connect() {
        return new DeviceConnectRequestBuilder(sdkConfiguration);
    }

    /**
     * Complete the device-onboarding handshake
     * 
     * <p>Completes the device-onboarding handshake. See partner integration guide.
     * 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public DeviceConnectResponse connectDirect() {
        RequestlessOperation<DeviceConnectResponse> operation
            = new DeviceConnect.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest());
    }

    /**
     * Renew a device session
     * 
     * <p>Renews a device session. See partner integration guide.
     * 
     * @return The call builder
     */
    public DeviceRefreshRequestBuilder refresh() {
        return new DeviceRefreshRequestBuilder(sdkConfiguration);
    }

    /**
     * Renew a device session
     * 
     * <p>Renews a device session. See partner integration guide.
     * 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public DeviceRefreshResponse refreshDirect() {
        RequestlessOperation<DeviceRefreshResponse> operation
            = new DeviceRefresh.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest());
    }

    /**
     * Validate end-user session
     * 
     * <p>Validates an end-user JWT and returns session information.
     * 
     * @return The call builder
     */
    public DeviceValidateRequestBuilder validate() {
        return new DeviceValidateRequestBuilder(sdkConfiguration);
    }

    /**
     * Validate end-user session
     * 
     * <p>Validates an end-user JWT and returns session information.
     * 
     * @param security The security details to use for authentication.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public DeviceValidateResponse validate(@Nonnull DeviceValidateSecurity security) {
        RequestlessOperation<DeviceValidateResponse> operation
            = new DeviceValidate.Sync(sdkConfiguration, security, _headers);
        return operation.handleResponse(operation.doRequest());
    }

}
