/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sandboxCreateScenario } from "../funcs/sandbox-create-scenario.js";
import { sandboxDeleteScenario } from "../funcs/sandbox-delete-scenario.js";
import { sandboxGetScenario } from "../funcs/sandbox-get-scenario.js";
import { sandboxListScenarios } from "../funcs/sandbox-list-scenarios.js";
import { sandboxPutScenario } from "../funcs/sandbox-put-scenario.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Sandbox extends ClientSDK {
  /**
   * Create a sandbox scenario on a journey
   *
   * @remarks
   * Creates an org-tier sandbox scenario belonging to the journey in the path. Returns 409 if the name is taken on that journey (the same name may exist on other journeys). The scenario is resolvable at journey-start, for runs of that journey only, via the x-gbg-scenario header. Org is taken from the token.
   */
  async createScenario(
    request: operations.CreateSandboxScenarioRequest,
    options?: RequestOptions,
  ): Promise<models.SandboxScenarioWritten> {
    return unwrapAsync(sandboxCreateScenario(
      this,
      request,
      options,
    ));
  }

  /**
   * List a journey's sandbox scenarios
   *
   * @remarks
   * Lists the org's sandbox scenarios belonging to the journey in the path — never another journey's. Pass includePlatform=true to also return read-only GBG-provided platform scenarios (available on every journey); an org scenario shadows a platform scenario of the same name.
   */
  async listScenarios(
    request: operations.ListSandboxScenariosRequest,
    options?: RequestOptions,
  ): Promise<Array<models.SandboxScenarioSummary>> {
    return unwrapAsync(sandboxListScenarios(
      this,
      request,
      options,
    ));
  }

  /**
   * Read a sandbox scenario
   *
   * @remarks
   * Reads one org-tier sandbox scenario of the journey in the path. By default does not fall back to the platform tier or to another journey, so a name that exists only at platform level, or only on another journey, returns 404. Pass includePlatform=true to fall back to the read-only GBG-provided scenario of that name; the response `tier` says which tier served it. Another journey is never consulted either way.
   */
  async getScenario(
    request: operations.GetSandboxScenarioRequest,
    options?: RequestOptions,
  ): Promise<models.SandboxScenario> {
    return unwrapAsync(sandboxGetScenario(
      this,
      request,
      options,
    ));
  }

  /**
   * Replace a sandbox scenario
   *
   * @remarks
   * Replaces an existing org-tier sandbox scenario of the journey in the path. Returns 404 if it does not exist on that journey — use POST to create. Requires UPDATE:journey; creating (POST) requires CREATE:journey, so an edit-only grant cannot mint new scenarios through this endpoint.
   */
  async putScenario(
    request: operations.PutSandboxScenarioRequest,
    options?: RequestOptions,
  ): Promise<models.SandboxScenarioWritten> {
    return unwrapAsync(sandboxPutScenario(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a sandbox scenario
   *
   * @remarks
   * Deletes an org-tier sandbox scenario of the journey in the path by archiving it: it disappears from listings and journey-start resolution, but its version history is retained and creating the same name again restores it. A platform scenario of the same name, previously shadowed by this one on this journey, becomes resolvable again at journey-start.
   */
  async deleteScenario(
    request: operations.DeleteSandboxScenarioRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(sandboxDeleteScenario(
      this,
      request,
      options,
    ));
  }
}
