/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Devices } from "./devices.js";
import { Health } from "./health.js";
import { Instances } from "./instances.js";
import { Interactions } from "./interactions.js";
import { Journeys } from "./journeys.js";
import { Tasks } from "./tasks.js";

export class Go extends ClientSDK {
  private _health?: Health;
  get health(): Health {
    return (this._health ??= new Health(this._options));
  }

  private _devices?: Devices;
  get devices(): Devices {
    return (this._devices ??= new Devices(this._options));
  }

  private _tasks?: Tasks;
  get tasks(): Tasks {
    return (this._tasks ??= new Tasks(this._options));
  }

  private _journeys?: Journeys;
  get journeys(): Journeys {
    return (this._journeys ??= new Journeys(this._options));
  }

  private _instances?: Instances;
  get instances(): Instances {
    return (this._instances ??= new Instances(this._options));
  }

  private _interactions?: Interactions;
  get interactions(): Interactions {
    return (this._interactions ??= new Interactions(this._options));
  }
}
