/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tasksGetSchema } from "../funcs/tasks-get-schema.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Tasks extends ClientSDK {
  /**
   * Fetch V1-compat task schema
   *
   * @remarks
   * V1 compatibility shim. Returns a Draft-07 JSON Schema for the active interaction of the journey identified by taskId (taskId = V2 instanceId), or { processing: true } while modules execute.
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async getSchema(
    request?: operations.GetTaskSchemaRequest | undefined,
    options?: RequestOptions,
  ): Promise<{ [k: string]: any }> {
    return unwrapAsync(tasksGetSchema(
      this,
      request,
      options,
    ));
  }
}
