/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tasksGetSchema } from "../funcs/tasks-get-schema.js";
import { tasksListSchema } from "../funcs/tasks-list-schema.js";
import { tasksList } from "../funcs/tasks-list.js";
import { tasksUpdate } from "../funcs/tasks-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Tasks extends ClientSDK {
  /**
   * Get End User Tasks
   *
   * @remarks
   * Get End User Tasks
   */
  async list(
    security: operations.GetTasksSecurity,
    request?: operations.GetTasksRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetTasksResponse> {
    return unwrapAsync(tasksList(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Put End User Data
   *
   * @remarks
   * Put End User Data
   */
  async update(
    security: operations.UpdateTaskSecurity,
    request?: operations.UpdateTaskRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.UpdateTaskResponse> {
    return unwrapAsync(tasksUpdate(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get Task Schema
   *
   * @remarks
   * Get Task Schema
   */
  async getSchema(
    request?: operations.GetTaskSchemaRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetTaskSchemaResponse> {
    return unwrapAsync(tasksGetSchema(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Tasks Schema
   *
   * @remarks
   * Get Tasks Schema
   */
  async listSchema(
    request?: operations.GetTasksSchemaRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetTasksSchemaResponse> {
    return unwrapAsync(tasksListSchema(
      this,
      request,
      options,
    ));
  }
}
