/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const AddDeviceScope = {
  Mobile: "mobile",
  Desktop: "desktop",
  Wildcard: "*",
  Any: "any",
  Unknown: "",
} as const;
export type AddDeviceScope = ClosedEnum<typeof AddDeviceScope>;

export type AddDeviceRequest = {
  /**
   * Journey Instance Id, a unique identifier for a started journey instance.
   */
  instanceId: string;
  scope?: Array<AddDeviceScope> | undefined;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const AddDeviceScope$outboundSchema: z.ZodMiniEnum<
  typeof AddDeviceScope
> = z.enum(AddDeviceScope);

/** @internal */
export type AddDeviceRequest$Outbound = {
  instanceId: string;
  scope?: Array<string> | undefined;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const AddDeviceRequest$outboundSchema: z.ZodMiniType<
  AddDeviceRequest$Outbound,
  AddDeviceRequest
> = z.catchall(
  z.object({
    instanceId: z.string(),
    scope: z.optional(z.array(AddDeviceScope$outboundSchema)),
  }),
  z.any(),
);

export function addDeviceRequestToJSON(
  addDeviceRequest: AddDeviceRequest,
): string {
  return JSON.stringify(
    AddDeviceRequest$outboundSchema.parse(addDeviceRequest),
  );
}
