/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type CreateHandoffTokenSecurity = {
  interactionAccess: string;
};

export type CreateHandoffTokenRequest = {
  instanceId: string;
};

/** @internal */
export type CreateHandoffTokenSecurity$Outbound = {
  InteractionAccess: string;
};

/** @internal */
export const CreateHandoffTokenSecurity$outboundSchema: z.ZodMiniType<
  CreateHandoffTokenSecurity$Outbound,
  CreateHandoffTokenSecurity
> = z.pipe(
  z.object({
    interactionAccess: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      interactionAccess: "InteractionAccess",
    });
  }),
);

export function createHandoffTokenSecurityToJSON(
  createHandoffTokenSecurity: CreateHandoffTokenSecurity,
): string {
  return JSON.stringify(
    CreateHandoffTokenSecurity$outboundSchema.parse(createHandoffTokenSecurity),
  );
}

/** @internal */
export type CreateHandoffTokenRequest$Outbound = {
  instanceId: string;
};

/** @internal */
export const CreateHandoffTokenRequest$outboundSchema: z.ZodMiniType<
  CreateHandoffTokenRequest$Outbound,
  CreateHandoffTokenRequest
> = z.object({
  instanceId: z.string(),
});

export function createHandoffTokenRequestToJSON(
  createHandoffTokenRequest: CreateHandoffTokenRequest,
): string {
  return JSON.stringify(
    CreateHandoffTokenRequest$outboundSchema.parse(createHandoffTokenRequest),
  );
}
