/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type FetchInteractionSecurity = {
  customerAccess?: string | undefined;
  interactionAccess?: string | undefined;
};

export const FetchInteractionScope = {
  Subject: "subject",
  Reviewer: "reviewer",
} as const;
export type FetchInteractionScope = ClosedEnum<typeof FetchInteractionScope>;

export type FetchInteractionRequestBody = {
  /**
   * Journey Instance Id, a unique identifier for a started journey instance.
   */
  instanceId: string;
  scope?: FetchInteractionScope | undefined;
  [additionalProperties: string]: unknown;
};

export type FetchInteractionRequest = {
  /**
   * Response profile. Omit or 'full' for the full response (default, unchanged). 'slim' returns the compact, typed customer-facing shape. Any other value returns 400.
   */
  view?: string | undefined;
  body?: FetchInteractionRequestBody | undefined;
};

/**
 * Interaction state (full by default; slim with ?view=slim)
 */
export type FetchInteractionResponse =
  | models.InteractionFetchResponse
  | models.SlimInteractionFetchResponse;

/** @internal */
export type FetchInteractionSecurity$Outbound = {
  CustomerAccess?: string | undefined;
  InteractionAccess?: string | undefined;
};

/** @internal */
export const FetchInteractionSecurity$outboundSchema: z.ZodMiniType<
  FetchInteractionSecurity$Outbound,
  FetchInteractionSecurity
> = z.pipe(
  z.object({
    customerAccess: z.optional(z.string()),
    interactionAccess: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      customerAccess: "CustomerAccess",
      interactionAccess: "InteractionAccess",
    });
  }),
);

export function fetchInteractionSecurityToJSON(
  fetchInteractionSecurity: FetchInteractionSecurity,
): string {
  return JSON.stringify(
    FetchInteractionSecurity$outboundSchema.parse(fetchInteractionSecurity),
  );
}

/** @internal */
export const FetchInteractionScope$outboundSchema: z.ZodMiniEnum<
  typeof FetchInteractionScope
> = z.enum(FetchInteractionScope);

/** @internal */
export type FetchInteractionRequestBody$Outbound = {
  instanceId: string;
  scope?: string | undefined;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const FetchInteractionRequestBody$outboundSchema: z.ZodMiniType<
  FetchInteractionRequestBody$Outbound,
  FetchInteractionRequestBody
> = z.catchall(
  z.object({
    instanceId: z.string(),
    scope: z.optional(FetchInteractionScope$outboundSchema),
  }),
  z.any(),
);

export function fetchInteractionRequestBodyToJSON(
  fetchInteractionRequestBody: FetchInteractionRequestBody,
): string {
  return JSON.stringify(
    FetchInteractionRequestBody$outboundSchema.parse(
      fetchInteractionRequestBody,
    ),
  );
}

/** @internal */
export type FetchInteractionRequest$Outbound = {
  view?: string | undefined;
  body?: FetchInteractionRequestBody$Outbound | undefined;
};

/** @internal */
export const FetchInteractionRequest$outboundSchema: z.ZodMiniType<
  FetchInteractionRequest$Outbound,
  FetchInteractionRequest
> = z.object({
  view: z.optional(z.string()),
  body: z.optional(z.lazy(() => FetchInteractionRequestBody$outboundSchema)),
});

export function fetchInteractionRequestToJSON(
  fetchInteractionRequest: FetchInteractionRequest,
): string {
  return JSON.stringify(
    FetchInteractionRequest$outboundSchema.parse(fetchInteractionRequest),
  );
}

/** @internal */
export const FetchInteractionResponse$inboundSchema: z.ZodMiniType<
  FetchInteractionResponse,
  unknown
> = smartUnion([
  models.InteractionFetchResponse$inboundSchema,
  models.SlimInteractionFetchResponse$inboundSchema,
]);

export function fetchInteractionResponseFromJSON(
  jsonString: string,
): SafeParseResult<FetchInteractionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FetchInteractionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FetchInteractionResponse' from JSON`,
  );
}
