/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Include read-only platform-tier scenarios in the listing. Defaults to false.
 */
export const ListSandboxScenariosIncludePlatform = {
  True: "true",
  False: "false",
} as const;
/**
 * Include read-only platform-tier scenarios in the listing. Defaults to false.
 */
export type ListSandboxScenariosIncludePlatform = ClosedEnum<
  typeof ListSandboxScenariosIncludePlatform
>;

export type ListSandboxScenariosRequest = {
  /**
   * Id of the journey the scenario belongs to. Scenarios are listed, read and resolved per journey.
   */
  journeyId: string;
  /**
   * Include read-only platform-tier scenarios in the listing. Defaults to false.
   */
  includePlatform?: ListSandboxScenariosIncludePlatform | undefined;
};

/** @internal */
export const ListSandboxScenariosIncludePlatform$outboundSchema: z.ZodMiniEnum<
  typeof ListSandboxScenariosIncludePlatform
> = z.enum(ListSandboxScenariosIncludePlatform);

/** @internal */
export type ListSandboxScenariosRequest$Outbound = {
  journeyId: string;
  includePlatform?: string | undefined;
};

/** @internal */
export const ListSandboxScenariosRequest$outboundSchema: z.ZodMiniType<
  ListSandboxScenariosRequest$Outbound,
  ListSandboxScenariosRequest
> = z.object({
  journeyId: z.string(),
  includePlatform: z.optional(
    ListSandboxScenariosIncludePlatform$outboundSchema,
  ),
});

export function listSandboxScenariosRequestToJSON(
  listSandboxScenariosRequest: ListSandboxScenariosRequest,
): string {
  return JSON.stringify(
    ListSandboxScenariosRequest$outboundSchema.parse(
      listSandboxScenariosRequest,
    ),
  );
}
