/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type SearchAddressesSecurity = {
  customerAccess?: string | undefined;
  interactionAccess?: string | undefined;
};

export type SearchAddressesRequest = {
  /**
   * Journey Instance Id, a unique identifier for a started journey instance.
   */
  instanceId: string;
  text: string;
  containerId?: string | undefined;
  limit?: number | undefined;
};

/** @internal */
export type SearchAddressesSecurity$Outbound = {
  CustomerAccess?: string | undefined;
  InteractionAccess?: string | undefined;
};

/** @internal */
export const SearchAddressesSecurity$outboundSchema: z.ZodMiniType<
  SearchAddressesSecurity$Outbound,
  SearchAddressesSecurity
> = z.pipe(
  z.object({
    customerAccess: z.optional(z.string()),
    interactionAccess: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      customerAccess: "CustomerAccess",
      interactionAccess: "InteractionAccess",
    });
  }),
);

export function searchAddressesSecurityToJSON(
  searchAddressesSecurity: SearchAddressesSecurity,
): string {
  return JSON.stringify(
    SearchAddressesSecurity$outboundSchema.parse(searchAddressesSecurity),
  );
}

/** @internal */
export type SearchAddressesRequest$Outbound = {
  instanceId: string;
  text: string;
  containerId?: string | undefined;
  limit?: number | undefined;
};

/** @internal */
export const SearchAddressesRequest$outboundSchema: z.ZodMiniType<
  SearchAddressesRequest$Outbound,
  SearchAddressesRequest
> = z.object({
  instanceId: z.string(),
  text: z.string(),
  containerId: z.optional(z.string()),
  limit: z.optional(z.int()),
});

export function searchAddressesRequestToJSON(
  searchAddressesRequest: SearchAddressesRequest,
): string {
  return JSON.stringify(
    SearchAddressesRequest$outboundSchema.parse(searchAddressesRequest),
  );
}
