/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DeviceRefreshResponse = {
  endUserToken: string;
  expiresIn: number;
  instanceId: string;
  resumeCredential: string;
  credentialExpiresAt: string;
  credentialExpiresIn: number;
  linkExpiresAt: string;
};

/** @internal */
export const DeviceRefreshResponse$inboundSchema: z.ZodMiniType<
  DeviceRefreshResponse,
  unknown
> = z.object({
  endUserToken: types.string(),
  expiresIn: types.number(),
  instanceId: types.string(),
  resumeCredential: types.string(),
  credentialExpiresAt: types.string(),
  credentialExpiresIn: types.number(),
  linkExpiresAt: types.string(),
});

export function deviceRefreshResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeviceRefreshResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeviceRefreshResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeviceRefreshResponse' from JSON`,
  );
}
