/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const DeviceConnectResponseTokenType = {
  EndUser: "end-user",
} as const;
export type DeviceConnectResponseTokenType = ClosedEnum<
  typeof DeviceConnectResponseTokenType
>;

export type DeviceConnectResponse = {
  endUserToken: string;
  tokenType: DeviceConnectResponseTokenType;
  expiresIn: number;
  instanceId: string;
  resumeCredential?: string | undefined;
  credentialExpiresAt?: string | undefined;
  credentialExpiresIn?: number | undefined;
};

/** @internal */
export const DeviceConnectResponseTokenType$inboundSchema: z.ZodMiniEnum<
  typeof DeviceConnectResponseTokenType
> = z.enum(DeviceConnectResponseTokenType);

/** @internal */
export const DeviceConnectResponse$inboundSchema: z.ZodMiniType<
  DeviceConnectResponse,
  unknown
> = z.object({
  endUserToken: types.string(),
  tokenType: DeviceConnectResponseTokenType$inboundSchema,
  expiresIn: types.number(),
  instanceId: types.string(),
  resumeCredential: types.optional(types.string()),
  credentialExpiresAt: types.optional(types.string()),
  credentialExpiresIn: types.optional(types.number()),
});

export function deviceConnectResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeviceConnectResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeviceConnectResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeviceConnectResponse' from JSON`,
  );
}
