/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type InteractionFetchResponseJourney = {
  status: string;
};

export const InteractionFetchResponseCardinality = {
  AtLeastOne: "at-least-one",
} as const;
export type InteractionFetchResponseCardinality = ClosedEnum<
  typeof InteractionFetchResponseCardinality
>;

export type InteractionFetchResponseOutstandingGroup = {
  elementId: string;
  cardinality: InteractionFetchResponseCardinality;
  refs: Array<string>;
};

export type InteractionFetchResponseJoinedDevice = {
  connected: boolean;
};

export type InteractionFetchResponse = {
  instanceId: string;
  interactionId?: string | undefined;
  journey: InteractionFetchResponseJourney;
  interaction?: { [k: string]: any } | undefined;
  context?: { [k: string]: any } | undefined;
  instructions?: any | undefined;
  outstanding?: any | undefined;
  outstandingGroups?:
    | Array<InteractionFetchResponseOutstandingGroup>
    | undefined;
  processing?: boolean | undefined;
  result?: { [k: string]: any } | undefined;
  joinedDevice?: InteractionFetchResponseJoinedDevice | undefined;
};

/** @internal */
export const InteractionFetchResponseJourney$inboundSchema: z.ZodMiniType<
  InteractionFetchResponseJourney,
  unknown
> = z.object({
  status: types.string(),
});

export function interactionFetchResponseJourneyFromJSON(
  jsonString: string,
): SafeParseResult<InteractionFetchResponseJourney, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InteractionFetchResponseJourney$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InteractionFetchResponseJourney' from JSON`,
  );
}

/** @internal */
export const InteractionFetchResponseCardinality$inboundSchema: z.ZodMiniEnum<
  typeof InteractionFetchResponseCardinality
> = z.enum(InteractionFetchResponseCardinality);

/** @internal */
export const InteractionFetchResponseOutstandingGroup$inboundSchema:
  z.ZodMiniType<InteractionFetchResponseOutstandingGroup, unknown> = z.object({
    elementId: types.string(),
    cardinality: InteractionFetchResponseCardinality$inboundSchema,
    refs: z.array(types.string()),
  });

export function interactionFetchResponseOutstandingGroupFromJSON(
  jsonString: string,
): SafeParseResult<
  InteractionFetchResponseOutstandingGroup,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      InteractionFetchResponseOutstandingGroup$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'InteractionFetchResponseOutstandingGroup' from JSON`,
  );
}

/** @internal */
export const InteractionFetchResponseJoinedDevice$inboundSchema: z.ZodMiniType<
  InteractionFetchResponseJoinedDevice,
  unknown
> = z.object({
  connected: types.boolean(),
});

export function interactionFetchResponseJoinedDeviceFromJSON(
  jsonString: string,
): SafeParseResult<InteractionFetchResponseJoinedDevice, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      InteractionFetchResponseJoinedDevice$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InteractionFetchResponseJoinedDevice' from JSON`,
  );
}

/** @internal */
export const InteractionFetchResponse$inboundSchema: z.ZodMiniType<
  InteractionFetchResponse,
  unknown
> = z.object({
  instanceId: types.string(),
  interactionId: types.optional(types.string()),
  journey: z.lazy(() => InteractionFetchResponseJourney$inboundSchema),
  interaction: types.optional(z.record(z.string(), z.any())),
  context: types.optional(z.record(z.string(), z.any())),
  instructions: types.optional(z.any()),
  outstanding: types.optional(z.any()),
  outstandingGroups: types.optional(
    z.array(
      z.lazy(() => InteractionFetchResponseOutstandingGroup$inboundSchema),
    ),
  ),
  processing: types.optional(types.boolean()),
  result: types.optional(z.record(z.string(), z.any())),
  joinedDevice: types.optional(
    z.lazy(() => InteractionFetchResponseJoinedDevice$inboundSchema),
  ),
});

export function interactionFetchResponseFromJSON(
  jsonString: string,
): SafeParseResult<InteractionFetchResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InteractionFetchResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InteractionFetchResponse' from JSON`,
  );
}
