/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const JourneyStartResponseStatus = {
  Started: "started",
} as const;
export type JourneyStartResponseStatus = ClosedEnum<
  typeof JourneyStartResponseStatus
>;

export type JourneyStartResponse = {
  instanceId: string;
  instanceUrl?: string | undefined;
  status: JourneyStartResponseStatus;
  message?: string | undefined;
};

/** @internal */
export const JourneyStartResponseStatus$inboundSchema: z.ZodMiniEnum<
  typeof JourneyStartResponseStatus
> = z.enum(JourneyStartResponseStatus);

/** @internal */
export const JourneyStartResponse$inboundSchema: z.ZodMiniType<
  JourneyStartResponse,
  unknown
> = z.object({
  instanceId: types.string(),
  instanceUrl: types.optional(types.string()),
  status: JourneyStartResponseStatus$inboundSchema,
  message: types.optional(types.string()),
});

export function journeyStartResponseFromJSON(
  jsonString: string,
): SafeParseResult<JourneyStartResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => JourneyStartResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'JourneyStartResponse' from JSON`,
  );
}
