/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  StateFetchResponse,
  StateFetchResponse$inboundSchema,
} from "./state-fetch-response.js";

export const JourneyStartResponseStatus = {
  Started: "started",
  Completed: "completed",
  Failed: "failed",
  AwaitingInput: "awaiting-input",
  Pending: "pending",
} as const;
export type JourneyStartResponseStatus = OpenEnum<
  typeof JourneyStartResponseStatus
>;

export type JourneyStartResponse = {
  instanceId: string;
  instanceUrl?: string | undefined;
  status: JourneyStartResponseStatus;
  message?: string | undefined;
  waitedSeconds?: number | undefined;
  state?: StateFetchResponse | undefined;
};

/** @internal */
export const JourneyStartResponseStatus$inboundSchema: z.ZodMiniType<
  JourneyStartResponseStatus,
  unknown
> = openEnums.inboundSchema(JourneyStartResponseStatus);

/** @internal */
export const JourneyStartResponse$inboundSchema: z.ZodMiniType<
  JourneyStartResponse,
  unknown
> = z.object({
  instanceId: types.string(),
  instanceUrl: types.optional(types.string()),
  status: JourneyStartResponseStatus$inboundSchema,
  message: types.optional(types.string()),
  waitedSeconds: types.optional(types.number()),
  state: types.optional(StateFetchResponse$inboundSchema),
});

export function journeyStartResponseFromJSON(
  jsonString: string,
): SafeParseResult<JourneyStartResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => JourneyStartResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'JourneyStartResponse' from JSON`,
  );
}
