/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Schema = {
  interactionId: string;
  instruction?: string | undefined;
  schema: { [k: string]: any };
};

export type SchemaFetchResponse = {
  deliveryId: string;
  resolvedVersion: string;
  schemas: Array<Schema>;
};

/** @internal */
export const Schema$inboundSchema: z.ZodMiniType<Schema, unknown> = z.object({
  interactionId: types.string(),
  instruction: types.optional(types.string()),
  schema: z.record(z.string(), z.any()),
});

export function schemaFromJSON(
  jsonString: string,
): SafeParseResult<Schema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Schema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Schema' from JSON`,
  );
}

/** @internal */
export const SchemaFetchResponse$inboundSchema: z.ZodMiniType<
  SchemaFetchResponse,
  unknown
> = z.object({
  deliveryId: types.string(),
  resolvedVersion: types.string(),
  schemas: z.array(z.lazy(() => Schema$inboundSchema)),
});

export function schemaFetchResponseFromJSON(
  jsonString: string,
): SafeParseResult<SchemaFetchResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SchemaFetchResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SchemaFetchResponse' from JSON`,
  );
}
