/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * Scenario payload (ScenarioPayload). Requires `modules`; optionally `defaultOutcome`, `description`, and extra passthrough fields. Validated by the store against the same schema the sandbox runtime enforces, so an accepted document is guaranteed runnable.
 */
export type UpdateSandboxScenarioRequestData = {};

export type UpdateSandboxScenarioRequest = {
  /**
   * Scenario payload (ScenarioPayload). Requires `modules`; optionally `defaultOutcome`, `description`, and extra passthrough fields. Validated by the store against the same schema the sandbox runtime enforces, so an accepted document is guaranteed runnable.
   */
  data: UpdateSandboxScenarioRequestData;
};

/** @internal */
export type UpdateSandboxScenarioRequestData$Outbound = {};

/** @internal */
export const UpdateSandboxScenarioRequestData$outboundSchema: z.ZodMiniType<
  UpdateSandboxScenarioRequestData$Outbound,
  UpdateSandboxScenarioRequestData
> = z.object({});

export function updateSandboxScenarioRequestDataToJSON(
  updateSandboxScenarioRequestData: UpdateSandboxScenarioRequestData,
): string {
  return JSON.stringify(
    UpdateSandboxScenarioRequestData$outboundSchema.parse(
      updateSandboxScenarioRequestData,
    ),
  );
}

/** @internal */
export type UpdateSandboxScenarioRequest$Outbound = {
  data: UpdateSandboxScenarioRequestData$Outbound;
};

/** @internal */
export const UpdateSandboxScenarioRequest$outboundSchema: z.ZodMiniType<
  UpdateSandboxScenarioRequest$Outbound,
  UpdateSandboxScenarioRequest
> = z.object({
  data: z.lazy(() => UpdateSandboxScenarioRequestData$outboundSchema),
});

export function updateSandboxScenarioRequestToJSON(
  updateSandboxScenarioRequest: UpdateSandboxScenarioRequest,
): string {
  return JSON.stringify(
    UpdateSandboxScenarioRequest$outboundSchema.parse(
      updateSandboxScenarioRequest,
    ),
  );
}
